### ISSUE TITLE
TypeError: null is not an object (evaluating '_ReanimatedModule.default.createNode')

### ISSUE THREAD

**Issue by RamonaVint** [software-mansion/react-native-reanimated#1177]
Android app crashes after upgrading to react native 0.63.2

Steps to reproduce:
-upgrade react native from 0.59.9 to 0.63.2
-react-native run-android

- React: 16.13.1
- React Native:0.63.2
- React Native Reanimated:1.13.0

**Comment by jakub-gonet** [comment]
Try unlinking reanimated and run yarn. If that won't help, reset your metro caches, watchman caches, remove `node_modules`, clear gradle and ios builds.

Report back if it won't help.

**Comment by RamonaVint** [comment]
This doesn't help and is very annoying. I spend so much time on it..

**Comment by terrysahaidak** [comment]
Unfortunately, there is no way to reproduce the error or help you without any code from your side. Please, make sure you run `graldlew clean` after changing `enableHermes`.

**Comment by RamonaVint** [comment]
I don't know which part of code would help to figure this out

**Comment by terrysahaidak** [comment]
Since you upgraded the React Native, make sure to double-check upgrading instructions. Also, you can verify by creating a new project with RN 0.63.2 and Reanimated 1.13.0 that it works as expected. If so, the problem is definitely in some things you missed from upgrading instructions.

Also, starting from RN 0.60 there is auto-linking support so make sure to remove any manual linking from the project and use the latest version of RN-CLI.

Also, personal advice: it's easier to create a whole new project than upgrading from 0.59 to 0.63.
