### ISSUE TITLE
Jest not resolving the module

### ISSUE THREAD

**Issue by mgambati** [software-mansion/react-native-reanimated#1196]
## Description

Jest isn't able to use the `react-native` field of package.json and tries to use the `main` field, which points to a `lib/commonjs/Animated` that don't exist in the dist.

### Screenshots
![image](https://user-images.githubusercontent.com/813131/92275972-23338f80-eebe-11ea-8aaa-267411b65dde.png)

## Steps To Reproduce

1. Install react-native-reanimated@alpha
2. Create a test file and imports `react-native-reanimated`
3. Run the test

### Expected behavior
Be able to import the module normally.

### Actual behavior
It crashes the testing suite.

I was able to resolve it temporarily by change jest config like this:

```json
"moduleNameMapper": {
    "^react-native-reanimated$":"<rootDir>/node_modules/react-native-reanimated/src/Animated.js"
},
```

Ideally changing the `main` and `module` fields to point to the right path should fix it.

## Package versions

- React: 16.13.1
- React Native: 0.63.2
- React Native Reanimated: 2.0.0-alpha.5

**Comment by taschik** [comment]
@mgambati Thank you so much! this saved my day!  👏 
Previously used the 2.3.0-alpha.2 and it wasn't necessary but after upgrading to 2.3.0-beta.3 jest broke but the workaround fixes it.

**Comment by bcgilliom** [comment]
I also had this happen after using the latest commit on `main` in package.json:

`"react-native-reanimated": "git+https://github.com/software-mansion/react-native-reanimated.git#7820ec095de7a719150dc5021561f0b8b0b10f38",`

It seems to work fine in the app, but crashes the tests. The above name mapper seems to fix it, although I'm not sure why...

flagging JIC this is a regression and not a side effect of me using a commit in package.json instead of an npm release 😄 as it seemed like 2.3.1 worked as expected

**Comment by Dakuan** [comment]
same, 2.4 breaks my tests
