### ISSUE TITLE
Slide animation is not working in Android

### ISSUE THREAD

**Issue by dion-george** [software-mansion/react-native-reanimated#1348]
## Description
The slide-right and slide-left animation is working fine on iOS but the animation is not horizontal and abrupt in Android.

## Code

```js
<Transition.In
  type="slide-right"
  durationMs={300}
  delayMs={0}
  interpolation="easeInOut"
/>
<Transition.Out type="slide-left" durationMs={300} interpolation="easeInOut" />
```
### Package versions

- React Native: "0.62.2"
- React Native Reanimated: "1.9.0"

**Comment by jakub-gonet** [comment]
We discussed Transitions internally in our team. Considering that v2 makes creating animations easier and Transitions was an experimental API for a long time, we decided to leave Transitions as they are.

We won’t actively fix bugs and improve docs, but we’ll happily merge any PR with fixes. We’re also thinking about rewriting Transitions in v2 sometime in the future.

I’m closing this issue, but if you have further questions, I will be happy to help.

**Comment by Strate** [comment]
@jakub-gonet hello,

i see that you closing issues related to Transitions API, because there is more easier Animation api in v2.

But I cannot realize how to implement transitions with that api. Especially related to layout changes, for exmple when adding a node should move other nodes to other positions. Do you have some examples of that?

**Comment by jakub-gonet** [comment]
@Strate I'm not sure what you mean by "node". That animation can be implemented by creating shared values for nodes positions and updating them when a new one is added. Please check our examples, maybe something will help you in implementing this. If you have further questions I'm happy to help.

**Comment by Strate** [comment]
@jakub-gonet thank you for answer. I'll try to be more clear.

Imagine you have this kind of component:
```
<View style={{flexDirection: "row"}}>
  {this.state.leftVisible ? <Text style={{flexGrow: 1, textAlign: "center"}}>Left text</Text> : null}
  {this.state.rightVisible ? <Text style={{flexGrow: 1, textAlign: "center"}}>Right text</Text> : null}
</View>
```

This renders to horizontal-layouted view, with 2 children, each one can have full-width of parent (because of flexGrow: 1).
But when "Right text" node get mounted, "Left text" node change its width to half of parent. If I want to animate that change of width width Animated or Reanimated, I should know final width of "Left text" node, which leads me to manage layouts of nodes in javascript-side, use onLayout prop and etc.

With Transitional.View this task leads to simply call `.configureNext()` right before children change and all, without need to know of all layouts and other things.
