### ISSUE TITLE
What is the alternative for Animated.Value.addListener

### ISSUE THREAD

**Issue by chj-damon** [software-mansion/react-native-reanimated#1417]
## Description

in react-native, Animated.Value can add listener to listen to the value change. my question is, how I can do the same effect with reanimated?

## Code
```js 
const animatedValue = useRef(new Animated.Value(0)).current;

useEffect(() => {
	animatedValue.addListener(val => {
		// do something
	});
}, []);

// what should I do with reanimated?
```

### Package versions

- React: 16.11
- React Native: 0.63.0
- React Native Reanimated: v1

**Comment by jakub-gonet** [comment]
The simplest way to do that is to use a [`call()` node](https://docs.swmansion.com/react-native-reanimated/docs/1.x.x/nodes/call). Another way is to use `animation.start(callback)`, see [this thread](https://github.com/software-mansion/react-native-reanimated/issues/299) for more info, [this comment from William should help you](https://github.com/software-mansion/react-native-reanimated/issues/299#issuecomment-498034651).

Besides, you shouldn't be using `useRef(new Animated.Value(0)).current;` because Animated Value will be created regardless if it's cached (`useRef` will reject second call so Value will be created and immediately GCed). Check out [`useValue()` hook](https://docs.swmansion.com/react-native-reanimated/docs/1.x.x/value).

**Comment by chj-damon** [comment]
thanks.
