### ISSUE TITLE
App is not starting up (RC 1) : ReferenceError: Can't find variable: _setGlobalConsole

### ISSUE THREAD

**Issue by JB-CHAUVIN** [software-mansion/react-native-reanimated#1546]
### Screenshots
![image](https://user-images.githubusercontent.com/8957878/102633103-440fb000-4150-11eb-8753-7e70f0bff83c.png)

### Expected behavior
App should start.

### Actual behavior
App is stuck (error on start).

## Package versions

- React Native: 0.63
- React Native Reanimated: v2 RC 1

**Comment by JB-CHAUVIN** [comment]
An other similar issue after RC 0 to RC 1 upgrade :
![Uploading image.png…]()

**Comment by piaskowyk** [comment]
Hey @JB-CHAUVIN,
Just for sure - did you try to clean cache? 
for example:
`yarn cache clean && rm -r node_modules && yarn && cd ios && pod install && cd .. && yarn start --reset-cache`

**Comment by mym0404** [comment]
In my case, `yarn start --reset-cache` is working for me.

**Comment by yleclanche** [comment]
I had the same issue while using expo. I had to revert to 2.0.0-rc.0.

**Comment by nandorojo** [comment]
> I had the same issue while using expo. I had to revert to 2.0.0-rc.0.

Same here. I also tried `expo start -c` with no luck

**Comment by karol-bisztyga** [comment]
Hey!
I see two cases here: either you didn't clear the cache or you are using expo.
In the second case, AFAIK, [the latest version of reanimated 2, that expo supports is rc.0](https://docs.expo.io/versions/latest/sdk/reanimated/#experimental-support-for-v2-alpha). Since rc.1 has native changes it won't work with rc.1. You can downgrade to rc.0 or wait for the expo to support rc.1.
The error you posted here comes exactly from [this change](https://github.com/software-mansion/react-native-reanimated/pull/1482/files#diff-450c1d3af9a73a380ef302aae14da8a43088352eccb72446ba5bdd603d6decbfR128).

**Comment by karol-bisztyga** [comment]
@JB-CHAUVIN I checked and this error also happens when you forget to add our babel plugin to babel config. Maybe that's your problem? Info [here](https://docs.swmansion.com/react-native-reanimated/docs/installation)

**Comment by alexandrughinea** [comment]
Not yet working with RN63.4+Typescript and Reanimated RC 1. I have tried downgrading to RC 0, almost same type of issue `ReferenceError: Can't find variable: _set*****. Any pointers?

**Comment by karol-bisztyga** [comment]
> Can't find variable: _set*****. Any pointers?

I see but what's the exact message in both cases? Those `***` actually matter a lot. So could you tell me what stood for the stars `***` for `rc.0` and for `rc.1`?

**Comment by tr3v3r** [comment]
The same here. 
RN63.4+Typescript and Reanimated RC 1

**Comment by wxsms** [comment]
> @JB-CHAUVIN I checked and this error also happens when you forget to add our babel plugin to babel config. Maybe that's your problem? Info [here](https://docs.swmansion.com/react-native-reanimated/docs/installation/#babel-plugin)

This is the answer for me. Add that plugin, restart with `--reset-cache`, problem solved. Thank you very much.

**Comment by piaskowyk** [comment]
In my case worked when I did:
- clean cache and node_modules - `yarn cache clean && rm -r node_modules && yarn && cd ios && pod install`
- uninstall application from device
- rebuild and install again application on device
- run server with `yarn --reset-cache`

**Comment by jakubgrzelak** [comment]
The same problem for me @piaskowyk solution didn't work for me

**Comment by aca-hakan-pinar** [comment]
Same issue :(

**Comment by 11kodykay11** [comment]
I am using expo and `rc.2` and ran into this issue suddenly. After reading this thread and [this](https://github.com/software-mansion/react-native-reanimated/issues/1542), I tried everything and the only workaround working is commenting out `_setGlobalConsole(console)` in `node_modules/react-native-reanimated/src/reanimated2/core.js`.
This comment is for those who are still struggling with this issue and not able to proceed like me. :)

**Note**: updating the package or reinstalling node_modules will reintroduce the issue until its fixed in react-native-reanimated

**Comment by guymross** [comment]
Honestly, wouldn't it be easier to die, be reincarnated and live a new life as not a programmer, than use this library?

**Comment by guymross** [comment]
> Honestly, wouldn't it be easier to die, be reincarnated and live a new life as not a programmer, than use this library?

Just a bit of frustrated dark humor as been trying to compile for 2 days now.

**Comment by tgwow** [comment]
I was able to solve by installing [2.0.0-rc.0](https://github.com/software-mansion/react-native-reanimated/releases/tag/2.0.0-rc.0)  version

**Comment by tgwow** [comment]
> I am using expo and `rc.2` and ran into this issue suddenly. After reading this thread and [this](https://github.com/software-mansion/react-native-reanimated/issues/1542), I tried everything and the only workaround working is commenting out `_setGlobalConsole(console)` in `node_modules/react-native-reanimated/src/reanimated2/core.js`.
> This comment is for those who are still struggling with this issue and not able to proceed like me. :)
> 
> **Note**: updating the package or reinstalling node_modules will reintroduce the issue until its fixed in react-native-reanimated

After commenting this I got a new error:  to synchronous call function {assign} from different thread.

I'm using SDK: 40 and rc.2, I already tried to clean all caches and none of theses works for me
