### ISSUE TITLE
[Question] change value of duration

### ISSUE THREAD

**Issue by bjartebore** [software-mansion/react-native-reanimated#166]
Is there any way to dynamically change the value of config.duration for timing()? I would like to continue my animation with a new sequence with a different duration.

**Comment by osdnk** [comment]
Hey,
Terribly sorry for a long answer!
Answering your question, you can use animated nodes inside the timing's config. 
I think this issue is outdated for you and decided to close it.
If you still face the problem, please let me know.

**Comment by vamshi9666** [comment]
@osdnk  i am trying to build instagram clone and its stories effect.For progress bar in story , i am animating width value , when user longPresses , i need to stop animation and start again when released. I managed to get this working.

problem: 
it takes same duration even from middle of progress, say 10 secs from 0 to 100, But as i am stopping and resuming its taking same time even from middle , say 60 to 100.

**Comment by MaskoMasko** [comment]
@vamshi9666, I'm late, but better late than never. It might be helpful to someone else now. 
In version 3.x, I resolved it by using the `withSequence` animation. Basically, we can run `withTiming` with the first duration value, reset it with the second, and so on...
```
const myValue = useSharedValue(0);
myValue.value = withSequence(
      withTiming(1, { duration: 4000 }),
      withTiming(0, { duration: 0 }),
      withTiming(1, { duration: 8000 }),
      // ...
);
```
Of course, this is a simplified version, but you get the idea. I didn't manage to find any other way to achieve the same. If there is a better way to solve this issue, please provide an answer because I don't really like this one myself.
