### ISSUE TITLE
useSharedValue is not a function

### ISSUE THREAD

**Issue by alakdam07** [software-mansion/react-native-reanimated#1671]
I literally copy paste the below code from react-native-reanimated docs. I am getting this error: `TypeError: (0, _reactNativeReanimated.useSharedValue) is not a function. (In '(0, _reactNativeReanimated.useSharedValue)(0)', '(0, _reactNativeReanimated.useSharedValue)' is undefined)`

```
import React from 'react'
import Animated, { useSharedValue, useAnimatedStyle } from 'react-native-reanimated';


export default function App() {
  const offset = useSharedValue(0);

  const animatedStyles = useAnimatedStyle(() => {
    return {
      transform: [{ translateX: offset.value * 255 }],
    };
  });

  return (
    <>
      <Animated.View style={[styles.box, animatedStyles]} />
      <Button onPress={() => (offset.value = Math.random())} title="Move" />
    </>
  );
}
```

this is my reanimated's package version `"react-native-reanimated": "~1.13.0",`

**Comment by piaskowyk** [comment]
Hey @alakdam07 
It is because you use an old version of reanimated. We introduced these functions in Reanimated v2. Please use the newer version for example [2.0.0-rc.2](https://github.com/software-mansion/react-native-reanimated/releases/tag/2.0.0-rc.2)
You can install this by the following command: `yarn add react-native-reanimated@next` or `yarn add react-native-reanimated@2.0.0-rc.2`
