### ISSUE TITLE
Size of app (.apk) has increased about 8 MB after upgrade from rc.1 to rc.2 

### ISSUE THREAD

**Issue by ahanusek** [software-mansion/react-native-reanimated#1675]
After upgrade Reanimated v2 to latest version (2.0.0-rc.2) size of app has increased about 8MB for .apk. 

### Screenshots

![Group 4](https://user-images.githubusercontent.com/16654786/106260560-d2cc1e00-6220-11eb-80d9-0205526a9fe7.png)

## Steps To Reproduce

1. Upgrade RNReanimated to rc.2
2. Check size of app
3. Downgrade RNReanimated to rc.1
4. Check size of app

### Expected behavior

Maybe I'm wrong, but app size shouldn't increase that significantly from one version to another.

## Package versions

- React: 16.13.1
- React Native: 0.63.4
- React Native Reanimated: 2.0.0-rc.2 / 2.0.0-rc.1
- NodeJS: 12.16.1

**Comment by kmagiera** [comment]
Thanks for reporting. Unfortunately this issue does not provide any instructions on how we can reproduce the issue, so here is what we tried:

1. Init new react-native project
2. Make release build with `gradlew clean assembleDebug assembleRelease`
3. Install reanimated rc-1 -> do another build
4. Install reanimated rc-2 -> do another build

After trying this the apk sizes are roughly the same for rc-1 and rc-2 builds both for debug and release apks: 23M (plain), 24M (with rc-1), 24M (with rc-2)
debug apks: 34M (plain), 35M (with rc-1), 34M (with rc-2)

Note that the resulting apk is not what gets distributed to the users via google play store as the apk may include binaries for all architectures enabled at the build time vs only the phone's architecture binaries that gets delivered when you install the app from play store.

I'm closing this issue as it appears there is no difference between builds from the testing we've done and the report does not provide any more details for us to be able to tell how your setup can be different.

If you can provide a repro scenario that we can follow please open a new issue. Otherwise you may also try to investigate the issue on your own by checking the content of these apks. APK files are just zip archives containing compiled classes and prebuilt libraries. You should be able to locate files that have significantly different sizes in between these two versions. I suspect what may have happened is that the rc-2 build either includes binaries for some additional CPU architecture, or maybe you are accidently pulling in some large libraries like Javascriptcore (look for `.so` files that are in the resulting APK and not in the previous one)
