### ISSUE TITLE
[Feature] have easing in interpolation

### ISSUE THREAD

**Issue by F4b1n0u** [software-mansion/react-native-reanimated#168]
if the same value is supposed to animated 2 difference things at the same time but with different easing, in React.Animated, a simple interpolation can do the trick, but the Reanimated.interpolate node does not let us apply an easing,

does someone could give me a hand to implement that ?

**Comment by kmagiera** [comment]
Hey @F4b1n0u ! Thanks for reaching out. Unfortunately this feature isn't on our immediate roadmap. We'd be open to accepting this as a contribution. If you need pointers please check this file where implementation of interpolate node is located:
https://github.com/software-mansion/react-native-reanimated/blob/master/src/derived/interpolate.js

We also have all the easing functions implemented here (we use them for timing animations):
https://github.com/software-mansion/react-native-reanimated/blob/master/src/derived/interpolate.js

Thanks!

**Comment by helixbass** [comment]
This is a useful feature to have (that React Native `Animated`'s `interpolate()` supports)

@F4b1n0u since `interpolate()` is implemented purely in JS it's possible to "override" and use your own version (without forking Reanimated)

Eg here's a version that seems to be working for me in order to pass `easing` as an option to `interpolate()`: https://gist.github.com/helixbass/109f64470fe8beab25843b1873d61906

So then you can call eg:
```
interpolate(someTiming.state.position, {
  inputRange: [0, 1],
  outputRange: [0, 100],
  easing: Easing.inOut(Easing.ease),
})
```

@kmagiera I can probably open a PR with this change

**Comment by hosseinmd** [comment]
This code works for me.
```js
              style={{
                opacity: interpolate(Easing.in(Easing.exp)(anim), {
                  inputRange: [0, MAX_TOP],
                  outputRange: [1, 0],
                }),
              }}
```
