### ISSUE TITLE
compatible with web (i.e. react-native-web)? 

### ISSUE THREAD

**Issue by alidcastano** [software-mansion/react-native-reanimated#169]
Was hoping you could clarify in advance - is the reanimted API compatible with web? wanted to get your input before using it for that, thanks

**Comment by grit96** [comment]
I tried to use this library via the [react-native-tab-view@^2.0.1](https://github.com/react-native-community/react-native-tab-view) update in my project that is using [react-native-web](https://github.com/necolas/react-native-web).

It appears to not be compatible with `react-native-web` due to a dependency on `BoundingDimensions` in `Touchable` but I did not dig any deeper than that.

**Comment by geminiyellow** [comment]
same error.

```
Failed to compile.

./node_modules/react-native-tab-view/src/TabBar.js
Module not found: Can't resolve 'react-native-reanimated' in '/Users/**/*/node_modules/react-native-tab-view/src'
```

**Comment by ziaulrehman40** [comment]
Web support will be highly useable. Making many other libraries useable on web.

**Comment by RichardLindhout** [comment]
@EvanBacon is working on it, with some really impressive results!
https://twitter.com/Baconbrix/status/1173825701192929280

See this running example
https://reanimated.netlify.com/#/IMapPanel

**Comment by geminiyellow** [comment]
holy good, working, thanks all.
