### ISSUE TITLE
Multi-cond (if..elseif..elseif..)

### ISSUE THREAD

**Issue by radex** [software-mansion/react-native-reanimated#174]
Using `cond` gets messy in terms of readability when you have a whole chain of extra conditions — code equivalent to flat `if.. else if .. else if ... else if... else ...` becomes deeply nested and hard to quickly understand.

I propose to add something like (exact API to be discussed):

```
conds(
  [ifThisIsTrue, thenEvaluateThis],
  [ifThatIsTrue, thenEvalThat],
  ...,
  elseEvalThisLastBit
)
```

This would simply desugar to a nested `cond()`, without any particular node code.

I'm proposing this to get the opinion if this (implemented just as sugar) would be accepted. If it's cool, I will send a PR. @osdnk @kmagiera WDYT?

**Comment by kmagiera** [comment]
I like the idea. Definitely feel a need for such a syntax. I'd have used it in several places already. As for the exact syntax I'd like to discuss that a bit more tho. I think it would be nice to model this after lisp/closure if possible instead of introducing a separate name. This should be doable as we could handle it differently depending on the number of arguments.

On the other hand I like the approach with using arrays to separate conditions. This seem to be more readable than just listing method arguments one by one. 

Anyone else would like to chime in? cc @osdnk

**Comment by radex** [comment]
> On the other hand I like the approach with using arrays to separate conditions

the inspiration comes from `cond()` in Ramda, where consecutive conditions come in pairs (expressed as two-element arrays).

The problem with the exact syntax I suggested is that for the `else` clause there is no reliable way (I think) to disambiguate between a condition-value pair and a Block given as en `else` clause. So else would need to be mandatory — but it's easy to forget.

**Comment by kmagiera** [comment]
We could also have sth along these lines:
```
conds(
  [(lessThen n -1), thenEvaluateThis],
  [(greaterThen n 1), evaluateThis],
  [else somethingElse]
```

Where `else` would just be an `Animated.Value(1)`

**Comment by naftalibeder** [comment]
For anybody needing a decent solution in the meantime, I've had a decent time with this relatively flat pattern:

```
cond(
  lessThan(n, 5),
  [...]
),
cond(
  and(greaterOrEq(n, 5), lessThan(n, 10)),
  [...]
),
cond(
  and(greaterOrEq(n, 10), lessThan(n, 15)),
  [...]
),
```

It's limited - more like a switch statement without fallthrough - but is certainly better than

```
cond(
  lessThan(n, 5),
  [...],
  cond(
    lessThan(n, 10),
    [...],
      cond(
        lessThan(n, 15),
        [...]
    ),
  ),
),
```

I'd love a `conds()` like @kmagiera suggested above!

**Comment by kmagiera** [comment]
Closing this as it seem we couldn't find a good design for this functionality. Note that this can be implemented in userland, and to us the focus now is to work on stabilizing Reanimated 2 api rather than add new features to the old core. Happy to accept this as a PR if there is anyone willing to work on this – we can even publish it both as part of 1.x and 2.x releases in such a case
