### ISSUE TITLE
When deleting an item from FlatList's data the Touchable inside gets stuck

### ISSUE THREAD

**Issue by alexpchin** [software-mansion/react-native-reanimated#1750]
## Description

I have an animated list in which each item has a button in it to remove from the list. After pressing, the item removes from the list but the Touchable doesn't disappear but instead replaces the button of the next one in the list. It is like the Component key has become confused. 

There seems to be an issue if you use index in `keyExtractor={(_, index) => String(index)}`.

### Video

[simulator1.mov.zip](https://github.com/software-mansion/react-native-reanimated/files/6039832/simulator1.mov.zip)

## Steps To Reproduce

Please see code.

### Expected behavior

Deleting an item should remove the button from the list.

### Actual behavior

The Touchable Button seems to linger.

## Snack or minimal code example

https://github.com/alexpchin/react-native-reanimated-bugs

## Package versions

- React: `16.13.1`
- React Native: `0.63.4`
- React Native Reanimated: `2.0.0-rc.0` (my app) & `2.0.0-rc.3` (example)

**Comment by alexpchin** [comment]
This isn't a bug with react-native-reanimated v2. I think it's a react or react-native bug.

The issue is created when I remove an item when I use the keyextractor: 

```js
const keyExtractor = (_, index) => String(index)
```

If you don't use the index and instead use something unique to each. item, i.e.

```js
const keyExtractor = (item) => item.id;
```

Then the issue isn't there.

**Comment by jakub-gonet** [comment]
I'm pretty sure this isn't a bug. React (Native) relies on unique keys to memoize rendered components. Let's say you have three components that have ids in range 1..3. When you remove the second component, then the third will have index=2 and index=3 won't be mapped to any component. That's why using [an index is discouraged](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/no-array-index-key.md) when your list [is modified](https://stackoverflow.com/a/59518081). `keyExtractor` act as [key provider](https://reactnative.dev/docs/flatlist#keyextractor) so it suffers from the same problem.

I'm going to close this one, if you have further questions I'm happy to help.
