### ISSUE TITLE
Animated node with ID 2 already exists

### ISSUE THREAD

**Issue by TijsM** [software-mansion/react-native-reanimated#1781]
## Description
When installing and using Reanimated v2 I keep on getting the ```Animated node with ID 2 already exists``` error. 
This only happens on Android though.

(I'm not using pure reanimated but i'm using [Moti](https://moti.fyi/), which relies on Reanimated V2)

I found that people had similar issues because they had a dependency that used Reanimated V1 (~1.13.0), for this is the case as well, but I can't figure out a way to work around this

### Screenshots

<img src="https://user-images.githubusercontent.com/36442007/109790599-df71d680-7c11-11eb-8f43-fdc2fdac2c56.png" width="300">

## Package versions

- React: 16.13.1
- React Native: ~0.63.2
- React Native Reanimated: 2.0.0-rc.0
- NodeJS: 12.16.1

**Comment by piaskowyk** [comment]
Hey @TijsM 
We have had a similar issue already. This is most likely caused by two instances of reanimated running simultaneously. More informations here https://github.com/software-mansion/react-native-reanimated/issues/1072#issuecomment-695782662 and here https://github.com/software-mansion/react-native-reanimated/issues/742#issuecomment-633151494.

The same resolved issues:
- https://github.com/software-mansion/react-native-reanimated/issues/1429
- https://github.com/software-mansion/react-native-reanimated/issues/1072
- https://github.com/software-mansion/react-native-reanimated/issues/742

Let me know if it works for you.

**Comment by kmagiera** [comment]
Have you tried putting Reanimated v2 in the resolutions section such that it enforces use of v2 across all the modules which depend on Reanimated? Version 2 of reanimated contains all the methods from v1 so the code written for v1 is expected to work.
https://classic.yarnpkg.com/en/docs/selective-version-resolutions/#toc-how-to-use-it

**Comment by jakub-gonet** [comment]
As kmagiera mentioned you should try using the resolutions section to make sure that one version will be used. For more context: when you have multiple versions of Reanimated they still share one native module but they're executing independently so at some point they'll use the same id, crashing the native module.

This issue is a bit old. If you still experience this problem, please reply.

**Comment by IjzerenHein** [comment]
Depending on the version of Moti that you are using, Moti used to declare `react-native-reanimated` as a (dev-)dependency, which may have caused problems (and required a resolution to fix). This is no longer the case with the latest version of moti, and you need to explicitly add `react-native-reanimated` to your dependencies. We also had problems with Snack in that regard. Hope that helps.

**Comment by letehaha** [comment]
> Have you tried putting Reanimated v2 in the resolutions section such that it enforces use of v2 across all the modules which depend on Reanimated? Version 2 of reanimated contains all the methods from v1 so the code written for v1 is expected to work. https://classic.yarnpkg.com/en/docs/selective-version-resolutions/#toc-how-to-use-it

Just faced the same problem with `react-native-skeleton-content` which used version 2.1.0 and Expo which required version 2.14.4, and dependency resolution helped 👍
