### ISSUE TITLE
[LayoutAnimations] can't combine enter/exit of the same type

### ISSUE THREAD

**Issue by hannojg** [software-mansion/react-native-reanimated#2539]
## Description

For `layout` animations we have [EntryExit transitions](https://docs.swmansion.com/react-native-reanimated/docs/api/LayoutAnimations/layoutTransitions#entryexit-transition), where we can "combine" an exit and enter animation using `combineTransition`.

### Expected behavior

Take an entering and an exiting animation of the same type, for example exiting: ZoomOut, entering ZoomIn.
You'd expect the view to first disappear with a scale effect, and then reappear with the same effect.

### Actual behavior & steps to reproduce

If you look [at the code](https://github.com/software-mansion/react-native-reanimated/blob/97bc537a3d2b8fd65abfb58c1649ad0035851535/src/reanimated2/layoutReanimation/defaultTransitions/EntryExitTransition.ts#L147-L150) of `combineTransition` you can see that it _merges_ the initial values, with the entering animation merging in last. This causes for example the scale property to be set to zero immediately. So, the animation just makes the view scale: 0.
See this video for example:

https://user-images.githubusercontent.com/16821682/137214115-c27c691c-9eda-42e6-bd18-2ded94599cd1.mov

```js
              <Animated.Text
                layout={combineTransition(
                  ZoomOut.duration(1000),
                  ZoomIn.duration(1000).springify()
                )}>
                {level}
              </Animated.Text>
```

## Snack or minimal code example

You should be able to reproduce this by changing in the waterfall example the ExitEnter animation to e.g. ZoomIn, ZoomOut.

## Package versions

- React Native: 0.65.1
- React Native Reanimated: 2.3.0-beta.2
- NodeJS: 14
- Xcode: 12
- Java & Gradle: /

## Affected platforms

- [x] Android
- [x] iOS
- [ ] Web

> P.S.: Except for this bug, LayoutAnimations are truly awesome, big thx for making them! ❤️

**Comment by tomekzaw** [comment]
Hello! Thanks for reporting. Indeed, there is some problem related to `combineTransition` that we need to fix.

```tsx
<Animated.Text
  layout={combineTransition(
    ZoomOut.duration(1000),
    ZoomIn.duration(1000)
  )}>
  {level}
</Animated.Text>
```

<details>
<summary>Example1.tsx</summary>

```tsx
import Animated, {
  ZoomIn,
  ZoomOut,
  combineTransition,
} from 'react-native-reanimated';

import React from 'react';
import { View } from 'react-native';

export default function Example1() {
  const [level, setLevel] = React.useState(0);

  const handlePress = () => {
    setLevel((level) => level + 1);
  };

  return (
    <View
      style={{ flex: 1, alignItems: 'center', justifyContent: 'center' }}
      onTouchStart={handlePress}>
      <Animated.Text
        layout={combineTransition(
          ZoomOut.duration(1000),
          ZoomIn.duration(1000)
        )}
        style={{ fontSize: 100 }}>
        {level}
      </Animated.Text>
    </View>
  );
}
```

</details>

https://user-images.githubusercontent.com/20516055/142409582-7b39f5ea-9883-4ed6-bbfa-59010f8f95eb.mov

Using a single `ZoomOut` animation as layout transition (without `combineTransition`) appears to work fine:

```tsx
<Animated.Text layout={ZoomOut.duration(1000)} style={{ fontSize: 100 }}>
  {level}
</Animated.Text>
```

<details>
<summary>Example2.tsx</summary>

```tsx
import Animated, { ZoomOut } from 'react-native-reanimated';

import React from 'react';
import { View } from 'react-native';

export default function Example2() {
  const [level, setLevel] = React.useState(0);

  const handlePress = () => {
    setLevel((level) => level + 1);
  };

  return (
    <View
      style={{ flex: 1, alignItems: 'center', justifyContent: 'center' }}
      onTouchStart={handlePress}>
      <Animated.Text layout={ZoomOut.duration(1000)} style={{ fontSize: 100 }}>
        {level}
      </Animated.Text>
    </View>
  );
}
```

</details>

https://user-images.githubusercontent.com/20516055/142410493-a5678abe-be05-4755-afaa-278e28b3a017.mov

However, please note that the counter updates immediately, without waiting for ZoomOut animation to finish, which is probably not the expected behaviour.

That's because, in general, layout transitions are meant only for animating the layout of a component (i.e. its position and size), if it has been changed as a result of a render.

In the example you have provided, the layout transition triggers because the text "14" has a slightly different width than text "15". If you had used a monospace font instead, the layout transition would not trigger.

From the docs:

> Entry/Exit transition lets you specify different animations for exiting from the current position and different animations for entering the new position **with new dimensions**.

I must admit that the name "Entry/Exit transition" is quite misleading. Intuitively, we rather expect entry/exit transitions to run the exiting animation on the old version of the component and then run the entering animation on the new version of the component. But layout transitions always animate the position and size of the current version of the component (i.e. after the render). Combining exiting and entering animations is just an example use-case which works fine unless you change the contents of the component. So even with `combineTransition` working correctly, you still wouldn't achieve the expected behaviour.

Here's what you can do instead:

```tsx
<Animated.Text
  exiting={ZoomOut.duration(1000)}
  entering={level > 0 && ZoomIn.delay(1000).duration(1000)}
  key={level}>
  {level}
</Animated.Text>
```

<details>
<summary>Example3.tsx</summary>

```tsx
import Animated, { ZoomIn, ZoomOut } from 'react-native-reanimated';

import React from 'react';
import { View } from 'react-native';

export default function Example3() {
  const [level, setLevel] = React.useState(0);

  const handlePress = () => {
    setLevel((level) => level + 1);
  };

  return (
    <View
      style={{ flex: 1, alignItems: 'center', justifyContent: 'center' }}
      onTouchStart={handlePress}>
      <Animated.Text
        exiting={ZoomOut.duration(1000)}
        entering={level > 0 && ZoomIn.delay(1000).duration(1000)}
        key={level}
        style={{ fontSize: 100 }}>
        {level}
      </Animated.Text>
    </View>
  );
}
```

</details>

https://user-images.githubusercontent.com/20516055/142419071-895d3c98-c50b-4e93-8d8f-09201ef54cc9.mov

The magic part here is the use of `key` property. That's because we need to differentiate the old and the new version of the text component, so React knows that not only the children have changed, but the props too. As a result, the old version is unmounted, which triggers the exiting animation, and simultaneously the new version gets mounted, so the entering animation starts as well. Finally, we can delay the latter so it waits until the exiting animation finishes. We also ignore the entering animation for level 0 (alternatively, we could only skip the one second delay).

Now let's wrap the text component with a view and add a background color:

```tsx
<View style={{ backgroundColor: 'lime' }}>
  <Animated.Text
    entering={level > 0 && ZoomIn.delay(1000).duration(1000)}
    exiting={ZoomOut.duration(1000)}
    key={level}
    style={{ fontSize: 100 }}>
    {level}
  </Animated.Text>
</View>
```

<details>
<summary>Example4.tsx</summary>

```tsx
import Animated, {
  LinearTransition,
  ZoomIn,
  ZoomOut,
} from 'react-native-reanimated';

import React from 'react';
import { View } from 'react-native';

export default function Example4() {
  const [level, setLevel] = React.useState(0);

  const handlePress = () => {
    setLevel((level) => level + 1);
  };

  return (
    <View
      style={{ flex: 1, alignItems: 'center', justifyContent: 'center' }}
      onTouchStart={handlePress}>
      <View style={{ backgroundColor: 'lime' }}>
        <Animated.Text
          entering={level > 0 && ZoomIn.delay(1000).duration(1000)}
          exiting={ZoomOut.duration(1000)}
          key={level}
          style={{ fontSize: 100 }}>
          {level}
        </Animated.Text>
      </View>
    </View>
  );
}
```

</details>

https://user-images.githubusercontent.com/20516055/142421573-88868433-32ef-4752-a21f-c6b7fe69cf76.mov

As you can see, the width of `<View>` component changes immediately each time we increment the counter. Fortunately, we can use layout transitions to smoothly animate the change of the size.

```tsx
<Animated.View
  layout={LinearTransition.duration(2000)}
  style={{ backgroundColor: 'lime' }}>
  <Animated.Text
    entering={level > 0 && ZoomIn.delay(1000).duration(1000)}
    exiting={ZoomOut.duration(1000)}
    key={level}
    style={{ fontSize: 100 }}>
    {level}
  </Animated.Text>
</Animated.View>
```

<details>
<summary>Example5.tsx</summary>

```tsx
import Animated, {
  LinearTransition,
  ZoomIn,
  ZoomOut,
} from 'react-native-reanimated';

import React from 'react';
import { View } from 'react-native';

export default function Example5() {
  const [level, setLevel] = React.useState(0);

  const handlePress = () => {
    setLevel((level) => level + 1);
  };

  return (
    <View
      style={{ flex: 1, alignItems: 'center', justifyContent: 'center' }}
      onTouchStart={handlePress}>
      <Animated.View
        layout={LinearTransition.duration(2000)}
        style={{ backgroundColor: 'lime' }}>
        <Animated.Text
          entering={level > 0 && ZoomIn.delay(1000).duration(1000)}
          exiting={ZoomOut.duration(1000)}
          key={level}
          style={{ fontSize: 100 }}>
          {level}
        </Animated.Text>
      </Animated.View>
    </View>
  );
}
```

</details>

https://user-images.githubusercontent.com/20516055/142422330-34d2248b-8284-4eb9-8006-b2f0e66a1cf1.mov

The only issue we encounter now is that if we increment the counter faster then the duration of the animation, the exiting animation starts from the target position of the component instead of the current position during entering animation:

https://user-images.githubusercontent.com/20516055/142424950-e91de7cc-7bae-4dd8-a4b9-523bce3c3e02.mov

That's because the exiting animation starts before the entering animation finishes. In the future, we may define what is the desirable behaviour in such case and modify the implementation accordingly.

I really hope this helps 😄

**Comment by hannojg** [comment]
@tomekzaw I somewhat missed your awesome response on that. Thx for taking the time to explain it in that much detail (don't want to spam you guys, sorry, just wanted to leave a big thank you <3)
