### ISSUE TITLE
When shared value alternates between two values, it is either not interruptible or cancellable

### ISSUE THREAD

**Issue by andrekovac** [software-mansion/react-native-reanimated#2733]
## Description

If the shared value alternatives between two values on button click, when adding `withSpring` or `withTiming` to the button handler function as described in the [official shared value docs](https://docs.swmansion.com/react-native-reanimated/docs/fundamentals/shared-values/) the animation is not interruptible more than once

Moving `withSpring` into the `useAnimatedStyle` hook solves the issue with the interruptions. But then it's not cancellable (via `cancelAnimation`) anymore.

### Expected behavior

Animation should be cancellable with `cancelAnimation` and also interruptible via starting new animations more than just once.

### Actual behavior & steps to reproduce

When pressing on the button to start animation again quickly, it only works for the first button press.

Steps to reproduce:

1. Use code from [this expo snack](https://snack.expo.dev/@andrusch/reanimated2---toggling-between-two-values-issue)
2. Start animation by hitting button
3. Hit button again while animation is still running several times
4. You will see that the first interruption works, but subsequent interruptions don't.
5. Move `withSpring` to line 7, i.e. `transform: [{ translateX: withSpring(offset.value * 255) }],`
6. Interrupting several times now works.
7. Add new button with `cancelAnimation` call for animation value
8. Canceling the animation doesn't work now.

## Snack or minimal code example

Use code from [this expo snack](https://snack.expo.dev/@andrusch/reanimated2---toggling-between-two-values-issue)

```js
import Animated, { withSpring, useAnimatedStyle, useSharedValue } from 'react-native-reanimated';

function Box() {
  const offset = useSharedValue(0);

  const animatedStyles = useAnimatedStyle(() => {
    return {
      transform: [{ translateX: offset.value }],
    };
  });

  return (
    <>
      <Animated.View style={[styles.box, animatedStyles]} />
      <Button
        onPress={() => {
          offset.value = withSpring(offset.value === 0 ? 200 : 0);
        }}
        title="Move"
      />
    </>
  );
}
```

## Package versions

- React Native: 0.66.3
- React Native Reanimated: 2.3.0
- NodeJS: v12.22.7
- Xcode: 12.5.1

## Affected platforms

Tested on iOS, but seems like a general issue to me.

- [ ] Android
- [x] iOS
- [ ] Web

-> The spring animation does not work at all on Web (as tested with the Expo Snack)

**Comment by scarlac** [comment]
This still seems to be an issue, making `withRepeat` much less useful because it can't effectively be paused/restarted. This means animations will keep running on hidden screens with a deeply nested navigation, wasting resources.

However, there is a workaround if you control the loop yourself:
```typescript
const rotationAnimation = useSharedValue(0);
const rotationAnimationStyle = useAnimatedStyle(() => ({
  transform: [{ rotate: `${rotationAnimation.value}deg` }],
}), []); 
useEffect(() => {
  if (!isFocused) {
    return;
  }

  let animTimer: ReturnType<typeof setTimeout>;
  function runLoop() {
    rotationAnimation.value = withTiming(rotationAnimation.value + 360, {
      duration: 1000,
      easing:   Easing.linear,
    });
    animTimer = setTimeout(runLoop, 1000);
  }
  runLoop();
  return () => {
    clearInterval(animTimer);
  };
}, [isFocused, rotationAnimation]);
```

In my tests, this gets around the issue and allows Fast Reload to function as intended (stopping the animation and fully stopping the loop), at the expense of the animation possibly "pausing" if the JS thread gets too busy every 1 second.

**Comment by amadeus** [comment]
I think this issue is related to a use case that I really need, but doesn't look like it's supported with Reanimated. Essentially I want to use a spring to chase the coordinates of a gesture I am performing, but the problem is when I apply a new updated spring value, I either have to supply a new velocity (which will be out of date from the existing computed velocity of the spring) or if I supply one, it will change the physics of the existing velocity and also appear jank.

Ideally with a spring, all you should need to do is update the `toValue` and just have it continue along its merry way. Is there some other way to do this that I am not aware of?

**Comment by m-bert** [comment]
Hi @andrekovac! You shouldn't use shared value to hold both animation and value of offset. You can use `ref` to choose which value should be passed into `withSpring`, like this:

```jsx
  const offset = useSharedValue(0);
  const ref = useRef(false);

...

      <Button
        onPress={() => {
          ref.current = !ref.current;
          offset.value = withSpring(ref.current ? 200 : 0);
        }}
        title="Toggle"
      />
```

This way you should be able to interrupt and cancel animation.
