### ISSUE TITLE
Entering / exiting animation stopped working in ParticipantList

### ISSUE THREAD

**Issue by likern** [software-mansion/react-native-reanimated#2744]
## Description

After **adding multiple elements** to `<ParticipantList />` component, `entering` and `exiting` **animations stopped working**.

### Expected behavior

`Entering` and `exiting` animations should be working

### Actual behavior & steps to reproduce

1. Run **Participant List** example from `react-native-reanimated`
2. Add multiple elements
3. See `entering` and `exiting` animations stopped working

## Package versions

- React Native: 0.67.0-rc.4
- React Native Reanimated: `main` branch
- NodeJS: 16.10.0
- Xcode: - 
- Java & Gradle: OpenJDK Runtime Environment Corretto-11.0.8.10.1

## Affected platforms

- [x] Android (tested)
- [ ] iOS (not tested)
- [ ] Web (not tested)

## Video
https://drive.google.com/file/d/1X00AVbm5c__vK0FG21cN-qB6fy366cyu/view?usp=sharing

**Comment by piaskowyk** [comment]
This is a performance issue related to not only with reanimated. Every component has its own animation of entering and layout, so the app was a freezer because you tried to run more than a hundred animations at the same time, and also React needed to compute your own operation like layout and mounting.
