### ISSUE TITLE
ScrollView onScroll/onLayout doesn't report values until scroll view is touched

### ISSUE THREAD

**Issue by radex** [software-mansion/react-native-reanimated#284]
I'm not 100% sure if this is a `reanimated` issue, an underlying React Ntaive issue, or something I'm doing wrong.

I'm attaching an event handler like this:

```

  const scrollHeight = new Value(-1)
  const contentHeight = new Value(-1)
// ...
onScrollEvent: event([
      {
        nativeEvent: {
          contentOffset: { y: scrollPosition },
          layoutMeasurement: { height: scrollHeight },
          contentSize: { height: contentHeight },
        },
      },
    ]),
```

to a ScrollView:

```js
<NativeViewGestureHandler ref={nativeGestureRef} {...nativeViewGestureHandlerProps}>
      <Animated.ScrollView
        // onScroll={onScroll}
        onLayout={onScroll}>
            ...
      </Animated.ScrollView>
    </NativeViewGestureHandler>
```

Both `scrollHeight` and `contentHeight` are reported to be `-1` (i.e. scroll view did not emit a new value) until I start scrolling. This happens regardless of whether I attach the event to `onScroll` or to `onLayout`.

FYI this happens even if I attach a function:

```
onLayout={({ layoutMeasurement, contentSize }) =>
          console.warn(layoutMeasurement, contentSize)
        }
```

**Comment by kmagiera** [comment]
Hey @radex ! As for `onLayout` events they are currently not supported by reanimated nor animated native events. This is due to the fact they are special case on the react native core side and does not follow the regular flow for the events. This is something we can potentially address but would require changes in RN core.

As for the `onScroll` event handler it is expected that it only gets triggered when you start scrolling. So the values remain not updated until that happens.

Hope this is helpful and sorry it does not resolve the issue for you. I'd be open to discussing onLayout support but would prefer to create a separate issue for that. Thanks!
