### ISSUE TITLE
Question: How do I do a loop operation inside block ?

### ISSUE THREAD

**Issue by yuanfux** [software-mansion/react-native-reanimated#289]
i.e. I defined a static array in the constructor and tried to update a value based on this array.
```js
constructor(props) {
  super(props);
  this.someArray = [0, 1, 2, 3, 4];
  this.value = block([
   // loop through 'someArray' and update the 'value'
  ]);
}
```
Any idea ?

**Comment by dsznajder** [comment]
@yuanfux #162 Could help you :)

**Comment by brmenchl** [comment]
do you want this value to only be updated once or every time the block is re-evaluated?

**Comment by yuanfux** [comment]
> do you want this value to only be updated once or every time the block is re-evaluated?

every time the block is re-evaluated

**Comment by brmenchl** [comment]
your `someArray` can't change if it's all just primitives, if you want the values in that array to change, you'll have to have them as Animated.Values. Otherwise, if you use a loop function you can generate multiple animated nodes from the array. e.g.
```javascript
constructor(props) {
  super(props);
  this.someArray = [0, 1, 2, 3, 4];
  this.value = block([
   ...this.someArray.map(element => 
    block([/* do something with an element */])
  )
  ]);
}
```

There are no array-like structures in reanimated, so you'll have to do it all on the js side

**Comment by jakub-gonet** [comment]
Thanks @brmenchl for helpful answer to @yuanfux question 🎉 

I'm closing it, but if you need further assistance I'm glad to help.
