### ISSUE TITLE
Using Reanimated 2 with MobX

### ISSUE THREAD

**Issue by Bayramito** [software-mansion/react-native-reanimated#3019]
Hello 

I wonder is there a possibility for using RN2 with MobX stores?

I mean holding sharedValues on the store. To be able to access them from multiple components at the same time

**Comment by artemis-prime** [comment]
I've been using `mobx` w RNR 3 successfully.  After encountering a few issues I've come up with the following appraoch:

Do not try to 'mix' mobx and SharedValue's by doing things like holding the SV in the store etc.  Use mobx for what it's intended: to react to general state changes in the domain, either by triggering other domain logic, or rerendering `React` components.  Use` SharedValue`'s for what they're intended: to run animations and calculate values in `worklets` that support them.  

I'm sure you've noticed that you can't let `mobx` values get dereferenced in `worklet`s.  It will cause an exception since the `worklet` code will correctly recognize a `mobx` pbservable as proxied and refuse to try to copy it for the `worlet`.

## An example 
Say I have an animation that is driven by a `SharedValue` called `animBase`, which goes from 0 to 1 and back. Let's say some of the values in that animation are also effected by whether we're in landscape orientation.  This is handled by a `mobx` `observable` `deviceState.landscape`.  The simplest thing to do is the following:

```
  const animBase = useSharedValue<number>(otherState.someBoolean ? 1 : 0) 
  const landscape = useSharedValue<boolean>(deviceState.landscape)

    // SharedValue is can be accessed from worklet in useAnimatedStyle(),
    // while mobx state cannot.
  useEffect(() => (autorun(() => {
    landscape.value = deviceState.landscape     
  })), [])
```

That way, the `Reanimated` world is happy, since it's only dealing with `SharedValue`'s in its hooks / `worklets`, and it stays nicely synced to the `mobx` state.  

I've found this general approach to be pretty foolproof and my `mobx` and my RNR play very nicely together.

**Comment by piaskowyk** [comment]
Hey 👋 I believe this explanation might be helpful: [[Link to the explanation]](https://github.com/software-mansion/react-native-reanimated/issues/3019#issuecomment-1573707814). We haven't specifically designed the shared value feature to work seamlessly with state holders like MobX. It might work, but we haven't tested it extensively. If you have a specific scenario where you think Reanimated should support this functionality, please share it as an example. We'd greatly appreciate it! :pray:
