### ISSUE TITLE
Android error: package com.swmansion.reanimated does not exist

### ISSUE THREAD

**Issue by ChenDimri** [software-mansion/react-native-reanimated#3032]
## Description

Hi,
I'm installed your library and followed all of the steps in the documentation and I'm getting this error when trying to build on Android:
package com.swmansion.reanimated does not exist

## Package versions

| name                                 | version |
| ------------------------------------ | ------- |
| react-native                         |      0.63.3   |
| react-native-reanimated              |   2.4.1      |
| Gradle                               |   5.6.4      |

## Affected platforms

- [ X ] Android
- [ ] iOS
- [ ] Web

**Comment by ChenDimri** [comment]
I can't add an example because it's our app code, but I just did the regular installing in order to use stream-chat-react-native, which reanimated is one of its dependencies.

**Comment by piaskowyk** [comment]
Unfortunately, we didn't distribute binaries for react-native 0.63 due to package size. I hope that we will soon finish PR with a building Reanimated from the source - It would help. 
If you want you can downgrade your Reanimated version to 2.2 or 2.3, because this version supports react-native in 0.63 version.

**Comment by ChenDimri** [comment]
Worked for me with 2.2.4, thanks! @piaskowyk

**Comment by roots-ai** [comment]
What version to use for `react-native 0.70.3`?
