### ISSUE TITLE
[iOS] Animations don't always run on component initialization

### ISSUE THREAD

**Issue by computerjazz** [software-mansion/react-native-reanimated#3296]
## Description

In reanimated 2.8.0, animations that run on component initialization don't always animate. I can't figure out why they work sometimes and don't work other times. The strangest thing is that adding a `console.log` within `useAnimatedStyle` seems to fix the issue. Wrapping the call that sets the shared value to kick off the initial animation in a `setTimeout` also seems to fix it (most of the time).

This bug does not occur in 2.3.1.

I believe this is the underlying issue behind this `react-native-bottom-sheet` issue: https://github.com/gorhom/react-native-bottom-sheet/issues/925

### Expected behavior
Animations run on component initialization.
(Below is with a `console.log` added in `useAnimatedStyle`):

https://user-images.githubusercontent.com/6730148/173665563-8df0791a-0a05-41de-a828-d9179f013849.MP4

### Actual behavior & steps to reproduce
Create a component that has animations that run on initialization. Show/hide component. Animations run sometimes, but sometimes they just jump to final value (or partially animate).

(Without `console.log` in `useAnimatedStyle`):

https://user-images.githubusercontent.com/6730148/173665704-8c6f93eb-56e3-4cfd-88cd-7f64b1b02252.MP4

## Snack or minimal code example

Run on iOS device to see issue: https://snack.expo.dev/@computerjazz/reanimated-init-bug

## Package versions
2.8.0

| name                                 | version |
| ------------------------------------ | ------- |
| react-native                         |   0.68.2      |
| react-native-reanimated              |     2.8.0    |
| expo                                 |   45      |

## Affected platforms

- [ ] Android
- [x] iOS
- [ ] Web

**Comment by Titozzz** [comment]
My issue is in fact the same as : https://github.com/software-mansion/react-native-reanimated/issues/3209. Maybe related?

**Comment by computerjazz** [comment]
A few clues (and maybe the reason why console.log fixes it): setting `optimalization = 0` here also seems to fix it: https://github.com/software-mansion/react-native-reanimated/blob/main/src/reanimated2/hook/useAnimatedStyle.ts#L481 (or returning `false` here: https://github.com/software-mansion/react-native-reanimated/blob/main/src/reanimated2/hook/utils.ts#L167-L175)

I believe this is also why `console.log` fixes it -- the babel transform gives different values here depending on whether a console.log exists, which drives `optimalization`: https://github.com/software-mansion/react-native-reanimated/blob/main/plugin.js#L745 (`isFunctionCall` becomes `true` when a `console.log` exists)

**Comment by computerjazz** [comment]
Since setting `optimalization = 0` seems to fix it, my gut says that the issues lies somewhere around here:

early return if 0: https://github.com/software-mansion/react-native-reanimated/blob/150e787d1101249122871128be5805c4fe288286/Common/cpp/Tools/Mapper.cpp#L59-L61

else: https://github.com/software-mansion/react-native-reanimated/blob/150e787d1101249122871128be5805c4fe288286/Common/cpp/Tools/Mapper.cpp#L59-L61

maybe some kind of race condition with `jsViewDescriptors` existing? https://github.com/software-mansion/react-native-reanimated/blob/150e787d1101249122871128be5805c4fe288286/Common/cpp/Tools/Mapper.cpp#L62

unfortunately i don't know C++ (yet 😛) so this may be about as far as i can go

**Comment by computerjazz** [comment]
@piaskowyk I think the issue has something to do with the performance optimazations or shared styles here: https://github.com/software-mansion/react-native-reanimated/pull/1470
https://github.com/software-mansion/react-native-reanimated/pull/1879

**Comment by notjosh** [comment]
Can you try it again now that #3374 is merged? It looks like the same behaviour.

**Comment by naftalibeder** [comment]
I can confirm. The explanation @computerjazz gave [here](https://github.com/software-mansion/react-native-reanimated/issues/3296#issuecomment-1172942584) looks correct, because any function call (not just `console.log`) fixes it. Even executing a no-op like

```
const style = useAnimatedStyle(() => {
  (() => {})();

  return {
    ...
  };
});
```

causes the style to update propertly.

I applied the changes [here](https://github.com/software-mansion/react-native-reanimated/pull/3374/commits/032138ae9637dfa309aa15b3b56a03e2b7715020), but it did not fix the problem.

**Comment by b0n1q** [comment]
has anyone found a fix for that?

**Comment by lightrow** [comment]
You can use v1 until they fix v2 in v3

**Comment by b0n1q** [comment]
it worked with versions 2.2.1

**Comment by b0n1q** [comment]
@computerjazz Hello! did you find any solution to solve it? :)

**Comment by lightrow** [comment]
I mean you can use v1 API with the latest version of reanimated, it doesn't have this bug, at least i haven't been able to reproduce it once i rewrote the affected component with V1 API.

**Comment by b0n1q** [comment]
I still don’t understand what v1 api means

**Comment by lightrow** [comment]
https://docs.swmansion.com/react-native-reanimated/docs/1.x.x/declarative

**Comment by b0n1q** [comment]
thanks, but how can we use v1 API with the latest version of reanimated, if v1 API = 1.x.x version of reanimated or I missed smth

**Comment by b0n1q** [comment]
got it! 
but I use moti and moti uses reanimated under the hood

**Comment by lightrow** [comment]
well, not sure why you'd need to use another abstraction when reanimated itself is already very straightforward to use

**Comment by b0n1q** [comment]
make the process even easier :)
it’s weird that a few people have this bug although reanimated used by a lot

**Comment by lightrow** [comment]
maybe not that many people try to animate height/width of components

**Comment by b0n1q** [comment]
> https://docs.swmansion.com/react-native-reanimated/docs/1.x.x/declarative
> 
> the same API is still available in 2.x, except `Easing` functions for v1 are now exported as `EasingNode`

I don’t use Easing, so it doesn’t help me

**Comment by freeboub** [comment]
Short update to notice that this issue can be reproduced on 2.11.0 and also affects android device (I use android tv, but should not impact behavior). workaround here: https://github.com/software-mansion/react-native-reanimated/issues/3296#issuecomment-1211069576 also fix the issue.

**Comment by sadia-onyxtec** [comment]
I am facing the same issue.

**Comment by lightrow** [comment]
simplest reproduction case
```
const Collapsible = () => {
    const childrenHeight = useSharedValue(0);

    const animStyle = useAnimatedStyle(() => {
        return {
            height: childrenHeight.value,
        };
    }, []);

    useEffect(() => {
        childrenHeight.value = 500;
    }, []);

    return (
        <Animated.View style={animStyle}>
            <View style={{ position: 'absolute', height: 500, width: 500, backgroundColor: 'red' }} />
        </Animated.View>
    );
};
```

**Comment by vancerbtw** [comment]
Any update on this? I am suffering from the same issue with a fade in animation that is triggered on component mount in useEffect. console.logging the shared value is my only current work around

**Comment by davoam** [comment]
This still happens in reanimated version `3.1.0`

**Comment by vancerbtw** [comment]
I had this crash happen when changing the content size of a scroll view when it was being animated and the content size changing affecting the current viewport. I solved this by delaying my content change until the scroll animation was completed. still not ideal :(

**Comment by Parveshdhull** [comment]
# Weird workaround
## Observation:
Problems are with sudden changes during initialization.
For example, in @lightrow's [example](https://github.com/software-mansion/react-native-reanimated/issues/3296#issuecomment-1433351242), he is changing `childrenHeight` from 0 to 500 instantly.
- He could have directly initialize the shared value to 500, because in `use effect` it also just changes to 500(without any animation, so the same effect).
- And animations also work, like `withTiming(500)`;
## Solution
### Not so good
`childrenHeight.value
 = with sequence(withTiming(0, {duration: 0}), withTiming(500, {duration: 0}))`

This solution works for me, as it also has 0 total duration, and somehow using sequence fixes issue.

**Problem:** This works great when you are creating/rendering view, but if view is already there like on hot reload, screen will flicker. Because we are hiding view and again showing
### Better solution
`childrenHeight.value
 = with sequence(withTiming(499, {duration: 0}), withTiming(500, {duration: 0}))`

**Comment by ngokevin** [comment]
I ran into this issue on certain Android phones. It's really a race condition that manifests reliably on some phones. In my case, it was with Moti, but I'll see if I can reproduce with Reanimated API as well:

```js
const anim = useDynamicAnimation(() => ({ opacity: 0 });

useEffect(function () {
  anim.animateTo({ opacity: 1});
}, []);

return anim;
```

It did help to add delays, or only run the initial onMount animation after a view's onLayout, but it still manifested. Just wanted to comment it wasn't an iOS-only issue for me

**Comment by henrymoulton** [comment]
@piaskowyk any ideas on what we can do to give a better repro given it's a race condition?

**Comment by AlexSapoznikov** [comment]
Has anyone figured out a workaround for it so far?

**Comment by piaskowyk** [comment]
I know that this is an old issue, but could someone confirm whether this problem still exists in the latest version of Reanimated or if it has been resolved?

**Comment by josumonk** [comment]
"react-native-reanimated": "^3.14.0",
Issue still exists

**Comment by sarthakpranesh** [comment]
I have been facing the same or rather a similar issue on a production application. I have noticed this issue to be rather notorious. It occurs more often on animation that run right after app launch when JS thread is completely blocked due to background tasks. I have also noticed this to occur more often in iOS devices then android.

In my use case I have two separate `useAnimatedStyle` hooks that use the same shared value, these hooks use interpolate functions to animate opacity in a way that both are mutually excluded. So, if one is visible another one should not be, like not even chance it should be. But in some out off this world scenario they both get rendered at once, and even a small micro interaction jerks the UI and fixes this anomaly.

I am on version "2.17.0", and upgrading would be very painful for my team and as per @josumonk it seems its still not fixed. Would love to help debug this further and looking for guidance if their is a fix or workaround already present (already tried everything on this thread).

**Comment by teojiesern** [comment]
I am also experiencing this under cases where JS thread is heavily used, using [Keyframes](https://docs.swmansion.com/react-native-reanimated/docs/layout-animations/keyframe-animations/) seems to fix it for me

Reanimated version: 3.16.7

```
const entering = new Keyframe({
    '0': {
        transform: [{ scale: 0 }],
    },
    '100': {
        transform: [{ scale: 1 }],
    },
}).duration(SnackbarConstants.ANIMATION_DURATION * 2);

return <Animated.Text entering={entering}>{children}</Animated.Text>
```
