### ISSUE TITLE
Building failed on 0.69 for iOS

### ISSUE THREAD

**Issue by skurgansky-sugarcrm** [software-mansion/react-native-reanimated#3316]
## Description
dependencies:
    "react-native": "0.69.0",
    "react-native-reanimated": "^3.0.0-rc.0",

Podfile:
  use_react_native!(
      :path => config[:reactNativePath],
      # to enable hermes on iOS, change `false` to `true` and then install pods
      :hermes_enabled => true,
      :fabric_enabled => true,

<img width="717" alt="image" src="https://user-images.githubusercontent.com/14196384/175520424-abafe2d4-fc39-499b-ab12-2fc38258ace1.png">
'react/config/ReactNativeConfig.h' file not found in Scheduler

### Expected behavior
build is completed 

### Actual behavior & steps to reproduce
Build failed

## Snack or minimal code example
sample RN 0.69 project with react-native-reanimated installed as it's described in docs

**Comment by graszka22** [comment]
Make sure to setup your project with Fabric according to RN documentation: https://reactnative.dev/docs/new-architecture-app-renderer-ios
Especially try to run `USE_FABRIC=1 RCT_NEW_ARCH_ENABLED=1 pod install` in `ios` directory. I had the same error and that worked for me.
Let us know if that worked.

**Comment by kesha-antonov** [comment]
0.69.1 is out https://github.com/facebook/react-native/releases

**Comment by tomekzaw** [comment]
Hello @skurgansky-sugarcrm, did you manage to resolve the problem according to https://github.com/software-mansion/react-native-reanimated/issues/3316#issuecomment-1169065858?

For more details on using Reanimated with Fabric enabled, see https://github.com/software-mansion/react-native-reanimated/issues/2991#issuecomment-1197886823.

**Comment by skurgansky-sugarcrm** [comment]
@tomekzaw  
```
USE_FABRIC=1 RCT_NEW_ARCH_ENABLED=1 bundle exec pod install
```
worked for me, but i don't understand why do i have to pass this params when i have them explicitly set in Podfile ? And i couldn't find the explanation in docs

**Comment by tomekzaw** [comment]
Thanks for response.

> worked for me, but i don't understand why do i have to pass this params when i have them explicitly set in Podfile ? And i couldn't find the explanation in docs

Can you please share with us how exactly you set these params explicitly in Podfile?

**Comment by skurgansky-sugarcrm** [comment]
```
target 'myApp' do
  config = use_native_modules!
  **fabric_enabled = true**
  # Hermes is now enabled by default.
  # The following line will only disable Hermes if the USE_HERMES envvar is SET to a value other than 1 (e.g. USE_HERMES=0).
  **hermes_enabled = true** || !ENV.has_key?('USE_HERMES') || ENV['USE_HERMES'] == '1'

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :production => production,
    **fabric_enabled: fabric_enabled,
    hermes_enabled: hermes_enabled,**
```

isn't it how RN docs say to do it?

**Comment by tomekzaw** [comment]
@skurgansky-sugarcrm According to [Enabling Fabric on iOS](https://reactnative.dev/docs/new-architecture-app-renderer-ios) section in the docs, indeed you need to enable `:fabric_enabled` prop in `use_react_native!` call to enable new renderer on iOS.

However, the value is read directly from `ENV['USE_FABRIC']` and the recommended way of enabling Fabric is with by passing environmental variables: `USE_FABRIC=1 RCT_NEW_ARCH_ENABLED=1 pod install`.

The thing is that all third-party libraries need to detect whether Fabric is enabled or not. Currently, we do this by checking the environmental variable:
https://github.com/software-mansion/react-native-reanimated/blob/a6bcde36a16b44ab6c6731041132ceea57ee5783/RNReanimated.podspec#L48

So in our example app, instead of setting `:fabric_enabled` prop, we set the environmental variable:
https://github.com/software-mansion/react-native-reanimated/blob/a6bcde36a16b44ab6c6731041132ceea57ee5783/FabricExample/ios/Podfile#L4

**Comment by skurgansky-sugarcrm** [comment]
@tomekzaw  
but weren't env variables USE_FABRIC and RCT_NEW_ARCH_ENABLED recommended for RN below 0.68 to test new architecture ? Now RN works with new architecture when these props set in Podfile, while a bunch of 3rd party libs are still using env variables to work correctly ?

**Comment by fsl-karimullah** [comment]
Your Ruby version is 2.6.10, but your Gemfile specified 2.7.5 i got this error when run that command
