### ISSUE TITLE
I have this issue when run react-native run-android - "error: index.js: Cannot find module 'react-native-reanimated/plugin'"

### ISSUE THREAD

**Issue by Rananjaya** [software-mansion/react-native-reanimated#3361]
I have this issue when run react-native run-android - "error: index.js: Cannot find module 'react-native-reanimated/plugin'"

**Comment by piaskowyk** [comment]
Hey, could you provide a repo to reproduce your issue?

**Comment by JarodStreck** [comment]
Same issue with 2.5.0 and after adding plugins:['react-native-reanimated/plugin'] in the babel.config.js

**Comment by Rananjaya** [comment]
I have fix this issue with comment plugins: ['react-native-reanimated/plugin']
module.exports = function(api) {
  api.cache(true);
  return {
    presets: ['babel-preset-expo'],
    // plugins: ['react-native-reanimated/plugin'],
  };
};

**Comment by tomekzaw** [comment]
@Rananjaya! I'm afraid that commenting out this line doesn't resolve the issue because Reanimated Babel plugin is necessary for Reanimated to work properly. 😢 

@JarodStreck Can you please verify if file `node_modules/react-native-reanimated/plugin.js` exists? Do you have `react-native-reanimated` listed in your app's `package.json`? Did you remember to install the dependencies with `yarn install` (or `npm i`)? 🤔
