### ISSUE TITLE
useAnimatedProps sets all native prop values even when only one value has changed

### ISSUE THREAD

**Issue by mrbrentkelly** [software-mansion/react-native-reanimated#3390]
## Description

I've upgraded from Reanimated 2.2.4 to 2.9.1 and am experiencing a difference in behavior for the `useAnimatedProps` hook... In 2.2.4 when you update a shared value used in `animatedProps`, only that native prop would get updated, however in 2.9.1 (actually since 2.3.0) when you update a shared value used in `animatedProps` then every native prop listed in the animated props object gets updated.

This is problematic for native components that have native props which you only want to update when its corresponding shared value changes. For example, we have a custom Native Video Component that we control various things using reanimated `animatedProps` such as isPlaying, and seeking. For example...

```jsx
const isPlaying = useSharedValue(true);
const seekTo = useSharedValue(0);

const animatedProps = useAnimatedProps(() => ({
  isPlaying: isPlaying.value,
  seekTo: seekTo.value,
}));

<VideoPlayer source={someSource} animatedProps={animatedProps} />
```

In Reanimated 2.2.4 we could set the value of `isPlaying` to `false` without impacting the current playhead position. But after updating to 2.9.1, when you set `isPlaying.value = false`, then the video will also seek to the current value of the `seekTo` shared value (even though its shared value 'seekTo' hasn't changed).

### Expected behavior

See above

### Actual behavior & steps to reproduce

See above

## Snack or minimal code example

See above

## Package versions

| name                                 | version |
| ------------------------------------ | ------- |
| react-native                         |       0.67.4  |
| react-native-reanimated              |    2.9.1     |
| NodeJS                               |    16.4.2     |
| Xcode                                |    13.4.1     |
| Java                                 |   11.0.11      |
| Gradle                               |    7.2     |

## Affected platforms

- [x] Android
- [x] iOS
- [ ] Web

**Comment by tomekzaw** [comment]
Hello @mrbrentkelly! Thanks for reporting this issue.

Indeed, there is a difference in handling animated props between Reanimated 2.2.4 and 2.3.0. Previously, all animated props were differentiated by Reanimated and only those who have changed were applied onto the native views. However, this involved a performance and memory overhead, so we decided to optimize this by applying animated props directly onto native views without diffing.

In most of the cases, this change doesn't alter the behaviour of animated components in any way, because such animated props are updated only from Reanimated and are never changed from the native side. In this specific case of video player, the problem comes from the fact that `seekTo.value` is not synchronized with the current timestamp from the player. When you update `isPlaying.value`, the worklet inside `useAnimatedProps` returns a JS object with two animated props and thus `seekTo` prop is updated with outdated shared value.

I'm wondering if this issue can be resolved by implementing the diffing inside `useAnimatedProps` like so:
```js
const animatedProps = useAnimatedProps(() => {
  if (/* only isPlaying changed */) {
    return { isPlaying: isPlaying.value };
  } else if (/* only seekTo changed */) {
    return { seekTo: seekTo.value };
  } else {
    return {
      isPlaying: isPlaying.value,
      seekTo: seekTo.value,
    };
  }
});
```
Please let us know if this approach works for you.

**Comment by mrbrentkelly** [comment]
Hey @tomekzaw, thanks so much for that detailed explanation. It's good to know this behavior change was intentional and it's not a bug after all.

Thanks for your suggestion 🙏. I know it will work as we've already implemented something similar to workaround this behavior change. 

Thanks again!

**Comment by mrbrentkelly** [comment]
Closing as this is the expected behavior for `animatedProps` as of v2.3.0.
