### ISSUE TITLE
Deleting last items from ScrollView with layout transitions causes jumps

### ISSUE THREAD

**Issue by Tauka** [software-mansion/react-native-reanimated#3412]
## Description

I use `ScrollView` with `Animated.View` children, and layout transitions work mostly fine. Except when I remove last items, scroll view immediately shrinks, creating jumps.

### Expected behavior
Animate smoothly `ScrollView` just as I would delete from top. When scrolled to the bottom, they should shift to bottom (like in Notes app in iOS), rather than items shifting to top

### Actual behavior & steps to reproduce
Deleting from last rows causes jumps, whereas deleting from top is smooth. Add enough items to scroll appear, scroll to bottom and delete last items

https://user-images.githubusercontent.com/15087247/181166416-e82d5ff0-72ce-4c49-a8b3-53315c6fa011.MP4

## Snack or minimal code example

Issue appears in the example from official docs:
https://snack.expo.dev/UHTx6Ye5e

## Package versions

| name                                 | version |
| ------------------------------------ | ------- |
| react-native                         |  0.64.3        |
| react-native-reanimated              | 2.8.0        |
| expo                                 | 45.0.0        |

Issue also appears on latest version (2.9.1), checked in my projecy, but Snack does not support latest version.

## Affected platforms

- [x] Android
- [x] iOS
- [ ] Web

**Comment by tomekzaw** [comment]
Hello @Tauka! Thanks for reporting this issue as well as for the detailed description. While it certainly doesn't look right, I'm afraid that this is actually the expected behaviour of Layout Animations.

Here's how Layout Animations work in Reanimated: when the position or size (i.e. layout) of some component changes, we animate its `x`, `y`, `width` and `height` props from the previous layout to the new layout.

When you remove the 1st, 2nd, 3rd etc. element from `ScrollView`, the layout (in particular, y-coordinate) of all next items changes, so the appropriate layout animations are launched.

When the ScrollView is scrolled all the way to the bottom and you remove the last item, the position of all the previous items (within ScrollView) doesn't change, thus no layout animation will be triggered. The observed jump happens because of the fact that once the item is deleted, the contents of ScrollView changes its height, and thus the scroll offset is automatically adjusted by the system.

In such case, the best solution would be to animate ScrollView's offset (in general, this can be done in Reanimated using [`scrollTo`](https://docs.swmansion.com/react-native-reanimated/docs/next/api/nativeMethods/scrollTo/)), but I'm not sure if the offset can be greater then the height of the contents minus the height of the ScrollView itself. I'm wondering if this can be fixed by converting the ScrollView to `Animated.ScrollView and animating its bottom padding accordingly (only when the last item is removed), from the height of the last item down to zero, accordingly.

**Comment by Tauka** [comment]
Hello @tomekzaw. Thank you, I really appreciate your response. I will try to play with ScrollView offset and padding as you suggested, and I'm sure I can make it work that way. Sorry for false bug report, closing issue

**Comment by Tauka** [comment]
If anyone faces same problem as me, this is how I solved it:
https://snack.expo.dev/U7-brio_U

Idea is to increase the padding of `ScrollView` every time we remove item to the height of single item, and I also use `onScroll` (that's why we have to use `Animated.ScrollView`) listener to decrease the padding whenever we scroll up. I had to wrap contents of `Animated.ScrollView` into `Animated.View`, because `contentContainerStyle` doesn't work with animated styles
