### ISSUE TITLE
We use RN version "0.64.2" and REA version "^2.8.0"

### ISSUE THREAD

**Issue by guiziii** [software-mansion/react-native-reanimated#3413]
We use RN version "0.64.2" and REA version "^2.8.0"
If I use the old node modules I see this structure in re-animated > 
<img width="384" alt="image" src="https://user-images.githubusercontent.com/77700933/178890671-2bdc3a13-01d4-4cad-b45d-d7e65c70d948.png">
But If do yarn install even without changing anything in package.json I see the reanimated-64.aar file not available ?
<img width="382" alt="image" src="https://user-images.githubusercontent.com/77700933/178891704-1625f615-3f64-4913-a260-487b23856e21.png">

I'm able to work if I use the old node modules and that's possible until I change the package.json. 
Should I spend my time upgrading the RN version (which is a pain as unimodules are involved) or what else can be done here ?

_Originally posted by @ratz6 in https://github.com/software-mansion/react-native-reanimated/issues/3161#issuecomment-1183943006_

**Comment by tomekzaw** [comment]
Hello @guiziii! In order to keep the package size as small as possible, Reanimated 2.x contains prebuilt AARs only for 5 most recent minor versions of React Native. That's why with the release of Reanimated 2.8.0 we no longer provide the AARs for 0.64.x.

If Reanimated cannot detect the AAR for appropriate react-native version, it tries to built itself directly from sources. Do you have Android NDK installed and set up?

Also, If you don't use Reanimated 1 API, you can upgrade to Reanimated v3 which is always built from sources on Android (this matches the behaviour on iOS).

**Comment by ivangonzalezg** [comment]
> Hello @guiziii! In order to keep the package size as small as possible, Reanimated 2.x contains prebuilt AARs only for 5 most recent minor versions of React Native. That's why with the release of Reanimated 2.8.0 we no longer provide the AARs for 0.64.x.
> 
> If Reanimated cannot detect the AAR for appropriate react-native version, it tries to built itself directly from sources. Do you have Android NDK installed and set up?
> 
> Also, If you don't use Reanimated 1 API, you can upgrade to Reanimated v3 which is always built from sources on Android (this matches the behaviour on iOS).

I just followed these steps https://developer.android.com/studio/projects/install-ndk#default-version and it worked
