### ISSUE TITLE
`withSpring` does not work as documented

### ISSUE THREAD

**Issue by david-arteaga** [software-mansion/react-native-reanimated#3424]
## Description

The [Driving Animations section of the docs](https://docs.swmansion.com/react-native-reanimated/docs/fundamentals/shared-values#driving-animations) show an example where you can animated a box with the `withSpring`, setting an animated value like this `animatedValue.value = withSpring(Math.random())`, but doing this does not result in the described animation.

https://user-images.githubusercontent.com/7199015/182003943-8a1fede1-a9bc-4f57-8542-d23b7662637d.MP4

The `Move good` and `Move good 2` cases use a different pattern to correctly generate the desired animation:
- `Move good`: `offset.value = withSpring(Math.random() * 255)`
- `Move good 2`: `translateX: withSpring(offset.value * 255)`

### Expected behavior

The animation should work and the box should move like a spring with the code in the [example from the docs](https://docs.swmansion.com/react-native-reanimated/docs/fundamentals/shared-values#driving-animations)

### Actual behavior & steps to reproduce

The box does not animate like a spring.

## Snack or minimal code example

https://snack.expo.dev/@david.arteaga/reanimated-with-spring-error

## Package versions

| name                                 | version |
| ------------------------------------ | ------- |
| react-native                         |     0.68.2    |
| react-native-reanimated              |     2.3.1    |
| NodeJS                               |     16.16.0    |
| Xcode                                |         |
| Java                                 |         |
| Gradle                               |         |
| expo                                 |     44.0.0    |

## Affected platforms

- [ ] Android
- [x] iOS
- [ ] Web

**Comment by tomekzaw** [comment]
Hello @david-arteaga! Thanks for reporting the issue.

Indeed, `offset.value * 255` has different behaviour than `withSpring(Math.random() * 255)`.

The position and velocity for spring animation is computed iteratively, based on the values from the previous frame. The animation finishes when $\Delta x = x_t - x_{t-1} <$ `restDisplacementThreshold` and $\Delta v_x <$ `restSpeedThreshold`.

If you call `withSpring` without passing the config object, i.e.
```ts
offset.value = withSpring(0.5);
```
the following default parameters are actualy used (see [docs](https://docs.swmansion.com/react-native-reanimated/docs/api/animations/withSpring)):
```ts
offset.value = withSpring(0.5, {
  restDisplacementThreshold: 0.01,
  restSpeedThreshold: 2,
});
```

In the provided example, the box does not animate like a spring because the animation stops too early because both stop conditions are actually fulfilled while passing through the rest position. The solution is to decrease the position and velocity thresholds, i.e.: 
```ts
offset.value = withSpring(Math.random(), {
  restDisplacementThreshold: 0.001,
  restSpeedThreshold: 0.01,
});
```
or, alternatively, animate the shared value from 0 to 255 instead of from 0 to 1.

I will submit a PR that fixes the source code of the example in the docs.

**Comment by david-arteaga** [comment]
Got it. That makes sense.

Thanks for laying it out!
