### ISSUE TITLE
Animation styles are not updating in tests. 

### ISSUE THREAD

**Issue by manastunga787** [software-mansion/react-native-reanimated#3495]
### Description

**I was not able to test updated animation style as suggested in documentation [https://docs.swmansion.com/react-native-reanimated/docs/guide/testing/#example](url). Animation style are not updating to new value. in test cases**

**Though the following Code works fine in browser but fails in test**

```
import styled from "styled-components/native";
import { Text } from "react-native";
import Animated, { useAnimatedStyle, useSharedValue, withTiming } from "react-native-reanimated";
import { useState, useRef, useEffect } from "react";

export default function MyButton({ children, onPress, style, textStyle }) {

    // both top and left have initial value of -5
    const ripplePositonSharedValueLeft = useSharedValue(-5);
    const ripplePositonSharedValueTop = useSharedValue(-5);

    const btnRef = useRef();

    let rippleAnimationStyle = useAnimatedStyle(() => {
        return {
            left: ripplePositonSharedValueLeft.value,
            top: ripplePositonSharedValueTop.value,
        }
    })


    const handlePressIn = (e) => {
        ripplePositonSharedValueLeft.value = withTiming(e.nativeEvent.locationX - 5, { duration: 500 });
        ripplePositonSharedValueTop.value = withTiming(e.nativeEvent.locationY - 5, { duration: 500 });
    }


    return (
        <Btn testID="btn" ref={btnRef} onPressIn={handlePressIn} >
            <Text style={textStyle}>{children}</Text>
            <RippleCircle testID="rippleCircle" style={rippleAnimationStyle} />
        </Btn>
    );
}

const Btn = styled.Pressable`
    padding:8px 10px;
    background-color:blue;
    border-radius:5px;
    position:relative;
    justify-content:center;
    align-items:center;
`;

const RippleCircle = styled(Animated.View)`
    background-color:red;
    width:10px;
    height:10px;
    /* padding:5px; */
    border-radius:50%;
    position:absolute;
    `;
```

**In My Test file** 

```
import { render, screen, fireEvent } from "@testing-library/react-native";
import MyButton from "../components/myButton";
import {
    withReanimatedTimer,
    advanceAnimationByTime,
    advanceAnimationByFrame,
    getAnimatedStyle
} from "react-native-reanimated/src/reanimated2/jestUtils";


 test("MyButton RippleCircle must move to the position where clicked. ", () => {
        withReanimatedTimer(() => {
            render(<MyButton>Click</MyButton>);
            let btn = screen.getByTestId("btn");
            let rippleCircle = screen.getByTestId("rippleCircle");
            expect(rippleCircle).toHaveStyle({ left: -5, top: -5 });

            fireEvent(btn, "onPressIn", { nativeEvent: { locationX: 10, locationY: 15 } });

            advanceAnimationByTime(500);
            rippleCircle = screen.getByTestId("rippleCircle");
            expect(rippleCircle).toHaveAnimatedStyle({ left: 5, top: 10 });
        })

    });
```

**Test Fails with following error**

```
Expected: {"left":5,"top":10}
Received: {"backgroundColor":"red","width":10,"height":10,"borderRadius":5,"position":"absolue","left":-5,"top":-5}
```

```
Differences:
    - 'left' should be 5, but is -5
    - 'top' should be 10, but is -5
```

**My Jest-setup.js**

```
global.__reanimatedWorkletInit = () => { }
jest.mock('react-native-reanimated', () => require('react-native-reanimated/mock'))
require('react-native-reanimated/lib/reanimated2/jestUtils').setUpTests();
```

**Package.json**

```
{
  "name": "expo-app",
  "version": "1.0.0",
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web"
  },
  "dependencies": {
    "expo": "~46.0.7",
    "expo-status-bar": "~1.4.0",
    "jest": "^26.6.3",
    "jest-expo": "^46.0.1",
    "react": "18.0.0",
    "react-dom": "18.0.0",
    "react-native": "0.69.4",
    "react-native-reanimated": "~2.9.1",
    "react-native-web": "~0.18.7",
    "styled-components": "^5.3.5"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "@testing-library/jest-native": "^4.0.11",
    "@testing-library/react-native": "^11.0.0",
    "@types/jest": "^28.1.7",
    "@types/styled-components-react-native": "^5.1.3",
    "react-test-renderer": "18"
  },
  "private": true
}
```

**Node v16.15.0**

### Steps to reproduce

npx jest

### Snack or a link to a repository

https://github.com/manastunga787/reanaimated-testing

### Reanimated version

2.9.1

### React Native version

18.0.0

### Platforms

Web

### Workflow

Expo managed workflow

### Architecture

Fabric (New Architecture)

### Acknowledgements

Yes

**Comment by cam-shaw** [comment]
Hmmm I'm getting this issue again after upgrading RN & Jest. @manastunga787 just pinging again to see how you go around it, and whether the "unmock" worked for you?

**Comment by kmagiera** [comment]
Hi @manastunga787 and others. Thank you for reporting this issue. I noticed that the issue is related to reanimated 2. As part of Reanimated 3 we re-did the whole testing integration layer and as a consequence, the tests you submitted now execute correctly on Reanimated 3. 

I verified that your repo tests run correctly after the update. The things I did:
 1) update reanimated version to latest
 2) update jest version to latest (it is important as reanimated integration requires newer version than the one used in your repo)
 3) In reanimated 3 the testing setup is a bit different, so I made necessary changes to account for that, namely:
   - jest-setup.js now only need to have this one line in it: `require('react-native-reanimated').setUpTests();`
   - for advancing timer, you just use the built-in jest method: `jest.advanceTimersByTime(500);`
   - you also don't need to use `withReanimatedTimer` – essentially you test no longer need to import anything from jestUtils

All the changes in setup are documented here: https://docs.swmansion.com/react-native-reanimated/docs/guides/testing/

I also made a gist with the test file for you to take a look, apparently after saving the file got reformatted, so apart from necessary changes there are also some formatting changes: https://gist.github.com/kmagiera/2ddb815895b35010a6d4f50e6594d57b
