### ISSUE TITLE
Why 2.10.0 need to download and build boost, glog, double-conversion, folly when newArchEnabled is set to false

### ISSUE THREAD

**Issue by wood1986** [software-mansion/react-native-reanimated#3523]
### Description

Why 2.10.0 need to download and build boost, glog, double-conversion, folly when newArchEnabled is set to false?

even if newArchEnabled = true, it should use the react-native one

![image](https://user-images.githubusercontent.com/5212215/186963095-a30eda69-6e1d-432b-9849-b7a2f486b624.png)

### Steps to reproduce

1. create a react native app
2. add react-native-reanimated: "^2.10.0" to package
3. yarn android

### Snack or a link to a repository

/

### Reanimated version

2.10.0

### React Native version

0.69.3

### Platforms

Android

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Paper (Old Architecture)

### Build type

Debug mode

### Acknowledgements

Yes

**Comment by SectionTN** [comment]
it's because there's some c/c++ code need to be compiled, they use boost, glog etc...
i've made a workaround for this; [link](https://github.com/mrousavy/react-native-vision-camera/issues/1148#issuecomment-1214998966)

**Comment by billnbell** [comment]
That is not a work around. We need it to use the RN libraries not define new ones.

**Comment by wood1986** [comment]
Here is the main question if newArchEnabled=false, should react-native-reanimated download and build the c++ thing? I expect it should not

**Comment by SectionTN** [comment]
> That is not a work around. We need it to use the RN libraries not define new ones.

you're not defining new ones, you'll put the downloaded libraries inside their folder, when you run your project, you'll found that task UP-TO-DATE so it will not download anything during build.

**Comment by tomekzaw** [comment]
Hey @wood1986, thanks for reporting the issue.

> Here is the main question if newArchEnabled=false, should react-native-reanimated download and build the c++ thing? I expect it should not

Originally, Reanimated 2 is distributed as AAR with pre-compiled binaries for each supported RN version, JS runtime, Android arch etc. In such case, boost, folly, glog and double-conversion should not be downloaded, since the shared library is already shipped within the package. **In other words, Reanimated 2.10 with client-side build disabled doesn't need to download these native dependencies.**

However, since Reanimated 2.5.0 it is also possible to enable client-side build (requires Android NDK). We need certain header files from boost, folly, etc. when compiling Reanimated shared library. In such case, boost, folly, glog and double-conversion should be downloaded. That's because on the old architecture (Paper), react-native itself is also distributed as AAR so these native dependencies are not downloaded, so Reanimated needs to download them.

As a side note: client-side build is also necessary to use Reanimated with V8 engine.

Finally, with the new architecture, React Native is built from sources and so is Reanimated 3.0.0-rc.2. Thus, boost, folly, glog and double-conversion need to downloaded. (We also decided to match this behaviour when using Reanimated 3 with the old architecture as well, so Reanimated 3 is always built from sources.) We are aware of the fact that react-native itself downloads these native dependencies but these tasks are implementation detail so we should not rely on them. However, we will be trying to optimize this in the future.

Here's a table that hopefully summarizes all possible configurations:

| Configuration | Current behaviour | Preferred behaviour |
|-|:-:|:-:|
| Reanimated 2.10, old arch, AAR, JSC/Hermes | ✔️? | ✖️ |  
| Reanimated 2.10, old arch, client-side build, JSC/Hermes/V8 | ✔️ | ✔️ | 
| Reanimated 3.0.0-rc.2, old arch | ✔️ | ✔️ | 
| Reanimated 3.0.0-rc.2, new arch | ✔️ | ✖️ | 

Legend:
* ✔️ - boost, folly, glog and double-conversion should be downloaded
* ✖️ - boost, folly, glog and double-conversion should NOT be downloaded

**Comment by Jumbostan** [comment]
>  In other words, Reanimated 2.10 with client-side build disabled doesn't need to download these native dependencies.

Hi @tomekzaw, how can I disable the client-side build in Reanimated 2.10?

**Comment by nvojnovic** [comment]
It would be nice if we could disable client-side build in 2.10.x

**Comment by tomekzaw** [comment]
> It would be nice if we could disable client-side build in 2.10.x

It should be already disabled by default.

**Comment by nvojnovic** [comment]
> It should be already disabled by default.

Then we are maybe not talking about the same thing. I thought it is connected with need to download these additional libraries. Is there a way to build project without downloading this additional libraries if we are not using new arch.

**Comment by SectionTN** [comment]
> > It should already be disabled by default.
> 
> Then we are maybe not talking about the same thing. I thought it was connected with the need to download these additional libraries. Is there a way to build the project without downloading these additional libraries if we are not using the new arch?

yes, there is, follow this trick: https://github.com/mrousavy/react-native-vision-camera/issues/1148#issuecomment-1239487610

**Comment by nvojnovic** [comment]
> yes, there is, follow this trick: [mrousavy/react-native-vision-camera#1148 (comment)](https://github.com/mrousavy/react-native-vision-camera/issues/1148#issuecomment-1239487610)

That would prevent downloads, but why are the download tasks executed in the first place if we don't need/want to build anything? I'm still not sure what exactly is getting build because react-native-reanimated-70-hermes.aar is provided in package.

**Comment by SectionTN** [comment]
it will prevent download and make the task `UP-TO-DATE`, this will save build time for you until we get a fix.

**Comment by leon-marzahn** [comment]
Any update on this?

**Comment by tomekzaw** [comment]
> Any update on this?

Currently we have a few tasks with higher priority (i.e. 2.10.0 not working in monorepos). Is this issue critical for you?

**Comment by leon-marzahn** [comment]
> > Any update on this?
> 
> Currently we have a few tasks with higher priority (i.e. 2.10.0 not working in monorepos). Is this issue critical for you?

It does take like 4 minutes everytime a dependency is updated. Monorepos are working fine for me, i'm using it in NX.

**Comment by raajnadar** [comment]
> > Any update on this?
> 
> Currently we have a few tasks with higher priority (i.e. 2.10.0 not working in monorepos). Is this issue critical for you?

Yes someone should look into this, as ever-time, we build APK or aab we need to download this which increases build time on both new and old arch, with expo eas local build we don’t even understand why the build is very slow.

I guess a few PRs are raised to address this...
