### ISSUE TITLE
react-native-reanimated:buildCMakeRelWithDebInfo FAILED

### ISSUE THREAD

**Issue by Guilleanto** [software-mansion/react-native-reanimated#3535]
### Description

![image](https://user-images.githubusercontent.com/18471149/187958086-aba8c2c2-e3bb-42c9-a47b-b65e70c53c20.png)

I have a problem when I try to build release

I already tried with ./gradlew clean

### Steps to reproduce

1 npx react-native init AwesomeProject
2 Install react-native-reanimated 2.10.0
3.- Build release with ./gradlew bundleRelease

### Snack or a link to a repository

n/a

### Reanimated version

2.10.0

### React Native version

0.68.2

### Platforms

Android

### Workflow

React Native (without Expo)

### Build type

Release mode

### Acknowledgements

Yes

**Comment by justin-tay** [comment]
This can be because a number of Windows applications cannot deal with paths that exceed MAX_PATH.

You might want to try moving your project directory to the root directory ie. `C:/AwesomeProject` or symlinking your project directory from root ie. using `mklink /D`. You should clean before trying again from the new directory.
