### ISSUE TITLE
zIndex does not work as expected in iOS Simulator

### ISSUE THREAD

**Issue by ayushbgl** [software-mansion/react-native-reanimated#3584]
### Description

I have multiple animated views (in a list) with their `useAnimatedStyle` style hook. The `zIndex` property there works as expected on Android real phone but incorrectly on iOS Simulator.

### Steps to reproduce

1. Create two overlapping `<Animated.View style={[viewStyle]}>` with slight change in x and y values. The one created/rendered after is on top of the other one.
2. Change the `zIndex` value in viewStyle which is calling `useAnimatedStyle` function based upon some logic, button click or a gesture.
3. The updated value of zIndex is reflected on Android real device as the corresponding view moves on the top but not on iOS simulator.

### Snack or a link to a repository

None

### Reanimated version

2.3.1

### React Native version

0.66.4

### Platforms

Android, iOS

### Device

iOS simulator

### Acknowledgements

Yes

**Comment by tomekzaw** [comment]
Hey @ayushbgl, thanks for reporting this issue! Based on your description I've tried to prepare a repro.

Modifying `zIndex` in `useAnimatedStyle` seems to work fine on iOS:

https://user-images.githubusercontent.com/20516055/191018684-c68aba66-79d8-4d92-98a5-673b8c9f28d9.mov

Note that I'm using the latest release of Reanimated which currently is 2.10.0 (or 3.0.0-rc.2).

On Android you need to use `elevation` (so in order to support both platforms effectively you need to set and modify two props, `zIndex` and `elevation`):

https://user-images.githubusercontent.com/20516055/191019725-340983f8-9324-473d-a012-9afa3f0e78b0.mov

Here's the source code:
```tsx
import Animated, {
  useAnimatedStyle,
  useSharedValue,
} from 'react-native-reanimated';
import {Button, StyleSheet, View} from 'react-native';

import React from 'react';

export default function App() {
  const sv = useSharedValue(1);

  const style = useAnimatedStyle(() => ({
    zIndex: sv.value,
    elevation: sv.value,
  }));

  const handlePress = () => {
    sv.value = sv.value === 1 ? 3 : 1;
  };

  return (
    <>
      <Animated.View style={[styles.a, style]} />
      <View style={styles.b} />
      <View style={styles.button}>
        <Button title="Toggle z-index" onPress={handlePress} />
      </View>
    </>
  );
}

const styles = StyleSheet.create({
  a: {
    position: 'absolute',
    top: 200,
    left: 50,
    width: 200,
    height: 200,
    backgroundColor: 'red',
  },
  b: {
    position: 'absolute',
    top: 300,
    left: 150,
    width: 200,
    height: 200,
    backgroundColor: 'blue',
    zIndex: 2,
    elevation: 2,
  },
  button: {
    position: 'absolute',
    top: 100,
    left: 0,
    right: 0,
  },
});
```

Can you upgrade to 2.10.0 (or 3.0.0-rc.2) and let us know if it works for you?

**Comment by ayushbgl** [comment]
Thanks @tomekzaw for your comment. I tried reproducing it and realized that I had my individual components wrapped in a `<View>`. Strangely, the behavior was still acceptable on Android. Closing the issue.
