### ISSUE TITLE
[iOS] 120 fps laggy in debug mode

### ISSUE THREAD

**Issue by dylancom** [software-mansion/react-native-reanimated#3628]
### Description

When testing animations on a real device in `Debug` mode, the animations are very laggy (when using 120 fps).
After changing the scheme to `Release` the animations become butter smooth.
This makes it hard to adjust animations during development and predict how they will run in production.

### Steps to reproduce

1. Add `<key>CADisableMinimumFrameDurationOnPhone</key><true/>` to info.plist.
2. Make sure that the Product > Scheme > Build Configuration is at debug.
3. Run app on a real device that supports 120 fps.
4. Notice that withTiming animations are very laggy.

### Snack or a link to a repository

https://snack.expo.dev/

### Reanimated version

2.10.0

### React Native version

0.64.0

### Platforms

iOS

### Architecture

Paper (Old Architecture)

### Build type

Debug mode

### Device

Real device

### Device model

iPhone 13 Pro

### Acknowledgements

Yes

**Comment by pmtu95** [comment]
I have the same issue. I have implemented drawer navigation on Android, and the animation shows/hides smoothly also, but when I'm in debug mode, the animation is very slow and laggy

**Comment by szydlovsky** [comment]
Hey there is some things that likely cause it. Firstly, debug mode will always be slower and clunkier because of all the measures taken to check the app. Seconly, React Native itself caps the app's performance at 60 fps, because of some hardcoded values that you can see [in this thread](https://github.com/facebook/react-native/issues/29333).
