### ISSUE TITLE
v2.11.0 causing diffs in Podfile.lock depending on if it was built on an ARM or x86 machine

### ISSUE THREAD

**Issue by shamilovtim** [software-mansion/react-native-reanimated#3696]
### Description

We run CI on an x86 macOS container. My personal machine is an M1 Max. After bumping **2.10.0 -> 2.11.0** of reanimated we're getting non deterministic diffs in the Podfile.lock md5 hash depending on if Pods were built on an ARM machine or x86 machine
```diff
-  RNReanimated: 097e693137613d46d013634c9d25a88e7c64da1e
+  RNReanimated: 81bec259b82a8bd2902557e48ef36290be15f389
```

This causes our project to fail building on CI:
<img width="992" alt="Screen Shot 2022-10-19 at 7 53 17 PM" src="https://user-images.githubusercontent.com/3495974/196825754-ade590e8-58ed-4584-8a33-e53df63fcd46.png">

Since the Pod is constructed locally, I assume the problem is in the source code of a podspec change to 2.11.0. And indeed, the Podspec did change: https://github.com/software-mansion/react-native-reanimated/compare/2.10.0...2.11.0#diff-2f3e36d153f0b1ce894c5dd8afad3b4119dd38054d65d7a593f60cf2762edf1a.

### Steps to reproduce

1. `yarn` on an x86 machine
2. `yarn` on an M1 machine

There should be a diff in Podfile.lock

### Snack or a link to a repository

N/A build issue

### Reanimated version

2.11.0

### React Native version

0.68.3

### Platforms

iOS

### JavaScript runtime

JSC

### Workflow

Expo bare workflow

### Architecture

Paper (Old Architecture)

### Build type

Debug mode

### Device

iOS simulator

### Acknowledgements

Yes

**Comment by Waltari10** [comment]
Facing a similar issue with the checksum changing in CI. My local machine is M1 and the build machine is an Intel Mac machine. The node_module/react-native-reanimated seems exactly the same when diffed, but the checksum ends up being different in podfile.lock.

**Comment by tomekzaw** [comment]
Hey @shamilovtim, thanks for reporting this issue. At this moment the root cause of this issue is unknown to me. I've tried installing Reanimated in a fresh RN 0.68.3 app both on M1 and Intel machine but obviously the hashes are different due to different project paths. I found this issue in CocoaPods repo (https://github.com/CocoaPods/CocoaPods/issues/11455) and compared `RNReanimated.podspec.json` generated by both machines but they are identical, excluding the path in `HEADER_SEARCH_PATHS` field.
