### ISSUE TITLE
fatal error: 'RuntimeManager.h' file not found

### ISSUE THREAD

**Issue by DtheRock** [software-mansion/react-native-reanimated#3708]
### Description

 ../../../../src/main/cpp/FrameProcessorRuntimeManager.h:13:10: fatal error: 'RuntimeManager.h' file not found
  #include "RuntimeManager.h"

### Steps to reproduce

I am getting this error when building an android app with a version later than 2.10.0. 

### Snack or a link to a repository

https://snack.expo.dev/

### Reanimated version

2.11.0

### React Native version

0.67.4

### Platforms

Android

### Acknowledgements

Yes

**Comment by tomekzaw** [comment]
Hey, it looks like react-native-vision-camera doesn't support Reanimated 2.11.0. That's because recently we changed the structure of header files (i.e. unpacked them from `headers` directories).

I believe this is pretty easy to fix here: https://github.com/mrousavy/react-native-vision-camera/blob/849aa3ebaf8edf8ad0809b1277097fa05db13c29/android/CMakeLists.txt#L64-L69

For backward-compatibility purposes, we can leave old paths and add new ones without `headers/`. cc @mrousavy

**Comment by mrousavy** [comment]
Got it - thanks for the heads up @tomekzaw! Created a PR here: https://github.com/mrousavy/react-native-vision-camera/pull/1301 - that should work
