### ISSUE TITLE
useAnimatedKeyboard doesn't update height value on input change

### ISSUE THREAD

**Issue by thecoorum** [software-mansion/react-native-reanimated#3721]
### Description

While using `useAnimatedKeyboard` hook I noticed that on changing inputs with different keyboard types (keyboard suggestions are enabled or disabled) it doesn't update the height value which causes an incorrect styling of element

### Steps to reproduce

1. Create a page both with enabled and disabled suggestions `TextInput`'s
2. Use `useAnimatedKeyboard` hook to get keyboard height value
3. Switch between inputs and check the returned values from hook

### Snack or a link to a repository

https://github.com/thecoorum/reanimated-keyboard-issue

### Reanimated version

2.10.0

### React Native version

0.69.6

### Platforms

iOS

### JavaScript runtime

Hermes

### Workflow

Expo managed workflow

### Architecture

Paper (Old Architecture)

### Build type

Debug mode

### Device

iOS simulator

### Acknowledgements

Yes

**Comment by kbrandwijk** [comment]
I noticed the same thing switching from number-pad to regular keyboard with suggestions, height is not updated.

**Comment by graszka22** [comment]
In your example you're using `useAnimatedKeyboard()` directly in your component like this:
```js
export default function App() {
  const keyboard = useAnimatedKeyboard();

  // Should update on switching between keyboard types
  console.log(keyboard.height.value);

  return (
    ...
  );
}
```
But `useAnimatedKeyboard()` is rather meant to be used for example with `useAnimatedStyle` hook, as shown in the example in the documentation: https://docs.swmansion.com/react-native-reanimated/docs/next/api/hooks/useAnimatedKeyboard#example. If you add `console.log(keyboard.height.value)` in the `useAnimatedStyle` you'll see that the height of the keyboard indeed changes.

`useAnimatedKeyboard()` does not cause a component re-render when keyboard height changes and that's why `console.log` is not called. The hook just returns a shared value with keyboard height that is updated without the re-renders. And that's a good thing, because `useAnimatedKeyboard()` tracks the height of the keyboard while it's animating. That means that when showing the keyboard the height of the keyboard can change at a rate of 60 times per second. You wouldn't want to re-render your component 60 times per second, because you'd get a slideshow instead of an animation. 

If you'd want to re-render your component anyway (I don't know your use case) when the keyboard opens/closes you can do so with `useAnimatedReaction` hook. Here is an example: https://gist.github.com/graszka22/a7933e69927fcc4f603abefe46f533b8
When keyboard opens/closes the react state is set and that causes a re-render and the `console.log` is executed.  I've set the state only when the keyboard is fully opened/closed to avoid re-rendering while animating. 

There is one issue related to this one that I found while testing your example: https://github.com/software-mansion/react-native-reanimated/pull/3940, but I think your issue is the misunderstanding I described above.

I hope that cleared up things a bit :)

**Comment by kbrandwijk** [comment]
Ah, the issue that I was running into (as I was already using it together with useAnimatedStyle), was indeed related to the issue you linked the PR for, which was switching from a keyboard without suggestions bar to one with.

**Comment by thecoorum** [comment]
@kbrandwijk same for me

**Comment by wezter96** [comment]
@graszka22 I am trying to use the height of the keyboard to animate my bottomsheet expanding but that does not seem to work well for me on Android but it works completely fine on iOS.
on Android this always logs 0
```ts
  const animatedStyle = useAnimatedStyle(() => {
    console.log('keyboard: ', keyboard.height.value);
    return {
      transform: [{ translateY: translateY.value }],
      top: isKeyboardAware ? SCREEN_HEIGHT - keyboard.height.value : SCREEN_HEIGHT,
    };
  });
  ```

**Comment by graszka22** [comment]
@wezter96 Hi, it works for me on the main branch. Please provide an example project (a repo or expo snack) that reproduces the problem. Make sure to setup the app correctly (https://docs.swmansion.com/react-native-reanimated/docs/next/api/hooks/useAnimatedKeyboard) and it would be best to create a separate issue as this is a completely different issue.
