### ISSUE TITLE
Could not get unknown property 'minor' for project ':react-native-reanimated' of type org.gradle.api.Project.

### ISSUE THREAD

**Issue by ivosabev** [software-mansion/react-native-reanimated#3861]
### Description

In android/build.gradle on line 285 and 288 there is a reference to a variable called `$minor`, I believe that is a type and it should be `$rnMinorVersionCopy`

https://github.com/software-mansion/react-native-reanimated/blob/main/android/build.gradle#L285

### Steps to reproduce

....

### Snack or a link to a repository

...

### Reanimated version

2.13.0

### React Native version

0.71.0-rc.3

### Platforms

Android

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Fabric (New Architecture)

### Build type

Debug mode

### Device

Android emulator

### Acknowledgements

Yes

**Comment by raminafandi** [comment]
Same issue, have you found a solution @ivosabev ?

**Comment by raminafandi** [comment]
@ivosabev I have changed that, but anyway the app was crashing in android every time when I was running, so downgraded react-native and everything works after downgrading version to 0.70.6.

**Comment by andreasbergqvist** [comment]
The error seems to be due to the $minor variable on line 288 and 291 in:
https://github.com/software-mansion/react-native-reanimated/blob/main/android/build.gradle#L288

It only happens if you are running a version of React Native higher than the current one supported by reanimated.

With the latest release of reanimated, which has support for React Native 0.71, the problem is gone (if you were running 0.71). But I guess the same will happen again with React Native 0.72. Since it is a warning that you are running an unsupported version, I guess the variables should be updated as @ivosabev mentions.
