### ISSUE TITLE
ReDoS when parsing colors

### ISSUE THREAD

**Issue by GonzaloGCV** [software-mansion/react-native-reanimated#3898]
### Description

As #3382 is mentioned: _"The regular expression used to parse numbers could be abused to cause a denial of service if the color to be parsed is controlled by an attacker."_

This fix was launched in release 2.10. I cannot upgrade my dependencies from 2.8 to 2.10 but I would like to fix the issue that synk auditied me.

Is possible to release a new 2.8.1 version with this fix?

### Steps to reproduce

For information about this vulnerability, see https://owasp.org/www-community/attacks/Regular_expression_Denial_of_Service_-_ReDoS.

### Snack or a link to a repository

#3382 

### Reanimated version

2.8.0

### React Native version

0.68.2

### Platforms

Android, iOS, Web

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by tomekzaw** [comment]
> Is possible to release a new 2.8.1 version with this fix?

Hey, generally we don't publish patch releases for older versions, especially for those that are 8 months old if there is 5 newer minor releases (latest is 2.13.0).

However, since the fix is JS-only, I would recommend applying it on your own using [patch-package](https://www.npmjs.com/package/patch-package).

Also, please note that in my opinion this vulnerability is hardly exploitable since colors are almost never controlled by the user (obviously, it depends on the use case). Honestly, I think there's a number of easier ways to exploit the app which just haven't been reported.

> I cannot upgrade my dependencies from 2.8 to 2.10

Can you please explain what's the reason you can't upgrade? Maybe other users have the same problem that we're not aware of yet.

**Comment by GonzaloGCV** [comment]
Hi @tomekzaw

> Can you please explain what's the reason you can't upgrade? Maybe other users have the same problem that we're not aware of yet.

I can't upgrade it because it seems that it is not compatible with other packages:
- "expo": "^45.0.0",
- "react": "17.0.2",
- "react-native": "0.68.2",

When I run `expo install react-native-reanimated@latest` this message appears:

```
Installing 1 SDK 45.0.0 compatible native module using Yarn.
> yarn add react-native-reanimated@~2.8.0
```

Thank you for your reply.

**Comment by tomekzaw** [comment]
Hi @GonzaloGCV, thanks for your response!

So apart from using patch-package for react-native-reanimated, you can also upgrade Expo SDK to 46 or 47 which include Reanimated 2.11 I think.

**Comment by piaskowyk** [comment]
Hello 👋 At this moment, both Reanimated 2 and 3 contain the fix for the ReDoS issue, so I think we can close the issue.
