### ISSUE TITLE
[3.0] com.swmansion.reanimated.Scheduler.triggerUI

### ISSUE THREAD

**Issue by andresribeiro** [software-mansion/react-native-reanimated#3931]
### Description

After upgrading from `v2.13.0` to `v3.0.0-rc.10`, the following error started to occur (i've found on Play Console)

```
com.swmansion.reanimated.Scheduler.triggerUI
java.lang.RuntimeException

Exception java.lang.RuntimeException:
  at com.swmansion.reanimated.Scheduler.triggerUI (Scheduler.java)
  at com.swmansion.reanimated.Scheduler$1.run (Scheduler.java)
  at com.swmansion.reanimated.Scheduler$2.runGuarded (Scheduler.java)
  at com.facebook.react.bridge.GuardedRunnable.run (GuardedRunnable.java)
  at android.os.Handler.handleCallback (Handler.java:938)
  at android.os.Handler.dispatchMessage (Handler.java:99)
  at android.os.Looper.loopOnce (Looper.java:226)
  at android.os.Looper.loop (Looper.java:313)
  at android.app.ActivityThread.main (ActivityThread.java:8751)
  at java.lang.reflect.Method.invoke (Method.java)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:571)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1135)
```

### Steps to reproduce

I don't know what could have led to this error, but I believe it was the Layout Animation (I'm using it for both entering and exiting)

### Snack or a link to a repository

https://snack.expo.io/

### Reanimated version

3.0.0-rc.10

### React Native version

0.70.6

### Platforms

Android

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Paper (Old Architecture)

### Build type

Release mode

### Device

Real device

### Device model

Occurred on Samsung, Redmi, POCO and Huawei devices

### Acknowledgements

Yes

**Comment by devoren** [comment]
@andresribeiro Hello, how did you solve this?

**Comment by andresribeiro** [comment]
@devoren I didn't. With the stable release of version 3, I thought it had been fixed

**Comment by devoren** [comment]
@andresribeiro Thanks for the quick response! ok i will try version 3.0

**Comment by kbvac** [comment]
> @devoren I didn't. With the stable release of version 3, I thought it had been fixed

good i will try too

**Comment by kbvac** [comment]
React.useEffect(() => {
    if (selectedTab == constants.screens.schedule) {
      flatListRef?.current?.scrollToIndex({
        index: 0,
        animated: true,
      });
      notifTabFlex.value = withSpring(4, { duration: 500 });
      notifTabColor.value = withSpring(COLORS.primary, { duration: 500 });
    } else {
      notifTabFlex.value = withSpring(1, { duration: 500 });
      notifTabColor.value = withSpring(COLORS.white, { duration: 500 });
    }

    if (selectedTab == constants.screens.available) {
      flatListRef?.current?.scrollToIndex({
        index: 1,
        animated: true,
      });
      walletTabFlex.value = withSpring(4, { duration: 500 });
      walletTabColor.value = withSpring(COLORS.primary, { duration: 500 });
    } else {
      walletTabFlex.value = withSpring(1, { duration: 500 });
      walletTabColor.value = withSpring(COLORS.white, { duration: 500 });
    }

    if (selectedTab == constants.screens.profile) {
      flatListRef?.current?.scrollToIndex({
        index: 2,
        animated: true,
      });
      favTabFlex.value = withSpring(4, { duration: 500 });
      favTabColor.value = withSpring(COLORS.primary, { duration: 500 });
    } else {
      favTabFlex.value = withSpring(1, { duration: 500 });
      favTabColor.value = withSpring(COLORS.white, { duration: 500 });
    }
  }, [selectedTab]);

my crash error is because of COLORS.color value when i comment this part no crash

Your app just crashed. See the error below.
java.lang.RuntimeException: com.facebook.react.bridge.JSApplicationIllegalArgumentException: Error while updating property 'backgroundColor' of a view managed by: RCTView
  com.swmansion.reanimated.Scheduler.triggerUI(Native Method)
  com.swmansion.reanimated.Scheduler$1.run(Scheduler.java:24)
  com.swmansion.reanimated.Scheduler$2.runGuarded(Scheduler.java:43)
  com.facebook.react.bridge.GuardedRunnable.run(GuardedRunnable.java:30)
  android.os.Handler.handleCallback(Handler.java:938)
  android.os.Handler.dispatchMessage(Handler.java:99)
  android.os.Looper.loop(Looper.java:223)
  android.app.ActivityThread.main(ActivityThread.java:7656)
  java.lang.reflect.Method.invoke(Native Method)
  com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
  com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
