### ISSUE TITLE
"Maximum call stack exceeded" error during fast refresh and custom events handler usage

### ISSUE THREAD

**Issue by kirillzyusko** [software-mansion/react-native-reanimated#3967]
### Description

If we are using custom event handlers as per [this](https://docs.swmansion.com/react-native-reanimated/docs/fundamentals/custom_events/) guide and fast refresh happens (you changed a file), then "Maximum call stack size exceeded" error appears.

It's not critical, since in release app it never happens, but during development it's very annoying to see this error constantly 😬 

P. S. if code is located in `App.js` file and you change it, then error is not showing up. But if the changes happen in isolated/separate file - the error always appears. Also if you remove `worklet` directives - everything works good and errors not showing up.

### Steps to reproduce

- open example app;
- go to `AnimatedRefExample` file and try to modify style of `AnimatedPager` component (change `flex` to `2`/`3`/`etc.`)

**Actual result:**

![image](https://user-images.githubusercontent.com/22820318/213256780-314b0c56-6550-424f-b17f-7407e5823877.png)

**Expected result:**

No error happens.

### Snack or a link to a repository

https://github.com/kirillzyusko/reanimated-issue

### Reanimated version

2.14.2

### React Native version

0.70.5

### Platforms

iOS

### JavaScript runtime

JSC

### Workflow

React Native (without Expo)

### Architecture

Paper (Old Architecture)

### Build type

Debug mode

### Device

iOS simulator

### Device model

iPhone 14 Pro (iOS 16.2), simulator

### Acknowledgements

Yes

**Comment by kmagiera** [comment]
Hi, I investigated this issue and it turned out to be related to handling of animated refs. The second render cause animated ref object to be captured in the worklet and processing that object resulted in infinite loop because of its recursive structure. This issue has been fixed in Reanimated 3 and I verified you example works correctly on recent versions. I'll be closing this one but in case you still experience this please let us know. Note, that this issue wasn't limited to fast refresh but any scenario in which the inner component would get rerendered.

**Comment by kirillzyusko** [comment]
Hi @kmagiera 

Yes, I don't experience this problem anymore (for some reasons I thought the issue was closed automatically).

Thank you for fixing this problem! I appreciate that!
