### ISSUE TITLE
Using clockRunning/stop/start clock inside the proc

### ISSUE THREAD

**Issue by terrysahaidak** [software-mansion/react-native-reanimated#400]
I've been playing with `proc` and it looks so promising!

But I've noticed it doesn't work with `clockRunning, startClock, stopClock` blocks, since we are passing animated param into each of them and [all of this ](https://github.com/kmagiera/react-native-reanimated/blob/master/src/core/AnimatedStartClock.js#L10-L13) invariants throw.

If I commented those invariants, app crashes on execution. On Android it says something like that:

<img src="https://user-images.githubusercontent.com/7809008/65589964-a18b7000-df92-11e9-83ce-7b9c91342b27.png" height="600" />

By the way, here are some perf results with [my example](https://github.com/terrysahaidak/react-native-reanimated-proc-test). You can change [these lines](https://github.com/terrysahaidak/react-native-reanimated-proc-test/blob/master/App.tsx#L5-L12) to use different versions. It renders 100 animated views, also animates 4 properties of each one with `timing`, so there are 400 timings. 
Check out perf monitor and delay until animation plays.

[Without proc](https://github.com/terrysahaidak/react-native-reanimated-proc-test/blob/master/useTiming.ts) :
![useTiming](https://user-images.githubusercontent.com/7809008/65589284-794f4180-df91-11e9-864d-2407d02f5c66.gif)

With [some atomic proc usage](https://github.com/terrysahaidak/react-native-reanimated-proc-test/blob/master/useProcTiming.ts) (everything except clockRunning, startClock, stopClock):

![useProcTiming](https://user-images.githubusercontent.com/7809008/65589439-b87d9280-df91-11e9-8dfa-9f20dfafaecd.gif)

[Everything](https://github.com/terrysahaidak/react-native-reanimated-proc-test/blob/master/useSuperProcTiming.ts) wrapped with proc:

![useSuperProcTiming](https://user-images.githubusercontent.com/7809008/65589537-e2cf5000-df91-11e9-954d-984c62fb4e7b.gif)

**Comment by ddzirt** [comment]
@osdnk

Correct me if I am wrong.

This error is because of this line on Android:
https://github.com/kmagiera/react-native-reanimated/blob/ac97ebba37e21dbd3de242328ad9409e25b8d200/android/src/main/java/com/swmansion/reanimated/NodesManager.java#L214

so basically changing it to this:
```java
if (type == Node.class || type == ValueNode.class || type == ParamNode.class || 
  FunctionNode.class) {
... code ...
}
```

it would pass and probably work. 

And, most likely, we would not need any changes to this:
https://github.com/kmagiera/react-native-reanimated/blob/master/src/core/AnimatedStartClock.js#L11

or this:

https://github.com/kmagiera/react-native-reanimated/blob/ac97ebba37e21dbd3de242328ad9409e25b8d200/src/core/AnimatedStopClock.js#L10

I might be wrong though.

**Comment by ddzirt** [comment]
OK, I am wrong this is not enough. 

And `invariant` has to be removed within `AnimatedClock.test.js`, `AnimatedStartClock.js` and `AnimatedStopClock.js`

**Comment by ddzirt** [comment]
If we do comment stuff out we will get this:
<img width="415" alt="Screen Shot 2019-09-25 at 17 17 18" src="https://user-images.githubusercontent.com/973562/65610379-ebd41780-dfb9-11e9-9842-adb25f703e94.png">

Meaning this works OK:
<img width="832" alt="Screen Shot 2019-09-25 at 17 29 24" src="https://user-images.githubusercontent.com/973562/65610461-0e663080-dfba-11e9-9b91-9b8c73267d5b.png">

But here, since we have `ParamNode` that derives from `ValueNode` and `FunctionNode` that derives from `Node` are incompatible with `ClockNode` and can not be converted.
<img width="633" alt="Screen Shot 2019-09-25 at 17 30 27" src="https://user-images.githubusercontent.com/973562/65610556-32c20d00-dfba-11e9-9782-baa9fb6eed63.png">

So as far as I understand this, we need to create a `Mapper` to make it work here and maybe then it will work. Still, I might be wrong again.

**Comment by ddzirt** [comment]
And by `Mapper` I mean something like this(do not mind this ugly piece, just trying it out):

<img width="664" alt="Screen Shot 2019-09-25 at 17 51 43" src="https://user-images.githubusercontent.com/973562/65612615-3dca6c80-dfbd-11e9-833d-1f12c7d1853a.png">

This stops errors that drop-in but also breaks animation, so it is either completely wrong way or me missing something.

**Comment by osdnk** [comment]
Hm, I'm not sure if I understand. Can you rather open a PR (even not working)? It will be easier to discuss there

**Comment by ddzirt** [comment]
Ok

**Comment by khorark** [comment]
If I'm use proc I turns out can't use clock in inside proc function? My animation not work, but if I remove proc all good. How I can used animation in declarative approach with proc and animation?

**Comment by terrysahaidak** [comment]
@khorark You can pass the clock as an argument, however, currently, you cannot call `stopClock`, `clockRunning`, `startClock` inside the proc.

**Comment by ShaMan123** [comment]
+1

**Comment by osdnk** [comment]
Fixed on master

**Comment by osdnk** [comment]
rel https://github.com/software-mansion/react-native-reanimated/commit/53f458b1ac7671dfa4d3198319687fe00bd602a0
