### ISSUE TITLE
get error when application up only in non debugger mode #4017

### ISSUE THREAD

**Issue by YOEL311** [software-mansion/react-native-reanimated#4029]
### Description

hey
 I installed react-native-reanimated on my app
 I did everything according to the instructions
 
added package on my ``MainApplication.java``
 ````
 packages.add(new ReanimatedPackage());
````
I also added this as the last plugin in my ``babel.config.js``

but my app crashed when React up 
I got error 

`Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication). A frequent cause of the error is that the application entry file path is incorrect.
      This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native.`
but when I switch to debug mode (of react native) app work as well
**It happens both on IOS and ANDROID platforms**

my error
![image](https://user-images.githubusercontent.com/39925212/216286597-5eedcaf5-acb0-49d4-824a-972cc0027cb1.png)

![image](https://user-images.githubusercontent.com/39925212/216286659-f1f79fd4-6fd3-479b-a572-95aafe69e3fa.png)

this my ``babel.config.js``
````
module.exports = {
  presets: [
    'module:metro-react-native-babel-preset',
    '@babel/preset-typescript',
  ],
  plugins: [
    [
      '@babel/plugin-transform-react-jsx',
      {
        runtime: 'automatic',
      },
    ],
    [
      'module:react-native-dotenv',
      {
        moduleName: '@env',
        path: '.env',
        blacklist: null,
        whitelist: ['AES_KEY'],
        safe: false,
        allowUndefined: false,
      },
    ],
    [
      'babel-plugin-root-import',
      {
        rootPathPrefix: '~',
        rootPathSuffix: 'src',
      },
    ],
    'react-native-reanimated/plugin'
  ]
};

````
 
 my relevant libraries from ``package.json``
 ````
    "@react-navigation/bottom-tabs": "6.5.3",
    "@react-navigation/native": "6.1.2",
    "@react-navigation/stack": "6.3.11",
    "react-native-gesture-handler": "2.9.0",
     "react-native-reanimated": "2.14.4",
     "react-native-redash": "18.1.0",
     "metro-react-native-babel-preset": "0.66.2",
     "react": "18.0.0",
     "react-native": "0.69.7",

 ````
 

### Steps to reproduce

1. npx react-native start --reset-cache
2. open my app

### Snack or a link to a repository

all example

### Reanimated version

2.14.4

### React Native version

0.69.7

### Platforms

Android

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Paper (Old Architecture)

### Build type

Release mode

### Device

Real device

### Device model

 android Samaung Galaxy S22 

### Acknowledgements

Yes

_Originally posted by @YOEL311 in https://github.com/software-mansion/react-native-reanimated/discussions/4017_

**Comment by graszka22** [comment]
Please describe exactly how are you building and running the app because something doesn't add up. Apps in release mode shouldn't have red screens (they just crash) also they don't need to connect to the packager because the js bundle is built when building the native app. How are you switching to debug mode?

Also:
```
packages.add(new ReanimatedPackage());
```
you probably don't need to do that, autolinking should just work.

**Comment by graszka22** [comment]
I just created a new project with RN `0.69.7` and Reanimated `2.14.4` and run the app on real device with android with `npx react-native run-android` and `npx react-native start --reset-cache`.  Everything works. So I'm guessing there is something wrong with the way your app is configured or run, especially since it's a hybrid app. Without example project and exact steps to reproduce I have no idea how your app is configured and it's not possible for me to help you.
