### ISSUE TITLE
Uncaught ReferenceError: Cannot access 'fun' before initialization

### ISSUE THREAD

**Issue by ertemishakk** [software-mansion/react-native-reanimated#4055]
### Description

Cant use `const t = useAnimatedRef()` after `import {useAnimatedRef} from 'react-native-reanimated` - it breaks the app

<img width="1023" alt="Screen Shot 2023-02-16 at 3 41 58 pm" src="https://user-images.githubusercontent.com/56520971/219270517-c62f7c5f-b370-4daa-9439-8dfc41212dee.png">

### Steps to reproduce

`import {useAnimatedRef} from 'react-native-reanimated`
`const t = useAnimatedRef()`

For some reason works fine on snack

### Snack or a link to a repository

https://snack.expo.dev/xSv5Y1l-u 

### Reanimated version

2.14.4

### React Native version

0.71.3

### Platforms

Web

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by tomekzaw** [comment]
Hey @ertemishakk, did you remember to add `plugins: ['react-native-reanimated/plugin']` in your `babel.config.js`?

**Comment by ertemishakk** [comment]
@tomekzaw hey, thanks for getting back. Yes, I've already added it in the babel config. Everything seems to be working fine - I can use other hooks and animate components. Except `useAnimatedRef`

**Comment by graszka22** [comment]
Hi @ertemishakk I've created a new expo web app (`npx create-expo-app my-app`), added reanimated (`expo install react-native-reanimated`) and added babel plugins:
```js
module.exports = function (api) {
  api.cache(true);
  return {
    presets: ["babel-preset-expo"],
    plugins: [
      "@babel/plugin-proposal-export-namespace-from",
      "react-native-reanimated/plugin",
    ],
  };
};
```
and it works for me. I suspect there might be something different with your project configuration. Could you provide an example repro on github, with all bundler and babel configs?

**Comment by ertemishakk** [comment]
@graszka22 hi there, here is the repo - https://github.com/ertemishakk/react-native-web-template, you can have a look at `App.tsx` and uncomment the commented code.

**Comment by graszka22** [comment]
Ok, I think I solved it. But that's complicated 😅 

To fix it quickly you can just add `'@babel/plugin-transform-block-scoping'` plugin to the top of your plugins list in `craco.config.js`. Don't forget to reset cache when you're changing anything related to babel (so remove your `node_modules` or whatever you're supposed to do on web). Or use `babel-preset-expo` (you don't even have to use expo for this). 
You can also use the newest v3 version of reanimated. 

Now why it doesn't work for your project: you're using `@babel/preset-react` as your babel preset. The transpiled output looks like this:
```js
function useAnimatedRef() {
  const tag = (0,_useSharedValue__WEBPACK_IMPORTED_MODULE_1__.useSharedValue)(-1);
  const ref = (0,react__WEBPACK_IMPORTED_MODULE_0__.useRef)();
  if (!ref.current) {
    const fun = function () {
      const _f = function (component) {
        // enters when ref is set by attaching to a component
        if (component) {
          tag.value = (0,_NativeMethods__WEBPACK_IMPORTED_MODULE_2__.getTag)(component);
          fun.current = component;
        }
        return tag.value;
      };
      _f._closure = {
        tag,
        getTag: _NativeMethods__WEBPACK_IMPORTED_MODULE_2__.getTag,
        fun
      };
// ...
      return _f;
    }();
//...
```

The transpiled output with expo's preset on the other hand looks like this:
```js
function useAnimatedRef() {
  var tag = Object(_useSharedValue__WEBPACK_IMPORTED_MODULE_2__["useSharedValue"])(-1);
  var ref = Object(react__WEBPACK_IMPORTED_MODULE_0__["useRef"])();
  if (!ref.current) {
    var fun = function () {
      var _f = function _f(component) {
        if (component) {
          tag.value = Object(_NativeMethods__WEBPACK_IMPORTED_MODULE_1__["getTag"])(component);
          fun.current = component;
        }
        return tag.value;
      };
      _f._closure = {
        tag: tag,
        getTag: _NativeMethods__WEBPACK_IMPORTED_MODULE_1__["getTag"],
        fun: fun
      };
      // ...
      return _f;
    }();
// ...
```

The difference is that in expo preset we have `var`s instead of `const`s. And you can't access `const`s before they're initialized, as opposed to `var`s ([docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Cant_access_lexical_declaration_before_init)).
In the transpiled code we access fun (`_f._closure = { fun: fun }`) before it's initialized. 
Expo's preset includes `metro-react-native-babel-preset` which includes `'@babel/plugin-transform-block-scoping'` which turns `const`s into `var`s (among many other plugins). There, mystery solved 🕵️ 

As for the newest version of reanimated, I can see that we're no longer using `fun` in the worklet, so it's not in the closure anymore so it should be ok. But there are other weird errors with your configuration on v3 as far as I tested so maybe it would be better use the expo's preset. It's even recommended in official `react-native-web` [docs](https://necolas.github.io/react-native-web/docs/multi-platform/)

**Comment by ertemishakk** [comment]
@graszka22 thank you for your help, that solves my problem. The reason I'm not using expo is that im working on mono repo for multiple environments which expo doesnt have support for.  Great explanation though - thanks again

**Comment by HuuNguyen312** [comment]
@graszka22 Thank you. My problem is solved.

```
  babel: {
    presets: ['@babel/preset-react'],
    plugins: [
      '@babel/plugin-transform-block-scoping',
      '@babel/plugin-proposal-export-namespace-from',
      'react-native-reanimated/plugin',
    ],
  },
```
