### ISSUE TITLE
Layout animation display when component unmount

### ISSUE THREAD

**Issue by MasonLe2497** [software-mansion/react-native-reanimated#4063]
### Description

I use layout animation with entering and exiting.
When i push new element then back to prev screen. Layout animation show and entering running. 
U can see my video:

https://user-images.githubusercontent.com/43195241/219549471-d95d7537-510c-46c9-a529-0c545cf164c0.mp4

On android: it work but layout animation be crop:
video:

https://user-images.githubusercontent.com/43195241/219549622-818b5a02-bce2-4eeb-8975-d8c32517ba11.mov

My code: [RNChallenge](https://github.com/MasonLe2497/RNChallengeV3)

### Steps to reproduce

Create Layout animation: entering, exiting
Go back to prev screen (react-navigation/native-stack)

### Snack or a link to a repository

https://github.com/MasonLe2497/RNChallengeV3

### Reanimated version

3.0.0-rc.10

### React Native version

0.71.3

### Platforms

iOS

### JavaScript runtime

None

### Workflow

React Native (without Expo)

### Architecture

Paper (Old Architecture)

### Build type

Debug mode

### Device

iOS simulator

### Device model

Iphone 11 (16.2)

### Acknowledgements

Yes

**Comment by jwajgelt** [comment]
Hi @MasonLe2497 !
Thanks for reporting this issue.
Could you try if this occurs on the main branch as well? Layout animations rewrite had issues with `native-stack` that were fixed in #3865, but that PR didn't make it into a release yet.

**Comment by jwajgelt** [comment]
I checked out reanimated on this commit: https://github.com/software-mansion/react-native-reanimated/commit/e6e239a3923dfd934bd688348ad49a922615b09d, and the iOS issue disappears.
We're working on the next release for v3, which will include this change.

**Comment by jwajgelt** [comment]
As for the Android issue - that one is still a problem, I'll look into it.

**Comment by jwajgelt** [comment]
Ok, I think I see what the issue on Android is.

The screen contents are wrapped in a `ScrollView`, which grows and shrinks with its contents. When you delete the last item in a row, the `ScrollView` shrinks (because exiting animations don't impact layout - RN doesn't "see" the exiting views). 
This causes the exiting views to clip to the new `ScrollView` size (see: [#31218](https://github.com/facebook/react-native/issues/31218) on RN repo). This seems like a bug in React Native, though it doesn't seem like it will be fixed anytime soon (seeing how the linked issue has been up for ~2 years at this point).

You may find some workarounds in the linked issue.
