### ISSUE TITLE
ReanimatedError: Maximum call stack size exceeded (native stack depth), js engine: reanimated

### ISSUE THREAD

**Issue by Willham12** [software-mansion/react-native-reanimated#4151]
### Description

App crashed with that code from reproduction with v3.0.0, no issues with v2.14.4.

### Steps to reproduce

https://github.com/zyslife/react-native-head-tab-view/blob/master/Example/react-native-head-tab-view/createCollapsibleScrollView.tsx#L160

### Snack or a link to a repository

https://github.com/zyslife/react-native-head-tab-view/blob/master/Example/react-native-head-tab-view/createCollapsibleScrollView.tsx#L160

### Reanimated version

3.0.0

### React Native version

0.71.3

### Platforms

iOS

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Paper (Old Architecture)

### Build type

Release mode

### Device

Real device

### Device model

iPhone XR

### Acknowledgements

Yes

**Comment by jwajgelt** [comment]
Hi @Willham12, thanks for reporting your issue!
I've tried running the example from the library you linked with RN 0.71 and Reanimated 3, but wasn't able to build it due to outdated dependencies.
Would you be able to provide a reproduction which uses that library and builds with these versions of react-native and reanimated?

**Comment by Willham12** [comment]
> same library with the same issue have you found a work around? @Willham12 ?

I remove the lib and replaced with https://reactnative.dev/docs/scrollview#stickyheadercomponent
