### ISSUE TITLE
ENOENT: no such file or directory, open '...../node_modules/react-native-gesture-handler/src/handlers/gestures/GestureDetector.tsx' when upgrading to 3.0.2 Reanimated

### ISSUE THREAD

**Issue by vukan-m** [software-mansion/react-native-reanimated#4320]
### Description

When upgrading reanimated to latest version, and having gesture-handler installed, this error occurs. My project is monorepo.
![Screenshot 2023-04-03 at 08 34 55](https://user-images.githubusercontent.com/36018864/229430101-00097736-812a-4d20-8cea-18d48e7d8ce1.png)

Expecting everything to work great, just to upgrade version and continue working.

You can test it on my repo, if you run yarn install now, app will run, but if you update react-native-reanimated to "3.0.2", app will no longer run.

### Steps to reproduce

1.  Setup basic yarn workspace monorepo project
2. Install react-native-reanimated 3.0.2
3. Install react-native-gesture-handler 2.9.0
4. Error occurs

### Snack or a link to a repository

https://github.com/vukan-m/reanimated-reproduce-error

### Reanimated version

3.0.2

### React Native version

0.70.5

### Platforms

Android

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Paper (Old Architecture)

### Build type

Debug mode

### Device

Android emulator

### Device model

Pixel 4 API 33 (Tiramisu)

### Acknowledgements

Yes

**Comment by vukan-m** [comment]
I only have react-native-gesture-handler import in my index.js and my bundler fails. I've debugged a little, when i remove react-native-reanimated/plugin from my babel.config, app bundles. When i comment out processIfWorkletNode from react-native-reanimated/plugin, i don't receive that error. Debugging is still in process, i'm in makeWorklet function atm, maybe the problem is here, maybe it's deeper. I hope this shines some light on the problem.

**Comment by NiharR27** [comment]
Can confirm i see the same issue.

**Comment by gitstud** [comment]
Also have this issue

**Comment by gitstud** [comment]
@vukan-m have you found any way to work around this issue?

**Comment by gitstud** [comment]
I was able to hack a solution with

```
for (const sourceFile of inputMap.sources) {
  if (process.PWD.includes("problematic/path"))
      inputMap.sourcesContent.push(
        fs.readFileSync(
            sourceFile.includes('node_modules') ? 
                     `.${sourceFile}` : 
                      process.env.PWD.split('/path')[0] + '/src' + sourceFile.split('/src')[1]
         ).toString('utf-8') <-- this is the problem, since file at the provided path doesn't exist
      );
    } else {
        fs.readFileSync(sourceFile).toString('utf-8')
}
}
```

**Comment by JulioCVaz** [comment]
same problem here, we also use a monorepo. I will test the approach of @gitstud

**Comment by vukan-m** [comment]
@gitstud 
i was able to run the app by tweaking plugin/index.js
```js
    for (const sourceFile of inputMap.sources) {
      if (fs.existsSync(sourceFile)) {
        inputMap.sourcesContent.push(
          fs.readFileSync(sourceFile).toString('utf-8')
          );
        } else {
          const newPath = sourceFile.replace("packages/RNApp", "");
          inputMap.sourcesContent.push(
            fs.readFileSync(newPath).toString('utf-8')
          )
        }
    }

```

**Comment by igorwessel** [comment]
@vukan-m We able to resolve this issue changing some settings in our project.

in MainApplication.java removed the entrypoint pointed for app package.
```java
	// before
    @Override
    protected String getJSMainModuleName() {
      return "packages/app/index";
    }

	// after
  	@Override
    protected String getJSMainModuleName() {
      return "index"; 
    }
```

And metro.config.js, we remove the projectRoot and configure watchFolders so metro that it can resolve dependencies.
```js
  watchFolders: [
    path.resolve(__dirname, '../../node_modules'),
    path.resolve(__dirname, '../../node_modules/@test-app/shared'),
  ],
```

I hope it helps!

**Comment by tjzel** [comment]
Hi @vukan-m, thanks for reporting the issue.

I have investigated the problem and ultimately concluded that it is happening due to improper configuration of your monorepo.

First of all, when we take a look at `packages/RNApp/index.js`, we can find there:

```JavaScript
import "react-native-gesture-handler";
```
While it seems not to be causing any issues, I don't see a reason for it to be there.

When we look at the error that metro gives while trying to build the Android app:

```
error packages/RNApp/App.tsx: /Users/root/reanimated/repro/packages/RNApp/packages/RNApp/App.tsx: ENOENT: no such file or directory, open '/Users/root/reanimated/repro/packages/RNApp/packages/RNApp/App.tsx'.
```

We can clearly see this `packages/RNApp/packages/RNApp/App.tsx`. This error comes from our babel plugin that is trying to access this file - but the directory of this file is provided by the metro bundler. So, the metro bundler fails to properly resolve directories for your monorepo. When we look into `packages/RNApp/metro.config.js`, we can see this line there:

```JavaScript
projectRoot: path.resolve(__dirname, "../.."),
```

Which seems to be the offender.

Trying to just get the bundle of the app with metro with this line:

```
yarn react-native bundle --reset-cache --platform android --dev true --entry-file App.tsx --bundle-output App.bundle.js
```

Also fails.

After I made the following change:

```Diff
-  projectRoot: path.resolve(__dirname, "../.."),
+  watchFolders: [path.resolve(__dirname, "../.."), ],
```

And moved `babel.config.js` to `packages/RNApp/babel.config.js`, manual bundling with the aforementioned command worked, and I've received your app bundle - metro provided correct directories this time.

The Android app still wasn't working and, since I'm not really proficient with configuring build files for Android, especially for monorepos, I have failed to make it work. However, I noticed that the configuration provided for it is also a little bit odd. Not to mention the iOS App, as I wasn't able to build it at all, with or without reanimated, due to improper configuration.

I can't reliably help you with your configuration, but people here in the comments have already given you a handful of ideas, so I've decided to close your issue.

**Comment by xrustic2020** [comment]
I'm also ran into this problem with use monorepo, and paid many time for fix it,
was trying fix metro.config, but only one things helped for me, it's change the versions of the libraries to:

- react-native-reanimated  => 2.17.0
- react-native-gesture-handler => 2.8.0

Not sure what happened 🤷, but maybe this solution will help someone
