### ISSUE TITLE
Transition, Transitioning, TransitioningView are missing from .d.ts in 3.x

### ISSUE THREAD

**Issue by justinadkins** [software-mansion/react-native-reanimated#4362]
### Description

I just made the jump to 3.0.2 and am getting TS errors because `Transition`, `Transitioning`, and `TransitioningView` are not typed.

### Steps to reproduce

1. Import any or all of these from `react-native-reanimated`
2. Observe TS complain

### Snack or a link to a repository

https://snack.expo.dev/@justinadkins/blessed-cereal

### Reanimated version

3.0.2

### React Native version

0.71.6

### Platforms

Android

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by tomekzaw** [comment]
Hey @justinadkins, thanks for reporting this issue. `Transition`, `Transitioning`, `TransitioningView` come from v1 API which was deprecated with v2 and finally removed in v3.

**Comment by justinadkins** [comment]
I see, thank you @tomekzaw! I didn't see anything in the [documentation](https://docs.swmansion.com/react-native-reanimated/docs/api/LayoutAnimations/layoutTransitions/) here regarding this. Is there a recommended alternative?

**Comment by tomekzaw** [comment]
@justinadkins Yup, that's indeed a missing information, however we're in the process of rewriting our docs and we'll definitely add it, thanks!

The recommended alternative for [Transitions](https://docs.swmansion.com/react-native-reanimated/docs/1.x/transitions), `Transitioning` and `TransitioningView` from v1 API is to use [Layout Transitions](https://docs.swmansion.com/react-native-reanimated/docs/api/LayoutAnimations/layoutTransitions/) (the exact thing you've linked to) which were added in v2 API and are perfectly fine to use with Reanimated v3. As mentioned in the docs, `Transition` is just a placeholder and should be replaced by real animation, for instance `FadingTransition`, that's why there's no type `Transition`.

**Comment by justinadkins** [comment]
Thanks again @tomekzaw, I appreciate the detailed response.

**Comment by itishin-rzero** [comment]
Still nothing in the docs. Please add it into the migration guide to save developers time. Thx!
