### ISSUE TITLE
Reanimated 3 on Android: when using the exiting animation on an Animated.View inside a Modal, the UI becomes unresponsive

### ISSUE THREAD

**Issue by kadikraman** [software-mansion/react-native-reanimated#4422]
### Description

When using the exiting animation on an `Animated.View` inside a `Modal` , the UI becomes unresponsive. In the example you’re no longer able to press the Open Modal button. Commenting out the exiting parameter in the example the issue does not happen. Also, it’s only happening if the animated container is placed inside a Modal, and only on Android.

### Steps to reproduce

1. clone the repository https://github.com/ceceppa/reanimated-3-bug (I had to fork it for the "Snack or a link to a repository" step to make the GH issue bot happy)
2. build and run on Android
3. open the model
4. close the modal
5. open the modal again -> this will fail as the UI becomes unresponsive

### Snack or a link to a repository

https://github.com/kadikraman/reanimated-3-bug

### Reanimated version

3.0.2

### React Native version

0.71.4

### Platforms

Android

### JavaScript runtime

None

### Workflow

React Native (without Expo)

### Architecture

None

### Build type

Debug mode

### Device

None

### Acknowledgements

Yes

**Comment by ealmiladi** [comment]
I'm pretty this is related to unmounting of components. I'm seeing issues, specifically on Android, where if the exiting animation is incomplete and the component unmounts, the whole screen becomes unresponsive, as mentioned here.

**Comment by gaishimo** [comment]
I ran into the same problem too.

I was using an exiting layout animation in a modal, and when I removed it, it stopped happening.

**Comment by kartik-stan** [comment]
Same issue with me as well, if I use exiting animation inside "react-native's" Modal component the app becomes unresponsive

**Comment by TheAdamBorek** [comment]
Yep, same issue on my side :(

**Comment by justinadkins** [comment]
I just ran into this migrating some animations from using the deprecated `Transition` to layout animations. We have a component that has an `exiting` animation but the user also has the ability to close the `Modal` that the component is inside of at any point. Once closed, the entire parent of the `Modal` is unresponsive. 

Using the element inspector tool I can't even get it to select this component once in this state.

**Comment by bfricka** [comment]
I've had this issue since updating to Reanimated 3 when it first came out, and it still persists now. We held off on upgrading to 3 at the time, but since it's an issue with layout animations, and layout animations are broken in 2 anyways, we upgraded and have had to disable them in Android.

I appreciate that this bug clarifies the issue only applies to exiting animations.

**Comment by bfricka** [comment]
Update: I was able to work around this problem on Android in a less than ideal way. In AnimationsManager.java, we see that views can be kept around if their children have animations.

```java
// we might want to keep this view around
// because one of the (children's) children
// has an exiting animation
if (view instanceof ViewGroup) {
  ViewGroup viewGroup = (ViewGroup) view;
  for (int i = viewGroup.getChildCount() - 1; i >= 0; i--) {
    View child = viewGroup.getChildAt(i);
    if (removeOrAnimateExitRecursive(child, shouldRemove)) {
      hasAnimatedChildren = true;
    } else if (shouldRemove) {
      toBeRemoved.add(child);
    }
  }
}
```

Essentially, Reanimated keeps ancestor views around if a child needs to animate. A concrete example of this in my app is that I remove the toast container when there are no toasts. Without this ancestor preservation, the last toast to be removed will not animate out.

Now, for me at least, this isn't an issue. In most cases, I don't actually want the animations to be preserved when I unmount a parent. For the toast container, I can just keep it around, even when there are no toasts. If I really wanted to remove the toast container when there are no toasts, but keep the exit animation on the last one, it would be a bit annoying. I'd have to set a timeout that corresponds to the duration of the exit animation, and keep a separate state to keep the container around for that duration.

Since there are so many real world use cases I can't imagine, I'm not sure how big a deal this is.

For me at least, I am going to patch the package like:

```java
if (view instanceof ViewGroup && shouldRemove) {
  ViewGroup viewGroup = (ViewGroup) view;
  for (int i = viewGroup.getChildCount() - 1; i >= 0; i--) {
    View child = viewGroup.getChildAt(i);
    toBeRemoved.add(child);
  }
}
```
It also wouldn't make sense to continue calling the method containing this code `removeOrAnimateExitRecursive`, since it's no longer recursive. And we could remove references to `hasAnimatedChildren`, since it's no longer in use.

I'd be curious to hear feedback on this and the project maintainers thoughts.

**Comment by robwalkerco** [comment]
I work with @kadikraman and have been re-testing updating the same project to reanimated version 3.3.0 on react-native version 0.71.11

reanimated 3.3.0 still has the same issue as was originally reported.

However, following the suggestion from @bfricka it appears that the following patch resolved the issue (at least from my initial testing) 👏 .

@piaskowyk @tomekzaw sorry to drag you into this issue, but are you aware of any issues with this approach, or do you have any suggestions for a better approach? I can clean up the patch and open a PR if you agree this is a suitable solution 🙇 

```patch
diff --git a/node_modules/react-native-reanimated/android/src/main/java/com/swmansion/reanimated/layoutReanimation/AnimationsManager.java b/node_modules/react-native-reanimated/android/src/main/java/com/swmansion/reanimated/layoutReanimation/AnimationsManager.java
index 9e54a86..87144b0 100644
--- a/node_modules/react-native-reanimated/android/src/main/java/com/swmansion/reanimated/layoutReanimation/AnimationsManager.java
+++ b/node_modules/react-native-reanimated/android/src/main/java/com/swmansion/reanimated/layoutReanimation/AnimationsManager.java
@@ -477,7 +477,12 @@ public class AnimationsManager implements ViewHierarchyObserver {
     int tag = view.getId();
     ViewManager viewManager = resolveViewManager(tag);
 
-    if (viewManager != null && viewManager.getName().equals("RNSScreenStack")) {
+    if (
+      viewManager != null && (
+      viewManager.getName().equals("RCTModalHostView") ||
+      viewManager.getName().equals("RNSScreen") ||
+      viewManager.getName().equals("RNSScreenStack")
+    )) {
       cancelAnimationsRecursive(view);
       return false;
     }
```

**Comment by bfricka** [comment]
@robwalkerco The one difference w/ your patch vs mine is that I changed `cancelAnimationsRecursive` to `cancelAnimationsInSubviews`. The latter calls the former, but also clears the animation configs. I was worried that without this, we might have memory leaks, since `ReaLayoutAnimator#deleteView` (the method that eventually causes `removeOrAnimateExitRecursive` to be called) calls `cancelAnimationsInSubviews` when it short circuits.

I'm not sure if this is necessary, although, in my testing, I didn't find any issues at the very least. This is why I was hoping for some feedback from the maintainers.

**Comment by bfricka** [comment]
> Is the fix that was just merged / released specific to modals? I know it was mentioned that this was an issue not only with modals but also with unmounting screens with exit animations.

@justinadkins The person who created the PR seems to have just copied my patch, so everything should be covered.

**Comment by kadikraman** [comment]
> > Is the fix that was just merged / released specific to modals? I know it was mentioned that this was an issue not only with modals but also with unmounting screens with exit animations.
> 
> @justinadkins The person who created the PR seems to have just copied my patch, so everything should be covered.

She sure did! I linked it to this ticket, I just realised I didn't explicitly give you credit for the solution, so I'll edit my PR description now!
We've been using this fix with patch-package and it's been working fine so we just wanted to get off the patch and I hoped raising it as a PR would speed things up, which it did :)

**Comment by bfricka** [comment]
@kadikraman Thanks for getting it out there quickly!
