### ISSUE TITLE
Worklets cannot be used in the worklet function declared before them

### ISSUE THREAD

**Issue by MatiPl01** [software-mansion/react-native-reanimated#4509]
### Description

When writing more complex animation using multiple worklets, I've noticed that worklet functions must be declared before they are used. It seems that worklets are copied to the UI thread in the same order that they are declared in the JS code, and thus, if I try to use a worklet function before its declaration appears in code, it is `undefined` and I get the following error:
```
ReanimatedError: undefined is not a function, js engine: reanimated
```

### Code examples
Examples below show only the order of worklet functions. In both cases, I call `runOnJS` with the `rotate` worklet function (`runOnUI(rotate)(rotation)`).

#### ✅ Example of code that works
`updateRotation` worklet is declared before `rotate` worklet, so it can be used inside the `rotate` worklet function
```ts
function updateRotation(rotation: SharedValue<number>) {
  'worklet';
  rotation.value += 1;
}

function rotate(rotation: SharedValue<number>) {
  'worklet';
  updateRotation(rotation);
  return {
    transform: [{rotate: `${rotation.value}deg`}],
  };
}
```

#### ❌ Example of code that doesn't work
`updateRotation` worklet is declared after `rotate` worklet, so it is not visible in the `rotate` worklet function body and is `undefined`
```ts
function rotate(rotation: SharedValue<number>) {
  'worklet';
  updateRotation(rotation);
  return {
    transform: [{rotate: `${rotation.value}deg`}],
  };
}

function updateRotation(rotation: SharedValue<number>) {
  'worklet';
  rotation.value += 1;
}
```

### Caveat
Code works properly when executed on the JS thread. Replacing the `runOnUI(rotate)(rotation)` with `rotate(rotation)` removes the issue but runs code on the JS thread which isn't what I need.

This example has only demonstration purpose. The same issue is related to Reanimated hooks that use worklets. I need to use the `useFrameCallback` hook in my project and it causes the same error.

### Steps to reproduce

1. Clone the repository linked in the description
2. Switch to the `worklets` branch using `git switch worklets` command
3. Install dependencies using `yarn` and run the app
4. You will notice that if you try to execute the `rotate` worklet on the UI thread, you will get the described error

### Snack or a link to a repository

https://github.com/MatiPl01/reanimated-issues/tree/worklets

### Reanimated version

3.2.0

### React Native version

0.71.8

### Platforms

Android, iOS

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by tjzel** [comment]
This is a known issue/pitfall to the team. Due to how the Reanimated Babel plugin works, there might be issues with hoisting in general. Your function declaration is hoisted and available in JavaScript, but our plugin appends some properties to the function (it actually creates a brand new function with new properties) which are not getting hoisted, since value assignments are not hoisted in JavaScript. These properties are mandatory for the function to be callable on the UI thread.

We have debated for a long time about this behavior, and ultimately decided not to change it for now, as solutions for it would require very extensive changes. Instead, we are planning to add proper information about this in our new documentation.

Regrettably, there is nothing else you can do but avoid hoisting worklet functions if it's not necessary.
