### ISSUE TITLE
ScrollTo does not work on reanimated ScrollView

### ISSUE THREAD

**Issue by jacobarvidsson** [software-mansion/react-native-reanimated#452]
When using scrollTo on a reanimated ScrollView ref, an error is thrown: "TypeError: node.scrollTo is not a function". I have reproduced it in a snack:

https://snack.expo.io/@jacobarvidsson/2c7078

```javascript
const App = () => {
  const scrollViewRef = useRef(null);
  useEffect(() => {
    if (scrollViewRef.current) {
      const node = scrollViewRef.current;
      if (node) {
        node.scrollTo({ x: 0, y: 0 });
      }
    }
  }, [])
    return (
      <View style={styles.container}>
        <Animated.ScrollView ref={scrollViewRef}>
          <Text>Test</Text>
        </Animated.ScrollView>
      </View>
    );
};
```

**Comment by emzet93** [comment]
I'm facing the same issue. @jacobarvidsson did you find any workaround for this?

**Comment by jacobarvidsson** [comment]
@emzet93 The workaround works, thanks! Obviously better if the animated component would forward the ref of the actual component, so leaving this open for now.

**Comment by nhuesmann** [comment]
@emzet93 Thanks for posting your solution, it worked for me too.

**Comment by yairopro** [comment]
I opened a PR that would solve this issue.

**Comment by co2nut** [comment]
Have you guys tried with  renderScrollComponent inside FlatList? It seems to be not working. 

Will get error  TypeError:null is not an object( 'reffVar.current.geNode' )

![image](https://user-images.githubusercontent.com/4594000/82640604-76e6d980-9c3d-11ea-927a-d24ce91cf184.png)

**Comment by amanmanhas** [comment]
Hi guys, you can solved it by using the **getNode()** method

There are two ways to solve this issue.-
1)If you are using the new recommended way to create a ref to a component since React 16.3 is to use React.createRef() then you will use in this way:-

scrollView = React.createRef();
<Animated.ScrollView
  ref={this.scrollViewRef}/>
  this.scrollViewRef.current.getNode().scrollTo({x: number, y: number, animated: true|false})

2) If you are using the previous way to create a ref before React 16.3 then you will use in this way:-

<Animated.ScrollView
  ref={c => (this.myRef = c)}/>
  this.myRef.getNode().scrollTo({
    y: 0,
    animated: true,
  });


The difference between the above two solution is , in one you can get the getNode() method inside the *current* and the other you can access it without current
