### ISSUE TITLE
boolean nodes don't support boolean types.

### ISSUE THREAD

**Issue by euroclydon37** [software-mansion/react-native-reanimated#470]
I just implemented some animations in JS and I was able to use JS booleans as values passed into `and` and `or`. But when writing the same logic in TS, I'm told I'm supposed to use `Adaptable<number>`. Am I doing something wrong or should the type definition be updated?

**Comment by jakub-gonet** [comment]
Hey @euroclydon37,
nodes like `eq`, `neq`, `greaterThan`, etc return 0 or 1, so we use numbers for signaling output value throughout the entire reanimated.

Using boolean values in some nodes and not in the others potentially could be confusing, so we are using one convention.

Using booleans in JS worked because true evaluates to `truthy` value just like `1`, a `false` to falsy value like `0`

I hope this resolves your question and if not, don't hesitate to ask
