### ISSUE TITLE
useAnimatedReaction previous result is empty

### ISSUE THREAD

**Issue by Amurmurmur** [software-mansion/react-native-reanimated#4796]
### Description

The same exact code with no changes at all works fine on v2 and breaks in v3.
```
  useAnimatedReaction(
    () => {
      return path;
    },
    (result, previous) => {
      if (previous) {
        transition.value = 0;
        transition.value = withTiming(1);
      }
    },
    [path]
  );
```

As a temp fix I basically rely only on `result` variable since previous is always null however when using reanimated v2 it is returning the correct value.

### Steps to reproduce

1. clone the repo
2. yarn install
3. cd ./example && yarn install
4. yarn run ios
5. go to line chart switch between Data 1 and Data 2 the chart will bug out and will not animate properly between different data sets

### Snack or a link to a repository

https://github.com/coinjar/react-native-wagmi-charts

### Reanimated version

3.3.0

### React Native version

0.72.3

### Platforms

Android, iOS

### JavaScript runtime

Hermes

### Workflow

Expo managed workflow

### Architecture

Paper (Old Architecture)

### Build type

Debug mode

### Device

iOS simulator

### Acknowledgements

Yes

**Comment by Emz27** [comment]
I had the same issue before, my workaround was to remove the dependencies of the useAnimatedReaction, keep it empty array because I think what happened is that the hook values resetted everytime the component update, the previous value is always null after component update. Good news is that it is not happening anymore in reanimated 3.4.0 nightly builds.

You can apply the same workaround while waiting for 3.4.0 release by making your path a sharedValue and remove the dependencies of useAnimatedReaction

```
const path = useSharedValue(0)
useAnimatedReaction(
	() => path.value,
	(result, previous) => {
		if (previous) {
			transition.value = 0;
			transition.value = withTiming(1);
		}
	},
	[],
);

```

or you can use the useEffect hook if you don't want to make it a sharedValue

```
useEffect(
	() => {
		if (path) {
// watchout for unmount calls
			return () => {
				transition.value = 0;
				transition.value = withTiming(1);
			}
		}
	},
	[path],
);
```

**Comment by tjzel** [comment]
Hi @Amurmurmur. Could you also post a link to - preferably a branch - of your repo that has Reanimated upgraded from 2 to 3? I want to be sure we are on the same page when dealing with this issue.
