### ISSUE TITLE
[v8] Reanimated setupMicrotask UI thread worklet pollutes JS thread's global and overrides native queueMicrotask, breaking all animations

### ISSUE THREAD

**Issue by DrRefactor** [software-mansion/react-native-reanimated#4953]
### Description

setupMicrotask overrides default native global.queueMicrotask, but I think it was supposed to do this only in scope of UI thread. However, it also overrides this method on JS thread, fully breaking reanimated - none of queued microtasks on JS thread is run, ever.

This only happens when using v8 engine. While using Hermes, global.queueMicrotask is not overriden on JS thread.

### Steps to reproduce

1. Use v8 as a JS engine.
2. Observe broken reanimated shared value updates / animations.

Minimal reproduction repo will be provided soon.

### Snack or a link to a repository

Minimum reproduction repo:
https://github.com/DrRefactor/reanimated-v8-issue-4953-reproduction/blob/main/App.tsx

Provided workaround, change USE_WORKAROUND to true to enable it. Workaround creates a reference to global.queueMicrotasks on JS thread, thus preventing overriding it. UI thread's implementation overrides properly. Animations work again.

Observe console.log:
`global.queueMicrotask= [Function anonymous]` means global.queueMicrotasks overriden by reanimated setupMicrotasks
`global.queueMicrotask= [Function queueMicrotask]` means it's a deafult native implementation

### Reanimated version

3.4.2

### React Native version

0.71.12

### Platforms

Android

### JavaScript runtime

V8

### Workflow

React Native (without Expo)

### Architecture

Paper (Old Architecture)

### Build type

None

### Device

Android emulator

### Device model

Android TV emulator, android mobile emulator

### Acknowledgements

Yes

**Comment by DrRefactor** [comment]
Provided minimal reproduction repo link.

**Comment by DrRefactor** [comment]
@Kudo could you take a look? Maybe this issue comes from react-native-v8?

**Comment by DrRefactor** [comment]
Thanks for info. Is there any v8 issue to track?

**Comment by piaskowyk** [comment]
I think not yet, but I am sure that it will appear in the V8 repository

**Comment by Kudo** [comment]
hi there! thanks for the heads-up and great repro.
the behavior is somehow by design. when introducing the `rnv8::createSharedV8Runtime()`, i [share the app runtime's global prototype to newer (worklet) runtime](https://github.com/Kudo/react-native-v8/blob/b5ce9d8344ee2abc9e7c1ea82281ba7d6a5ad511/src/v8runtime/V8Runtime.cpp#L104-L114). that would open much more possibility for reducing complexity from reanimated's shared value implementation.

i didn't expect the override use case. given reanimated does not use the "shared prototype" design and just introduce issues like this, maybe i could make the "shared prototype" configurable and disable it by default.
does it make sense to you? @piaskowyk @tomekzaw

**Comment by tomekzaw** [comment]
Hey @Kudo, thanks for your response.

> given reanimated does not use the "shared prototype" design

Indeed, Reanimated assumes that the global objects are separate. For instance, we inject our own `requestAnimationFrame` into the UI runtime but we certainly don't want to do this for the RN runtime. 

> i could make the "shared prototype" configurable and disable it by default.

I believe this would resolve this issue 🙏
