### ISSUE TITLE
Race condition between JS and UI threads

### ISSUE THREAD

**Issue by yolpsoftware** [software-mansion/react-native-reanimated#4978]
### Description

Please see the repository here:

https://github.com/yolpsoftware/rea-3-bugrepro-838

The README contains a description of the problem.

I'm not sure if this is a bug. However, I have asked in the [forums](https://forums.expo.dev/t/how-to-sync-between-a-render-and-a-reanimated-animation-variables-update/72725) and on [Stackoverflow with a bounty](https://stackoverflow.com/questions/76876088/how-to-sync-rendering-with-react-native-reanimated-variable-updates), and haven't yet got an answer. It seems to be a race condition between the JS and the UI thread, and I have not found any hints in the docs about how to sync them.

### Steps to reproduce

1. Run the repository https://github.com/yolpsoftware/rea-3-bugrepro-838

### Snack or a link to a repository

https://github.com/yolpsoftware/rea-3-bugrepro-838

### Reanimated version

3.3.0

### React Native version

0.72.4

### Platforms

iOS

### JavaScript runtime

Hermes

### Workflow

Expo managed workflow

### Architecture

Paper (Old Architecture)

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by bglgwyng** [comment]
I think we have the same problem. Once I posted the same issue and I just uploaded the video of reproducing it.
https://github.com/software-mansion/react-native-reanimated/issues/4446#issuecomment-1810197536
I'm so disappointed that your post in the forum got no answer. I think this behavior clearly is a bug, so it's hard to understand it not getting attention. Do you know any update on it?

**Comment by yolpsoftware** [comment]
We changed a few things to solve it. I think the main change was `useLayoutEffect` instead of `useEffect`.

**Comment by bglgwyng** [comment]
My example also uses `useLayoutEffect`. But it doesn't solve the problem. Did it work for your case?

**Comment by kmagiera** [comment]
Thanks for reporting @yolpsoftware and for your comments @bglgwyng – It's great you put effort in preparing the repo. I managed to run it and reproduce the problem locally. Since we recently worked on a different issue revolving around render race condition I figured it'd test this with the newest version of reanimated. It appears that when running with Reanimated 3.6.1 the problem no longer occurs. It is likely that this PR have fixed your problem too: https://github.com/software-mansion/react-native-reanimated/pull/5224

Would be great if you could verify that on your end before we close the issue. Thanks!

**Comment by yolpsoftware** [comment]
Seems this is again a problem in Reanimated 3.7 and upwards. We had to revert to Expo 50.

See also #5816.

**Comment by yolpsoftware** [comment]
Filed a new bug, since this one is closed already: #6083

**Comment by yolpsoftware** [comment]
@kmagiera this seems to have regressed.

Filed a new bug, since this one is closed already: #6083
