### ISSUE TITLE
Confusing error when passing animated style to a non-animated component

### ISSUE THREAD

**Issue by gaearon** [software-mansion/react-native-reanimated#5117]
### Description

Suppose I have this.

```js
  const animatedStyle = useAnimatedStyle(() => {
    return {
      // ...
    }
  })
 return <Image style={[animatedStyle]} />
```

I get an error that's very difficult to understand. It doesn't give me any information that would hint at what actually went wrong. It says `Reading from _value directly is only possible on the UI runtime` but I don't know what `_value` is, and I definitely don't read it directly myself. And the stack frame it shows doesn't even have `_value` access.

<img width="423" alt="Screenshot 2023-09-21 at 19 06 57" src="https://github.com/software-mansion/react-native-reanimated/assets/810438/6d42bf8f-ccfc-4269-bbfc-8228497da9ee">

The problem with the code above is that I forgot to do `Animated.createAnimatedComponent(Image)`.

I'd like the error message to be clearer if possible — at least in development.

### Steps to reproduce

see above

### Snack or a link to a repository

sorry

### Reanimated version

3.4.2

### React Native version

0.72.4

### Platforms

Android

### JavaScript runtime

Hermes

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by tjzel** [comment]
While I agree that given error is not very descriptive, I'm afraid we can't do much better without extensive changes in our logic.

`useAnimatedStyle` is (in big oversimplification) just a wrapper for underlying Shared Values and the reason for this error to happen isn't actually because of use of `useAnimatedStyle` in a non-animated component, but the non-animated component trying to access those wrapped Shared Values.

Note that this error can happen in many different scenarios, not only when appending Animated Styles to non-animated components. Basically, every misuse of a Shared Value (or `mutable` to be more specific) would cause it. Since we cannot really check in what context the misuse happened, it's hard to give a meaningful runtime error here - while we could potentially guard `useAnimatedStyle` with some `getter` shenanigans, we'd also need to do the same for inline usage of Shared Values etc.

What we could do is add this to our Troubleshooting section and point out common reasons for this to happen and link it in the error - I guess this is better than nothing, but I'm not certain if it's a scalable solution.

**Comment by gaearon** [comment]
I think adding a link and documenting a few common causes (as well as a technical description of what happened) would go a long way!

**Comment by gaearon** [comment]
On a side note, it would _really_ help to have an architectural overview page that talks about how the whole thing works in simplified terms.

**Comment by mannyuiux** [comment]
@gaearon @tjzel , I faced the similar issue and after read your comment[comment](https://github.com/software-mansion/react-native-reanimated/issues/5117#issuecomment-1731078717) I realised that I commented the line inside `Animated.View` and left it empty was causing the issue. 

<img width="782" alt="image" src="https://github.com/software-mansion/react-native-reanimated/assets/13067741/87fc848f-6614-486f-9124-29d85c6775b4">

**Comment by rahulnainwalttn** [comment]
Facing similar issue with react-native 0.83. [#2743](https://github.com/PostHog/posthog-js/issues/2743#issuecomment-3660706535)
