### ISSUE TITLE
Android and iOS build is getting crashed while making release builds

### ISSUE THREAD

**Issue by import-yuv** [software-mansion/react-native-reanimated#5138]
### Description

<img width="891" alt="image" src="https://github.com/software-mansion/react-native-reanimated/assets/53913163/be28ec0b-f144-419c-9de5-8c64edb41e92">

Context: 
I'm upgrading React Native from 0.71 to 0.72.3, and I've upgraded `react-native-reanimated` from 2.14.1 to 3.4.1, as well as several libraries such as react-native-screens, react-native-tab-view, lottie-react-native, @react-native-async-storage/async-storage, and react-native-notifications.

The following are the libraries that are utilised in the project:
```
 "react-native": "0.72.3",
 "react-native-reanimated": "3.4.1"
 "react-native-screens": "3.23.0",
 "styled-components": "5.3.5",
 "react-native-tab-view": "3.1.1",
 "react-native-gesture-handler": "2.9.0",
 "@react-navigation/bottom-tabs": "6.5.7",
 "@react-navigation/native": "6.1.6",
 "@react-navigation/stack": "6.3.16",
 "react-native-notifications": "5.1.0",
 "lottie-react-native": "5.1.6",
```

Here is the metro.config.js

```
const { getDefaultConfig, mergeConfig } = require('@react-native/metro-config');

/**
 * Metro configuration
 * https://facebook.github.io/metro/docs/configuration
 *
 * @type {import('metro-config').MetroConfig}
 */
const config = {
  resetCache: true,
  transformer: {
    getTransformOptions: async () => ({
      transform: {
        experimentalImportSupport: false,
        inlineRequires: false,
      },
    }),
  },
};

module.exports = mergeConfig(getDefaultConfig(__dirname), config);
```
While running the app in development, there is no problem; however, when I try to make the release builds, the app crashes on both Android and iOS.

The error logs are as follows:
```
Fatal Exception: RCTFatalException: Unhandled JS Exception: Error: [Reanimated] Using dev bundle in a release app build is not supported. Visit https://github.com/software-mansion/react-native-reanimated/issues/4737 to find more information on how to fix this issue., js engine: hermes
0  CoreFoundation                 0x9e38 __exceptionPreprocess
1  libobjc.A.dylib                0x178d8 objc_exception_throw

```

### Steps to reproduce

1. This error can be reproduced while upgrading react native to 0.72.3 and react-native-reanimated from v2 to v3.
2. The error will come when you try to build the release builds.

### Snack or a link to a repository

https://snack.expo.dev/

### Reanimated version

3.4.1

### React Native version

0.72.3

### Platforms

Android, iOS

### JavaScript runtime

Hermes

### Workflow

React Native

### Architecture

None

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by tjzel** [comment]
Hi @import-yuv. Have you checked the link with more information provided in error message?

**Comment by import-yuv** [comment]
@tjzel yes have checked [this](https://github.com/software-mansion/react-native-reanimated/issues/4737) link and tried all the methods but it didn't work.

**Comment by ayyam** [comment]
is the below error related 
> Task :react-native-gesture-handler:configureCMakeRelWithDebInfo[arm64-v8a]
C/C++: CMake Warning:
C/C++:   Manually-specified variables were not used by the project:
C/C++:     APP_BUILD_DIR

> Task :react-native-reanimated:buildCMakeRelWithDebInfo[armeabi-v7a] FAILED
C/C++: ninja: error: manifest 'build.ninja' still dirty after 100 tries

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-reanimated:buildCMakeRelWithDebInfo[armeabi-v7a]'.
> com.android.ide.common.process.ProcessException: ninja: Entering directory ? 
 any one faced above issue?

**Comment by Souvik-Maity-au6** [comment]
> Is the below error related
> 
> > Task :react-native-gesture-handler:configureCMakeRelWithDebInfo[arm64-v8a]
> > C/C++: CMake Warning:
> > C/C++:   Manually-specified variables were not used by the project:
> > C/C++:     APP_BUILD_DIR
> 
> > Task :react-native-reanimated:buildCMakeRelWithDebInfo[armeabi-v7a] FAILED
> > C/C++: ninja: error: manifest 'build. ninja' still dirty after 100 tries
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
>   Execution failed for task ':react-native-reanimated:buildCMakeRelWithDebInfo[armeabi-v7a]'.
> 
> > com.android.ide.common.process.ProcessException: ninja: Entering directory?
> > any anyone faced the above issue?

yes facing the same issue with the latest react-native-reanimated

**Comment by derek-primumco** [comment]
Has anyone tried it on [the @latest release 3.5.4](https://github.com/software-mansion/react-native-reanimated/releases)? 

Here are the notes for [3.5.2](https://github.com/software-mansion/react-native-reanimated/releases/tag/3.5.2):

> Fixing crash on Release mode with https://github.com/software-mansion/react-native-reanimated/pull/5087 (bug introduced in https://github.com/software-mansion/react-native-reanimated/pull/4794).

**Comment by derek-primumco** [comment]
Unfortunately, I couldn't reproduce this crash with `yarn create expo-app RNR -e with-reanimated` (Expo SDK 49, react-native-reanimated 3.3.0).

I tested Expo Go (the default) and switching to a development build (pressing `s` in Metro bundler); both worked with the following steps.

First, I needed to add the bundle identifier to `app.json` to be able to try out the development build and not just Expo Go:
```
  "expo": {
    "ios": {
      "bundleIdentifier": "com.RNR",
    },
  }
```

Then these are the exact steps I tested.
1. `yarn expo run:ios`
2. Press `Control+C` to quit Metro.
3. `yarn expo start --no-dev --minify`
4. Press `i` to launch iOS in Expo Go.
5. Test the app in the iOS Simulator, then force-quit it.
6. Press `s` to switch to Expo development build.
7. Press `i` to launch iOS in Expo Go. 
8. Test the app in the iOS Simulator, then force-quit it.
9. Upgrade to 3.5.4 with `yarn add react-native-reanimated`.
10. `rm -rf ios && yarn expo run:ios`
11. Press `Control+C` to quit Metro.
12. `yarn expo start -c --no-dev --minify`
13. Press `i` to launch iOS in Expo Go.
14. Test the app in the iOS Simulator, then force-quit it.
15. Press `s` to switch to Expo development build.
16. Press `i` to launch iOS in Expo Go. 
17. Test the app in the iOS Simulator, then force-quit it.

Anyway, I wanted to share these debugging instructions in case they help anyone else. 

I found that by experimenting with `yarn && yarn expo start -c --no-dev --minify` and the `s` key to switch to Expo Go, I was able to see an error (`unable to read properties of undefined`) that wasn't otherwise appearing. 

By swapping that section of the code from `window.location.hostname` to `window?.location?.hostname` suppressed the error, and now the app runs in production mode again.

**Comment by GustavoBonfimS** [comment]
Same error for me using `expo run:android --variant Release` or `gradlew assembleRelease`

**Comment by piaskowyk** [comment]
'[Reanimated] Using dev bundle in a release app build is not supported.' - We solved this issue in version 3.6.1

**Comment by TechSaq** [comment]
> is the below error related
> 
> > Task :react-native-gesture-handler:configureCMakeRelWithDebInfo[arm64-v8a]
> > C/C++: CMake Warning:
> > C/C++:   Manually-specified variables were not used by the project:
> > C/C++:     APP_BUILD_DIR
> 
> > Task :react-native-reanimated:buildCMakeRelWithDebInfo[armeabi-v7a] FAILED
> > C/C++: ninja: error: manifest 'build.ninja' still dirty after 100 tries
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
>   Execution failed for task ':react-native-reanimated:buildCMakeRelWithDebInfo[armeabi-v7a]'.
> 
> > com.android.ide.common.process.ProcessException: ninja: Entering directory ?
> > any one faced above issue?

How did you guys solve this issue? I am facing the issue while making release build.

**Comment by TechSaq** [comment]
I have version 3.7

**Comment by mcalc001** [comment]
Hey i think i'm getting this issue still on 3.8.1 on both IOS and Android only in release builds. Impossible to debug as i get no logs whats so ever.

**Comment by tjzel** [comment]
@mcalc001 You can try to use Sentry to catch the crash log.
