### ISSUE TITLE
SWC plugin is broken

### ISSUE THREAD

**Issue by abejfehr** [software-mansion/react-native-reanimated#5174]
### Description

Using a recent version of SWC to transpile typescript for React Native Web, the official `react-native-reanimated-swc-plugin` no longer works, and fails at runtime with an error:

![image](https://github.com/software-mansion/react-native-reanimated/assets/3917428/d2371ba7-0f2b-4742-a8f6-f1f520749020)

While it's possible to use React Native Reanimated without the plugin, it's virtually impossible if you rely on third party libraries that themselves rely on the plugin, like [react-native-bottom-sheet](https://github.com/gorhom/react-native-bottom-sheet).

### Steps to reproduce

1. Have a React Native Web application using webpack and swc-loader
2. Install this plugin, and observe that any page using reanimated seems to break

### Snack or a link to a repository

N/A

### Reanimated version

3.4.2

### React Native version

0.72.4

### Platforms

Web

### JavaScript runtime

V8

### Workflow

React Native

### Architecture

None

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by tjzel** [comment]
Hi @abejfehr. Unfortunately, because there was little interest in the SWC plugin while it's maintenance required more effort than we expected we decided not to develop it any further.

**Comment by MoOx** [comment]
@tjzel I guess you are aware of that but by not supporting SWC, you restrict some Next.js users to rely on you awesome work.

I was trying to use you plugin (required for https://github.com/gorhom/react-native-bottom-sheet) for a web app (that must offer good UX on mobile - and bottom sheet is very relevant in my case), but the problem is, my current setup rely on lots of modern Next.js API (including "next/font") that require SWC compiler, so custom babel config is not an option.

I understand that SWC plugin might be a lot of work but I just wanted to make sure that by doing so (not supporting SWC) you were aware that lots of people using latest Next.js APIs (like next/font and probably some other) will make it impossible to rely on your work.

**Comment by MoOx** [comment]
At least what you could do is to show https://www.npmjs.com/package/react-native-reanimated-swc-plugin as deprecated :(

**Comment by affectful** [comment]
@tjzel hi please mark the swc plugin as deprecated, I was about to try it and probably waste a few hours.

**Comment by tjzel** [comment]
@affectful Done!
