### ISSUE TITLE
Animations do not sanitize their defaults consistently

### ISSUE THREAD

**Issue by ckknight** [software-mansion/react-native-reanimated#52]
https://github.com/kmagiera/react-native-reanimated/blob/a4d6e11902956fe686f119948405641c1493b839/src/animations/backwardCompatibleAnimWrapper.js#L108-L113

If the animation function is called with all three arguments, then `config` never goes through the AnimationClass which provides default values if they are not available.

It seems like there should be a consistent sanitizer function for the config that works the same both ways.

**Comment by osdnk** [comment]
Hi, 
There's few issue, which have to be resolved:
1. https://github.com/kmagiera/react-native-reanimated/blob/a4d6e11902956fe686f119948405641c1493b839/src/animations/SpringAnimation.js#L38 "sanitizer" like this is not enough, because config could be animated node as well and JS arithmetical operation are not fine. At the very begging proof of concept of RNR was done only in JS and then implemented in Java and ObjC. 

2. How about state? I suppose that state should be also "default" if there's not enough fields

**Comment by osdnk** [comment]
Take a look on this case:
We have some node e.g.`const x = add(10, 20)`
Then I wish to use it as `speed` and other node as `bounciness`. 
So it's a bit more complicated:
https://github.com/kmagiera/react-native-reanimated/pull/40/files
I'm preparing this PR and I suppose it will be finished soon

**Comment by ckknight** [comment]
I don't think I ever asked for JS arithmetical operations in this issue. This is about providing defaults if `undefined` is passed in, or if the `state` or `config` objects do not have expected properties, or to support properties like `friction` which are supported in `SpringAnimation` but not `spring`.

**Comment by osdnk** [comment]
Ok, default value is maybe fine for a moment, but I wish to prepare more complex mechanism. 

If it is about spring animation, it's not enough to check if values are present or not, but also they have to be "translated" in order to provide fixed structure to `spring.js`. And this translation can't be done with arithmetical operations in js.

**Comment by ckknight** [comment]
I must have mis-communicated something along the way, because _nothing_ about this issue is related to translation. This is about consistently-handling config objects the same way within:

* `decay` and `DecayAnimation`
* `spring` and `SpringAnimation`
* `timing` and `TimingAnimation`

When calling one of the functions with 3 arguments, the `state` and `config` are passed straight-through and the AnimationClass is avoided entirely. Each AnimationClass observes the `state` and `config`, pulls out pertinent nodes, and handles defaults. `SpringAnimation` also supports `friction`, which is not a standard config for `spring`.

My proposal is _only_ to consistently handle that initialization.

The work within #40 is great for `spring`, and also could be applied to its `state` and also to the `decay` and `timing` functions.

**Comment by osdnk** [comment]
Yes, you are right about the need to handle each case of not-complete config and state. I wish only to point that it's not enough just to add missing value because it's more complicated issue (if it is about spring). I wish to cover issue of missing config and state values in this PR I linked

**Comment by osdnk** [comment]
For now decided to do it like ^^, @ckknight 
Is it what did you mean?
