### ISSUE TITLE
AnimatedProps or derived value bug

### ISSUE THREAD

**Issue by taZik616** [software-mansion/react-native-reanimated#5210]
### Description

Guys, I'm too lazy to collect evidence to present this problem, so I'll describe everything verbally

In the library version 3.5.4, I came across the fact that my component that had been working before stopped working
By lowering the version to 3.4.2, everything became as before

Component preview:
https://github.com/software-mansion/react-native-reanimated/assets/94304770/73873f82-8abf-4b61-804e-3df98b74c308

Code snippets
<img width="430" alt="Снимок экрана 2023-10-10 в 20 15 32" src="https://github.com/software-mansion/react-native-reanimated/assets/94304770/d227ec64-e4f9-4d44-adea-f4aa58099aea">
<img width="511" alt="Снимок экрана 2023-10-10 в 20 17 01" src="https://github.com/software-mansion/react-native-reanimated/assets/94304770/9a7d63f3-436a-43f1-bf93-e03b8bc07539">
<img width="755" alt="Снимок экрана 2023-10-10 в 20 17 51" src="https://github.com/software-mansion/react-native-reanimated/assets/94304770/9e18595c-2282-42ef-b7c7-c8aac3e7e887">

### Steps to reproduce

Use animated props or derived value

### Snack or a link to a repository

no

### Reanimated version

3.5.4

### React Native version

0.71.12

### Platforms

iOS

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Device model

any simulator and real device

### Acknowledgements

Yes

**Comment by tjzel** [comment]
Hi @taZik616. Could explain what exactly stopped working?

**Comment by daonham** [comment]
I got the same error, any solution?

**Comment by almorak** [comment]
may check if the .value is a number or object as I found the animation last frame returns a object/array instead of a number.

**Comment by taZik616** [comment]
> Hi @taZik616. Could explain what exactly stopped working?

Just determine which part could cause this problem, I think I have provided enough information to solve the problem for you. Here you need to experiment and not fall asleep with questions

**Comment by piaskowyk** [comment]
I have no idea what happend 😅 We're just free to use open source project, unfortunately we don't have enough capacity to investigate every issue without cooperation with the author - this is just impossible for us. Sorry for inconvenience 😔

**Comment by Hassaan68** [comment]
@piaskowyk why this is closed?? I am facing the same issue.. Animations are messed up in version 3.5.4 and working fine in version 3.4.2

**Comment by tjzel** [comment]
@Hassaan68 the description of the issue was `had been working before stopped working` without any details about how it worked before or what is the desired behavior.

It takes just a minute for us to ask and then know what to look for if a more extensive description is provided. 
However it takes significantly much more time when I have to build an App on two versions of Reanimated, not even knowing what to look for after that.

We will gladly investigate this issue, but we have to respect our time since it's limited. We asked for more details and the author of the issue committed his time to say he won't provide them. This indicates to me that the issue should be closed since the author is not cooperating and the problem is still not defined.

If you would explain what exactly is broken I'm more than happy to reopen this issue.
