### ISSUE TITLE
Declarative animations (aka Reanimated v1)

### ISSUE THREAD

**Issue by wcandillon** [software-mansion/react-native-reanimated#5307]
### Description

With React Native Skia, we are building all of our animations using Reanimated.
Our current perspective on it is that a Skia Drawings are no different than any component.
Following this principle has been really good to us so far. 

Now there is a slight difference between Skia components and "regular" RN components: we can easily animate thousands of drawing commands. This can means thousands of mappers for a relatively simple animation. This should be the case for React Native SVG as well.

At this level, we start to see a performance hit (especially on low-end Android devices) in compare to the same drawing animation but with a single mapper.
Now the pattern is always the same: one value (a gesture position or a progress animation) animates thousands of drawing commands but we need a slight derivation for each drawing command (for instance calculating a very simple transformation based on the position of the element we animate).
For such scenario, I am wondering if we could have only have one mapper and another primitive that would allow us to calculate the derived value still. Maybe something a bit more declarative like in v1 but maybe there are some other approach we can do to prototype.

It should be noted that we have a great workaround for such scenario but of course we are wondering if Reanimated could offer something there to improve the developer experience there.

### Steps to reproduce

There are two examples that follow the pattern described above (one value drives thousands of trivial yet independent derived values):
Digital Rain Effect: https://github.com/Shopify/react-native-skia/blob/main/example/src/Examples/Matrix/Matrix.tsx
Small performance benchmark: https://github.com/Shopify/react-native-skia/blob/main/example/src/Examples/Performance/PerformanceRects.tsx

### Snack or a link to a repository

https://github.com/Shopify/react-native-skia

### Reanimated version

3.5.4

### React Native version

0.72

### Platforms

Android, iOS

### JavaScript runtime

Hermes

### Workflow

React Native

### Architecture

Paper (Old Architecture)

### Build type

Debug mode

### Device

Real device

### Device model

Pixel 4

### Acknowledgements

Yes

**Comment by kmagiera** [comment]
Thanks for starting this discussion @wcandillon 

In general I'm not opposed to any changes or ideas regarding the API, especially if this was to benefit the library users.

I think, however, that an alternative approach to addressing this issue should be consider here as well. And by that I mean that instead of introducing a new abstraction, we could try to find a way of improving the current one. Below I wanted to add a bit of context from some of the attempts and testing we've done in the past which should shade some light on why I think there is a lot of potential for improvements:

Outside of the context of skia, a while back we've been working on improving performance of similar examples, where you have hundred of UI elements being animated all at once. We even have [some examples in the codebase](https://github.com/software-mansion/react-native-reanimated/blob/main/app/src/examples/BokehExample.tsx) already. Eventually, the conclusions that we reached was that the bottleneck wasn't on the Reanimated side but rather in the UIManager code responsible for handling parameter updates. This makes me believe that a different API wouldn't really impact the outcome this much if it still ends up interfacing with react native internals in the same way we do now. However, this isn't necessarily the case for Reanimated + Skia. With React Native we use `updateProps` method to apply the updates  to the native views, while in Skia this flow is different as we communicate with JsiDomNode via [`setProp`](https://github.com/Shopify/react-native-skia/blob/main/package/cpp/rnskia/dom/base/JsiDomNode.h#L105) method. 

Given the above I see two potential vectors for improving the current situation:
1) Given we use [`setProp`](https://github.com/Shopify/react-native-skia/blob/main/package/cpp/rnskia/dom/base/JsiDomNode.h#L105) for every single prop that we update, it is likely not optimal, as from what I understand it does perform a tree-wide updates multiple times as opposed to doing it only once per frame. I think by optimizing this bit we should be able to better support animations where tons of nodes are being updated at the same time
2) A consequence of the bottleneck that we discovered in updating native props, we decided to stop investigating further improvements on the reanimated side as they'd have a limited impact on the performance of handling hundreds of views. This doesn't need to be the case for Skia, and if that's the case we can resume this work if we have a clear goal. There are plenty of ideas we have already explored to some extent, like for example moving some of the processing logic to c++ for performance reasons, so I'm pretty optimistic that we could get some significant wins there.

**Comment by wcandillon** [comment]
This is very interesting information.
The benchmark that I ran was 450 mappers vs 1 (low-end device, debug mode) but didn't consider the overhead on Skia side (setProp).
I think the next step will be to prototype an adhoc way to derive/update the value without using an extra mapper to see what kind of performance we get.

This also seems to suggest that using shadow nodes may have a performance overhead if they were to be used for Skia. But here also I will run more benchmarks (comparings vs 450 views, 450 svgs) etc.

I will close this for now and reopen it maybe if I have more compelling data to share.

**Comment by wcandillon** [comment]
After doing more testing, I am able to measure that the overhead is "only" on the number of mapper. We have an example with a single mapper and 450 setprops per frame and it is much faster than the same example with 450 mappers.

We will see if we can prototype something where we have a "declarative" derived value. We will keep you posted.

**Comment by wcandillon** [comment]
We're currently looking at a way to update tousands of properties using a single mapper.
This one of the design we are exploring:
```tsx
const values = useDerivedValues(() => {
  return rects.map(() => {
    const p1 = { x: rct.x, y: rct.y };
    const p2 = pos.value;
    const r = Math.atan2(p2.y - p1.y, p2.x - p1.x);
    return [{ rotate: r }];
  });
});
return (
	<Group>
    {
      rects.map((rect, index) => {
        // Here we have single mapper (values) but we will still be able to update
        // the transform props. Benchmarking has shown us that this would be ok
        return <Rect rect={rect} key={index} transform={select(values, index)} />
      })
    }
    </Group>
)
```
