### ISSUE TITLE
[Shared Element] text or view that is inside the view transition not working

### ISSUE THREAD

**Issue by kicaal** [software-mansion/react-native-reanimated#5336]
Shared element transition with Animated.Text or Animated.View (as wrapper around Text) component does not work. The wrapper itself does work (please see border). I am trying to transition an emoji. I believe it might be because there is no support for Text transition yet based on: https://github.com/software-mansion/react-native-reanimated/issues/4990.

Whether it is an issue or a feature request I will let you decide as I lack context. Would be much appreciated if you could point me in the direction of a solution or alternatively let me know whether there will be support for it in the future.

Right now my only option is to go with the react-navigation-shared-element package which is no longer maintained 😶‍🌫️ so my colleagues are not fund of me 😩       

https://github.com/software-mansion/react-native-reanimated/assets/40881553/f427e2b5-5a0a-4a04-a0d3-811102a7f965

_Originally posted by @kicaal in https://github.com/software-mansion/react-native-reanimated/issues/5212#issuecomment-1789315930_

**Comment by tomekzaw** [comment]
@kicaal You should have two `Animated.Text` components with "Buscar destinos" which share the same `sharedTransitionTag`, do you have two or just one?

**Comment by kicaal** [comment]
Hello! I'm sorry for taking so long to reply! I have two, one at the beginning and the other at the destination.

**Comment by kmagiera** [comment]
Hi @kicaal – thanks for submitting the issue. I can clearly see that something is off based on video, but without a sample code it'd be difficult for us to investigate. Given you have this issue it'd be great if you could distill a small reproducible demo of this issue. Otherwise we could only start guessing on how the code is structured (what @tomekzaw tried when asking about whether there are two Animated.Text components), or even when we get it to reproduce similar issue it may end up being something that won't help in your usecase.

Going forward, we ask you to include a code snippet with reproducible demo. It doesn't have to be a full repo, just one js/ts file with all necessary components and styles that'd allow us to see replicate this bug. Thanks!

**Comment by mgltopdk** [comment]
This has been open even longer: https://github.com/software-mansion/react-native-reanimated/issues/5212. There is a code snipset there.
