### ISSUE TITLE
Single frame delay on Android between Native, SVG, and Skia

### ISSUE THREAD

**Issue by wcandillon** [software-mansion/react-native-reanimated#5341]
### Description

On Android, when animating SVG and Skia, it looks like there is always a one frame delay between the native view and the canvas view (SVG or Skia). The issue on iOS seems to be reproducible if there is more pressure put on the app.

Not sure if this is on issue with Reanimated or with SVG and Skia.

Below is an example with React Native SVG:
```tsx twoslash
import React, { useEffect } from "react";
import { StyleSheet, View } from "react-native";
import Animated, {
  useAnimatedStyle,
  useAnimatedProps,
  withRepeat,
  withTiming,
  Easing,
  cancelAnimation,
  useSharedValue,
} from "react-native-reanimated";
import { Svg, G, Rect as SvgRect } from "react-native-svg";

const AnimatedG = Animated.createAnimatedComponent(G);

const array = new Array(1).fill(0).map((_, index) => index);

export const useLoop = ({ duration }: { duration: number }) => {
  const progress = useSharedValue(0);
  useEffect(() => {
    progress.value = withRepeat(
      withTiming(1, { duration, easing: Easing.linear }),
      -1,
      true
    );
    return () => {
      cancelAnimation(progress);
    };
  }, [duration, progress]);
  return progress;
};

export default function App() {
  const clock = useLoop({ duration: 3000 });
  const animatedProps = useAnimatedProps(() => ({
    translate: `0, ${300 + clock.value * 300 - 300}`,
  }));
  const style = useAnimatedStyle(() => ({
    ...StyleSheet.absoluteFillObject,
    transform: [{ translateY: 300 + clock.value * 300 - 300 }],
  }));
  return (
    <View
      style={{
        flex: 1,
        flexDirection: "row",
      }}
    >
      <View style={{ flex: 1 }}>
        <Animated.View style={style}>
          {array.map((index) => (
            <View
              key={index}
              style={{
                position: "absolute",
                top: 150 * index + 50,
                left: 15,
                width: 100,
                height: 100,
                backgroundColor: "blue",
              }}
            />
          ))}
        </Animated.View>
      </View>
      <Svg style={StyleSheet.absoluteFill}>
        <AnimatedG animatedProps={animatedProps}>
          {array.map((index) => (
            <SvgRect
              key={index}
              x={15}
              y={150 * index + 50}
              width={100}
              height={100}
              fill="red"
            />
          ))}
        </AnimatedG>
      </Svg>
    </View>
  );
}
```

We also have the same behaviour with Skia:
```tsx
import {
  Canvas,
  Group,
  Rect,
  Skia,
  useClock,
} from "@shopify/react-native-skia";
import React from "react";
import { StyleSheet, View } from "react-native";
import Animated, {
  useAnimatedStyle,
  useDerivedValue,
} from "react-native-reanimated";

const array = new Array(1).fill(0).map((_, index) => index);
const paint = Skia.Paint();
paint.setColor(Skia.Color("pink"));

export function Breathe() {
  const clock = useClock();
  const offsetTx = useDerivedValue(() => [
    { translateY: 300 + Math.sin(clock.value / 300) * 300 - 300 },
  ]);
  const style = useAnimatedStyle(() => ({
    ...StyleSheet.absoluteFillObject,
    transform: [{ translateY: 300 + Math.sin(clock.value / 300) * 300 - 300 }],
  }));
  return (
    <View
      style={{
        flex: 1,
        flexDirection: "row",
      }}
    >
      <View style={{ flex: 1 }}>
        <Animated.View style={style}>
          {array.map((index) => (
            <View
              key={index}
              style={{
                position: "absolute",
                top: 150 * index + 50,
                left: 15,
                width: 100,
                height: 100,
                backgroundColor: "blue",
              }}
            />
          ))}
        </Animated.View>
      </View>

      <Canvas
        mode="continuous"
        style={StyleSheet.absoluteFill}
        pointerEvents="none"
      >
        <Group transform={offsetTx}>
          {array.map((index) => (
            <Rect
              key={index}
              x={15}
              y={150 * index + 50}
              width={100}
              height={100}
              color="green"
            />
          ))}
        </Group>
      </Canvas>
    </View>
  );
}
```

### Steps to reproduce

Run the code snippet, the expected behaviour is that the color blue should never be visible.

Example with Skia: https://gist.github.com/wcandillon/da5715b7b107bee808193cb637f8539f (contains the SVG example as well).

### Snack or a link to a repository

https://gist.github.com/wcandillon/da5715b7b107bee808193cb637f8539f

### Reanimated version

3.5.4

### React Native version

0.71.0

### Platforms

Android

### JavaScript runtime

Hermes

### Workflow

React Native

### Architecture

Paper (Old Architecture)

### Build type

Debug mode

### Device

Real device

### Device model

Pixel 4

### Acknowledgements

Yes

**Comment by tomekzaw** [comment]
Hey @wcandillon! Thanks for reporting this issue.

In Reanimated, we distinguish 3 categories of props depending on how we animate them:
* **Non-layout props** (also called **UI props**) &ndash; we can update them synchronously on the UI thread and we don't need to recalculate layout (position and size) when they change, for instance `backgroundColor` or `opacity`
* **Layout props** &ndash; we can update them from the native side (most likely on the UI thread) but we need to calculate layout after we do so, for instance `width`, `margin`, `padding` or `flex`
* **JS props** &ndash; we cannot update them from the native side because of at least one of these reasons:
    * The component is not a native component (it doesn't have a ShadowNode)
    * The component needs to run some calculations in JS code when its props change

`AnimatedG` from `react-native-svg` is one of those components which we need to animate using JS props mechanism. Effectively, this works like calling `setNativeProps` via `runOnJS`. Here's how it works on the native side:

https://github.com/software-mansion/react-native-reanimated/blob/c56d44fd99e7fb3f46f1868e1cfc6167bb759309/apple/REANodesManager.mm#L508-L517

On the JS side, we add a listener for `onReanimatedPropsChange` event that eventually calls `setNativeProps`, here's the whole flow:

https://github.com/software-mansion/react-native-reanimated/blob/c56d44fd99e7fb3f46f1868e1cfc6167bb759309/src/createAnimatedComponent/JSPropUpdater.ts#L70-L73

https://github.com/software-mansion/react-native-reanimated/blob/c56d44fd99e7fb3f46f1868e1cfc6167bb759309/src/createAnimatedComponent/JSPropUpdater.ts#L47-L50

https://github.com/software-mansion/react-native-reanimated/blob/c56d44fd99e7fb3f46f1868e1cfc6167bb759309/src/createAnimatedComponent/createAnimatedComponent.tsx#L247-L255

Because of asynchronicity, there's always some amount of delay. When the JS thread is busy, obviously some animation frames will be dropped. We can easily simulate busy JS thread with the following hook which you can call from `App` component:

```ts
function useJSThreadKiller() {
  useEffect(() => {
    const id = setInterval(() => {
      const until = performance.now() + 200;
      while (performance.now() < until) {}
    }, 300);
    return () => clearInterval(id);
  }, []);
}
```

Here's how it behaves (notice that the blue square is lagging when JS thread is busy):

https://github.com/software-mansion/react-native-reanimated/assets/20516055/98f6af68-ea92-4ed8-a977-af693a41281f

This is why there's a lag when using react-native-svg, let me check out the repro with Skia to see what's happening there.

**Comment by wcandillon** [comment]
@tomekzaw thank you for providing context. I'm very appreciating 🙏

In the case of Skia, on Android, it the delay can easily be explained because of our rendering pipeline there (see https://github.com/Shopify/react-native-skia/pull/1965), for iOS, I would need to do more testing and see if it can be easily reproduced on iOS. If not, we can probably close this.

**Comment by tomekzaw** [comment]
Okay, so effectively it updates props on the JS thread, correct? https://github.com/Shopify/react-native-skia/blob/d3881d084a0d1eb96460acfbb816832ead92d1bc/package/src/external/reanimated/renderHelpers.ts#L59-L76

Would be great to animate everything on the UI thread.

**Comment by wcandillon** [comment]
Sorry for the confusion `bindReanimatedProps2` uses the JS thread but if you use Reanimated 3, it uses the UI thread `bindReanimatedProps`

**Comment by tomekzaw** [comment]
Oh, you're right, I've linked the wrong function from Rea2. So the question is still valid, why the breakpoint in `REANodesManager` is not hit but the animation is running? 🤔

**Comment by wcandillon** [comment]
We are not using createAnimatedComponent, we just use a mapper to
update the node property directly. This is why this will not get it.

**Comment by wcandillon** [comment]
@tomekzaw Thank you so much for taking the time to look into this and providing the context of why this happens on SVG. In Skia, we don't think reanimated is the culprit either, we have an issue on our side to track this: https://github.com/Shopify/react-native-skia/issues/1960

**Comment by tomekzaw** [comment]
Always happy to help! Thanks ❤️
