### ISSUE TITLE
Animation resets and stops responding after redux re render state

### ISSUE THREAD

**Issue by guilhermeferrer** [software-mansion/react-native-reanimated#546]
I'm trying to implement a custom scroll indicator for a horizontal ScrollView and everything works fine execept when I need to do something on redux that changes the state, the animation resets and stops responding like the gif bellow:

![animated](https://user-images.githubusercontent.com/37006054/72371793-d6f3cf00-36e3-11ea-89dc-0962c82e002f.gif)

I was able to resolve this creating the animated variables outside of the function, but I don't understand why did it happen, there's other way to resolve this?

Snack Example: https://snack.expo.io/@zlg/daa4e9

**Comment by PierreCapo** [comment]
You need to wrap your Animated Value into a useMemoOne hook to not redeclare your animated value in every rerender.
Your line:
```JS
const scrollX = new Value(0);
```

Should become:

```JS
const { scrollX } = useMemoOne(() => ({
scrollX: new Value(0)
}), [])
```

You could achieve the same with `React.useMemo`, but `useMemoOne` https://github.com/alexreardon/use-memo-one is a better alternative because it guarantees that your animated value will never be discarded whereas it can potentially appen with `React.useMemo`

**Comment by guilhermeferrer** [comment]
Thank you very much @PierreCapo, useMemoOne solved my problem.
