### ISSUE TITLE
Xcode Archive Error: Undefined symbols for WorkletRuntime::runGuarded

### ISSUE THREAD

**Issue by jenskuhrjorgensen** [software-mansion/react-native-reanimated#5465]
### Description

Hi

I've run into an Xcode archive issue with the newest version of `react-native-reanimated` (3.6.1) when using JSC or Hermes and `WorkletRuntime::runGuarded` which means we cannot create release builds of our app with the newest version of `react-native-reanimated`.

I'm getting:
```
ld: Undefined symbols:
  reanimated::getCallGuard(facebook::jsi::Runtime&), referenced from:
      void reanimated::runOnRuntimeGuarded<>(facebook::jsi::Runtime&, facebook::jsi::Value const&) in AppDelegate.o
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

For debug builds on the simulator everything seems to be working fine. Archiving also seems to work when using `react-native-reanimated` 3.5.4.

I encountered the issue when archiving an app that also uses `react-native-vision-camera` (https://github.com/mrousavy/react-native-vision-camera) 2.16.5 and I have copied the c++ code from that library to `AppDelegate.mm` to reproduce the issue in an otherwise [clean fork of `react-native-reanimated`](https://github.com/jenskuhrjorgensen/react-native-reanimated/). Disclaimer: I have no idea how that code works - I just wanted it to fail in a minimum repro setup. I haven't tested it with v3 of `react-native-vision-camera` because it only supports Hermes and we cannot yet upgrade to that in our app. 

Other possibly relevant versions:
Cocoapods 1.14.3
Xcode 15.0.1

Let me know if you need any other information that I can help with. 

Thanks

### Steps to reproduce

1. Open `Example/ios/ReanimatedExample.xcworkspace` with Xcode
2. Set up signing for the target
3. `yarn setup`
4. In Xcode: `Product` => `Archive`

### Snack or a link to a repository

https://github.com/jenskuhrjorgensen/react-native-reanimated/

### Reanimated version

3.6.1

### React Native version

0.72.6

### Platforms

iOS

### JavaScript runtime

Hermes

### Workflow

React Native

### Architecture

Paper (Old Architecture)

### Build type

Release app & production bundle

### Device

None

### Acknowledgements

Yes

**Comment by tomekzaw** [comment]
Hey @jenskuhrjorgensen, thanks for submitting this issue. I've just tested Reanimated 3.6.1 on a fresh React Native 0.73.0 app built in release mode for iOS (old architecture) and it works correctly for me.

Before investigating this issue further, we'll need some more info:
1. How do you install pods for the release build? In particular, do you set environmental variable `PRODUCTION=1` when running `pod install`?
2. What is the name of the build configuration? Is it `Release` (default) or something different?

**Comment by tomekzaw** [comment]
> Did you build from my repro repo?

Nope, I cannot set up signing for the target. But I can already tell what's the cause of the error. There is a mismatch of the presence of `NDEBUG` flag when compiling `AppDelegate.mm` (which includes `RNReanimated/WorkletRuntime.h`) and `ReanimatedRuntime.cpp` inside `RNReanimated` pod.

>  I think it just used the default "release" config.

Can you confirm that? It works correctly only if the name of the scheme is `Release`.

> And I'm not setting anything speciel when running pod install.

Can you try installing pods with `PRODUCTION=1`?

**Comment by jenskuhrjorgensen** [comment]
> > I think it just used the default "release" config.
> 
> Can you confirm that? It works correctly only if the name of the scheme is `Release`.
It is using the `Release` configuration when archiving.

**Comment by stefanocapitanio** [comment]
Hi!

I'm having the same issue, I double checked the `Release` configuration and tried `PRODUCTION=1 pod install` but got the same error.

Thanks

**Comment by tomekzaw** [comment]
@jenskuhrjorgensen 

> Where can I see in your documentation that I should run `PRODUCTION=1` pod install (I would expect it somewhere around [here](https://docs.swmansion.com/react-native-reanimated/docs/2.x/fundamentals/installation/#ios))?

Nowhere. You can't see it in our docs because technically it's not our flag. It's a flag from React Native. It was introduced some time ago, without you couldn't build a fresh RN app (if I remember correctly, only on Fabric). It looks like it's gone in 0.73, but you're on 0.72.6 so I thought it might be relevant.

Also, you've linked to the 2.x docs page which is no longer maintained, 3.x docs are [here](https://docs.swmansion.com/react-native-reanimated/docs/fundamentals/getting-started/).

> If I understand those `NDEBUG` and `PRODUCTION` flags correctly it means we cannot make due with one set of committed pods for building both development and production builds. Is that correct?

Yes, kind of. `PRODUCTION` is an environmental variable that is read in podspecs of React Native and based on them some dependencies are included or excluded (for instance, Flipper stuff). It also affects the preprocessor macros used to compile the source files which, in turn, affect which parts of the code will be compiled (using `#if` or `#ifdef`).

For some reason, in #5113 we needed to migrate `#ifdef DEBUG` into `#ifndef NDEBUG` but after some time it turned out that React Native does it wrong and we needed to fix it in #5366. A common assumption for C++ projects is that in debug mode `DEBUG=1` is set and in release mode `NDEBUG=1` is set. React Native injects `DEBUG=1` macro in debug mode but sadly it does not inject `NDEBUG` in release mode (on iOS on Paper).

When you compile `ReanimatedRuntime.cpp` while building `RNReanimated` pod,`NDEBUG` flag is present because it is set correctly in `RNReanimated.podspec`. However, when you compile `AppDelegate.mm` which includes `RNReanimated/WorkletRuntime.h`, `NDEBUG` flag is not set because it's a different pod, managed by React Native (or, in fact, the `Podfile` of your app which is generated by React Native by default). In short, when you import our headers, you need to make sure that you pass proper preprocessor flags.

The repro you have provided does not represent a valid use case for this error to appear. Can you share more information on how to reproduce this error in your original app?

**Comment by tomekzaw** [comment]
@stefanocapitanio Thanks for checking. Can you share more info, for instance linker logs?

**Comment by jenskuhrjorgensen** [comment]
> Hey @jenskuhrjorgensen, thanks for submitting this issue. I've just tested Reanimated 3.6.1 on a fresh React Native 0.73.0 app built in release mode for iOS (old architecture) and it works correctly for me.

@tomekzaw it wasn't until now that I realized that you maybe didn't catch that I made some changes in the `AppDelegate.mm` by calling `WorktletRuntime::runGuarded` in order to reproduce the error. The changes can be seen in the repro repo here: https://github.com/jenskuhrjorgensen/react-native-reanimated/blob/704ed4d74ff22d762eb166a78c85c208c8794544/Example/ios/ReanimatedExample/AppDelegate.mm#L25

And I can confirm that the issue is also reproducible without signing and archiving when just running:

```
npx pod-install && npm run ios -- --mode release
```

Running the same with the `PRODUCTION=1` flag works.

I hope this helps in the reproduction of this on your end.

**Comment by tomekzaw** [comment]
@jenskuhrjorgensen I made a PR to RNVisionCamera which should solve the problem: https://github.com/mrousavy/react-native-vision-camera/pull/2270

**Comment by jenskuhrjorgensen** [comment]
Thanks, I will check it out @tomekzaw 

Is this also a long term fix? Because I guess this means all dependencies using worklets from `react-native-reanimated` would require this flag to be set?

**Comment by tomekzaw** [comment]
> Is this also a long term fix?

No, we plan to remove `NDEBUG` flag from header files to avoid such problems.

> this means all libs using worklets from `react-native-reanimated` would require this flag to be set?

Not really, only the libraries that include C++ files from Reanimated need this change. Currently, RNVisionCamera is the only library that includes our headers.

**Comment by jenskuhrjorgensen** [comment]
Thanks for the thorough and efficient responses, @tomekzaw.
