### ISSUE TITLE
Animation fails to execute and doesn't display components

### ISSUE THREAD

**Issue by SebaMutuku** [software-mansion/react-native-reanimated#5492]
### Description

Sometimes animations fail to execute and affected components/widgets don't show up

### Steps to reproduce

Add react-native-reanimated library ~3.3.0 in an expo project running React native version 0.72.6
Add the animation as show in the view below 
```
<Animated.View style={{
        margin: 10
    }} entering={FadeInRight.delay(100).duration(1000).springify()}>
```
Test it on android device. Tested it on android 10.

You will notice sometimes the view doesn't show animated components. However, when you restart the app, animation shows.

### Snack or a link to a repository

personal and can't share this

### Reanimated version

3.3.0

### React Native version

0.72.6

### Platforms

Android

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Device model

Pixel 6 pro, and Galaxy A21 s

### Acknowledgements

Yes

**Comment by SebaMutuku** [comment]
Sample screenshot for the same
![Screenshot_1702404731](https://github.com/software-mansion/react-native-reanimated/assets/36365043/c573911c-50b3-432a-b3f7-0b768a46a6bf)

**Comment by tomekzaw** [comment]
@SebaMutuku ~3.3.0 is quite old, does the issue persist on the latest version of Reanimated (currently 3.6.1)?

**Comment by SebaMutuku** [comment]
@tomekzaw I update to the current version. Allow me to do a couple of tests and revert.

**Comment by Latropos** [comment]
Hi! @SebaMutuku Does the update fix the problem? Can we close this issue?

**Comment by SebaMutuku** [comment]
@Latropos this doesn't based on comments from expo repo, I exluded it but I get the error 
`Error: [Reanimated] Mismatch between JavaScript part and native part of Reanimated (3.6.1 vs 3.3.0).`

**Comment by Vittor-Javidan** [comment]
I notice this error on my app as well.

This are my observations, of some clues that i noticed:

Through many usages i notice this happens more frequently on newer versions of android, For example, on my android 9 it happens very rare, but on 13 sometimes happens like 10% - 20% of the time. I'm sure is the animation library for the reason of every button functionalities is working fine, but not the animations.

This happens more frequently when you use hidden animation methods like requestanimationframe(). For example, using this method instead animationStyle, on android 13 sometimes the animation is not working 50% to 80% of the time!

This issue is marked by inconsistency, so is hard to debug.

My shot is that reanimated is using some broken api from android, but their source code is more likely to be fine. And the android uses distinct animations libraries for each android version, which the problem intensifies for each newer version of android. So probably there is a animation api being deprecated on android side.

I think the maintainers of reanimated should verify if the native code can have a more updated api. This is for sure a good start point to debug what is really happening.

If you want to test on you android 13 my app, this is the play store link: https://play.google.com/store/apps/details?id=com.lonewispapps.earthlog

You gonna notice a few times my app starts with the layout rendered, but the menu don't open my drawer, and the screen has no content. But you can create a project fine. Only way to solve this issue is by restarting the app and praying to animation work. And if it works, you gonna notice the project created during the bug is there without any issues.

**Comment by Vittor-Javidan** [comment]
[Update]

For me the solution and issue was this: https://github.com/software-mansion/react-native-reanimated/issues/5388

**Comment by SebaMutuku** [comment]
Finally, version 3.6.0 has been included in the latest expo SDK 50

**Comment by Latropos** [comment]
Closing since the error doesn't persist in newest reanimated

**Comment by Vittor-Javidan** [comment]
To be honest, I quit reanimated library. Fully removed from my app. The reason is: instability through versions.

Every time a new Expo SDK comes, it forces me to decide witch reanimated version I must use, for the reason of always coming a new animation bug. After 3 Expo SDK updates, i Just realize is not worthy keeping the reanimated lib. So i just refactored everything using the default React Native animation API, and everything just started working fine. No more fixing after expo SDK update. I know this is a expo issue, but at the same time expose how unstable is the releases from reanimated lib. Updating the reanimated lib can be a shot in the foot every time.
