### ISSUE TITLE
Archive Process Not working

### ISSUE THREAD

**Issue by achall9** [software-mansion/react-native-reanimated#5535]
### Description

Getting 'RuntimeAdapter -> Use of undeclared identifier debugger' every time I archive my React native app in Xcode 15.
This issue did not exist before Xcode 15.
I am using version ^3.1.0 in my package.json.

I am able to build and run the app locally without issue.

### Steps to reproduce

1. Archive app

### Snack or a link to a repository

https://google.com

### Reanimated version

1.3.0

### React Native version

^0.70.8

### Platforms

iOS

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by Latropos** [comment]
Hi! This bug is already described here: https://github.com/software-mansion/react-native-reanimated/issues/5446

You are probably interested in two last comments in the conversation, the information, that will be released in 3.7.0, and how to start using it earlier. 

If it doesn't fix your problem, please reopen the issue.
