### ISSUE TITLE
createAnimatedComponent props types vanish for components with index signature

### ISSUE THREAD

**Issue by tedcu** [software-mansion/react-native-reanimated#5607]
### Description

Animated custom component completely loses props types if an index signature is included in the props type. Started happening from `react-native-reanimated` 3.4 onwards.

See example in "steps to reproduce".

FYI the Snack is useless as this is just a type issue.

### Steps to reproduce

Fails
```
type TestType = {
  test: number
} & { [index: string]: string }

const Component = forwardRef((props: TestType) => {
  return null
})

const AnimatedComponent = Animated.createAnimatedComponent(Component)

const AnimatedMe = () => {
  return <AnimatedComponent test={0} />
}
```

Works
```
type TestType = {
  test: number
}

const Component = forwardRef((props: TestType) => {
  return null
})

const AnimatedComponent = Animated.createAnimatedComponent(Component)

const AnimatedMe = () => {
  return <AnimatedComponent test={0} />
}

```

### Snack or a link to a repository

https://snack.expo.dev/@tedcu/mad-red-bagel

### Reanimated version

3.6.1

### React Native version

0.73.2

### Platforms

Android, iOS

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Device model

Any

### Acknowledgements

Yes

**Comment by tjzel** [comment]
Hi @tedcu. Unfortunately, the use case you are proposing here is in opposition to how TypeScript works. You can read [here](https://www.typescriptlang.org/docs/handbook/2/objects.html#index-signatures) that
> While string index signatures are a powerful way to describe the “dictionary” pattern, they also enforce that all properties match their return type.

Therefore
```tsx
type TestType = {
  test: number
} & { [index: string]: string }
```

Is not a valid TypeScript type. If it worked before, it's only because animated component type was in worse state than they are now and key `test` was probably incorrectly inferred as any. You can do

```tsx
type TestType = {
  test: number
} & { [index: string]: string | number }
```

and see that animated component type works in this case.
