### ISSUE TITLE
How to performantly use an Animated.Value from another component? (w/o JS?)

### ISSUE THREAD

**Issue by xenophilicibex** [software-mansion/react-native-reanimated#567]
I want to make many different components (titlebars, tabs, buttons, &c) animate based on a single animation value (usually from gestures).

I've got it working by passing the Animation.Value around through JS (using a context + reducer with single Animation.Value). It works, but as I've added more and more animations, the frame drops have gotten worse and worse.

Here is a gesture with buttery smooth animation. It has two snapping points, and is working great,  **but** it doesn't affect anything else.
<img src="https://user-images.githubusercontent.com/1843672/72555971-afc80980-386b-11ea-88a0-bb755aa3e677.gif" width="204" height="394">

Now I want to do two things: 
1. Hook into the start, progress, and end of the animation (+gesture) to update the state machines
2. Animate the Tabs (and some other components) as this happening

Right now I only know how to do this through JavaScript. But as soon as I add some JavaScript, the entire animation loses frames. Here is a gif is how I want it to function. _As the hexagon expands, the tabs slide away_ (using the same Animation.Value) (Notice the JS FPS dropping to 20s)
<img src="https://user-images.githubusercontent.com/1843672/72556177-12b9a080-386c-11ea-9c53-ad65091d8142.gif" width="202" height="395">

In my app I have a number of gesture based animations like this that affect the rest of the app. I only know how to pass them around through JavaScript, but then the FPS tanks. I understand the purpose of Reanimated is to avoid going through the JS bridge, but right now I don't know of any other away to achieve the effect I want.

If anyone has any suggestions, I welcome them.

**Comment by Jarred-Sumner** [comment]
Immediate thoughts:
- Try to completely avoid doing this in JavaScript, you very likely can do what you need through `Animated.block`, `Animated.cond`, and `Animated.interpolate`. If there are state changes required, do them when the gesture state ends or passes a threshold. Ensure the `Animated.call` only triggers when necessary (rather than on every pan or something)
- If the same nodes are created by multiple components, try moving the node into an `Animated.proc`
- Ensure you're not creating the nodes in `render` (unless they're inside `<Animated.Code />`), instead create them in the `constructor` or in a `React.useRef`
- Ideally, only animate `transform` and `opacity`. `padding*`, `left`, and `top` are okay too, but definitely not `width` or `height`. You want to avoid causing layout to occur during gestures

**Comment by xenophilicibex** [comment]
Thanks for the suggestions @Jarred-Sumner . I was able to solve the problem by completely removing all JS calls. I moved the `transitionValue` to the top level component and pass it around everywhere and interpolate it each component.

**Comment by theMasix** [comment]
Thanks @Jarred-Sumner . What about `reanimated v2`? I can't find these methods (`block, cond etc`) in version 2. I think structure is fully changed in the new version...
