### ISSUE TITLE
All animations not working on some devices (Pixel 6/iPhone 11)

### ISSUE THREAD

**Issue by benawad** [software-mansion/react-native-reanimated#5774]
### Description

I attempted to upgrade my app to Expo 50 which uses reanimated v3.6.2 and animations did not start at all for a handful of users. 

Happened on a variety of different devices (Pixel 6, iPhone 8 Plus, iPhone 11, and Xiaomi Redmi Note 9 - to name a few).  It doesn't happen on every device of the same model, and I haven't been able to narrow down the commonality between the devices that don't work.

I can't reproduce it on any of my devices or using something like LambdaTest.

I debugged it with a user who was experiencing the problem (they have a Pixel 6 with Android 14) and even this simple repo that has a spinning square does not rotate for them (tried v3.8.0 and still didn't work).

Let me know if you have any tips on getting more debug info from the devices that don't work.

### Steps to reproduce

1. Run dev or prod build of the sample repo on a Pixel 6 with Android 14

### Snack or a link to a repository

https://github.com/benawad/test-reanimated

### Reanimated version

3.6.2

### React Native version

0.73.4

### Platforms

Android, iOS

### JavaScript runtime

Hermes

### Workflow

Expo Dev Client

### Architecture

None

### Build type

Release app & production bundle

### Device

Real device

### Device model

Pixel 6 (Android 14)

### Acknowledgements

Yes

**Comment by tomekzaw** [comment]
Hi @benawad, thanks for opening this issue.

Is it possible that some of your users have **reduced motion setting enabled**? Reanimated detects it out-of-the-box and in such case, it will automatically skip most animations in order to align with the expectations of the users.

You can control this setting individually for each animation by passing `{reduceMotion: ReduceMotion.Never}` to the animation config &ndash; this way you can force the animation to run even if reduced motion is enabled.

Please let us know if this works for you. For more details, please see [Accessibility](https://docs.swmansion.com/react-native-reanimated/docs/guides/accessibility/) section in our documentation.

**Comment by benawad** [comment]
That was it. Thanks for the help.

Is there a way to globally provide the reduced motion setting? I have a lot of animations, and users don't expect all the animations to stop even when they have reduced motion enabled. I'd like to create a setting at the application level.

For now, I'll be showing a pop-up to tell users to turn off reduced motion if they want to see any animations whatsoever.

**Comment by tomekzaw** [comment]
Nope, there's no application-level switch for now, but we are considering adding it as some users have requested it.
