### ISSUE TITLE
withRepeat does not repeat an entire animation block

### ISSUE THREAD

**Issue by AlexIoanGheorghita** [software-mansion/react-native-reanimated#5775]
### Description

I am using `react-native-skia` together with `react-native-reanimated` (v3). I have a couple of elements (a rectangle, a group of various shapes, and a line) for which I have separate animations. However, I am creating a dependency between those separate animations through callbacks as so:

```
useEffect(() => {
    translateY.value = withRepeat(withSpring(0, { damping: 12, stiffness: 85 }, () => {
      opacityGroup.value = withTiming(1, { duration: 500 }, () => {
        opacityLine.value = withTiming(1, { duration: 500 }, () => {
          lineWidthRight.value = withTiming({x: 221, y: 190}, { duration: 500 });
          lineWidthLeft.value = withTiming({x: 101, y: 190}, { duration: 500 });
          lineTranslateY.value = withRepeat(withDelay(500, withSequence(
            withTiming(25, { duration: 1000 }),
            withTiming(-25, { duration: 2000 }),
            withTiming(0, { duration: 1000 })
          )), -1);
        });
      });
    }));
  }, [
    translateY, 
    opacityGroup, 
    opacityLine, 
    lineWidthRight, 
    lineWidthLeft, 
    lineTranslateY
  ]);
```

The animations work as expected, and in the order that is expected. However, when the last callback finishes animating, I want to repeat the entire animation block. I thought it would be possible with the `withRepeat()` modifier, but if I add it as in the code example above, it will only repeat the `translateY` animation - this means that when the translation finishes, it will repeat, even though the other animations are still running. Is this expected behavior? If yes, is there any way to repeat the entire animation block ONLY after the last animation has finished?

### Steps to reproduce

1. Create a few easy shapes in `react-native-skia` (or pure React Native. The important aspect is for the animations to be separate, meaning to be applied on different components).
2. Create two or three animations - one for each component (such as a translation, a scale, etc.).
3. Have these animations in a `useEffect()`, so that they start when the screen renders, and create a dependency between them using callbacks, so that they are executed in order.
4. Apply `withRepeat()` on the first animation as in the example provided.

### Snack or a link to a repository

xyz

### Reanimated version

3.6.2

### React Native version

0.73.4

### Platforms

Android

### JavaScript runtime

None

### Workflow

Expo Dev Client

### Architecture

None

### Build type

Debug app & dev bundle

### Device

Android emulator

### Device model

Pixel 3 (Android 13.0)

### Acknowledgements

Yes

**Comment by Latropos** [comment]
Hi @AlexIoanGheorghita!
In fact all the animations run, but only `translateY` resets the animated value to its initial value. 
It means that in first loop you animate `translateY` from `translateY_initial_val` to `0`, `opacityGroup` from `opacityGroup_initial_val` to 1 etc.
And in the second loop you animate `translateY` again from `translateY_initial_val` to `0` (since function withRepeat is expected to restart the animated value), but you animate  `opacityGroup` from 1 to 1! This behaviour is expected.

I've created the following snippets of code to show you how to fix the problem
<table>
<tr><td>CODE</td><td>Recording</td></tr>
<tr><td>

```jsx
  const translateY = useSharedValue(100);
  const translateX = useSharedValue(100);

  useEffect(() => {
    translateY.value = withRepeat(
      withRepeat(
        withSpring(0, { damping: 12, stiffness: 85 }, () => {
          translateX.value = withTiming(translateX.value + 100, {
            duration: 500,
          });
        })
      )
    );
  }, [translateY, translateX]);
 ```
</td><td>

https://github.com/software-mansion/react-native-reanimated/assets/56199675/a315c2c8-7d2c-4e93-8d3d-bb3050ecbb81

</td></tr>
<tr><td>

```jsx
  const translateY = useSharedValue(100);
  const translateX = useSharedValue(100);

  useEffect(() => {
    translateY.value = withRepeat(
      withRepeat(
        withSpring(0, { damping: 12, stiffness: 85 }, () => {
          translateX.value = 100;
          translateX.value = withTiming(200, {
            duration: 500,
          });
        })
      )
    );
  }, [translateY, translateX]);

```
</td><td>


https://github.com/software-mansion/react-native-reanimated/assets/56199675/2288e163-a7b7-4403-9461-808993d881a7


</td></tr>

</table>
