### ISSUE TITLE
animatedProps doesn't work with Flashlist

### ISSUE THREAD

**Issue by renochew** [software-mansion/react-native-reanimated#5908]
### Description

animatedProps seems not working properly with Flashlist

### Steps to reproduce

1. Open Snack
2. Click button to toggle the "scrollEnabled" prop value through useAnimatedProps hook.
3. Flashlist still scrollable
4. Change the "AnimatedFlashList" component to "Animated.Flatlist".
5. Work as expected

### Snack or a link to a repository

https://snack.expo.dev/@renochew/curious-red-cashew?platform=android

### Reanimated version

3.8.1

### React Native version

0.73.6

### Platforms

Android

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by hirbod** [comment]
You need to use FlashLists `renderScrollComponent` and pass an Animated.ScrollView to it.

A quick example from my codebase:

```tsx
    import { ScrollView } from 'react-native-gesture-handler'
    import Animated from 'react-native-reanimated'
    
    const AnimatedScrollView = Animated.createAnimatedComponent(ScrollView)
      
    const ScrollViewWithRef = forwardRef((props, ref) => (
      <ScrollView {...props} ref={ref}  />
    )) as typeof ScrollView

    <FlashList
      ...
      renderScrollComponent={ScrollViewWithRef}
    />
```

(By the way, using ScrollView from RNGH is on purpose, you should do it on every FlashList (I have an exported FlashList that does this in our App). It optimizes touch behavior with Touchables. 

Either way, you'd need to pass your scrollEnabledProp to the underlying ScrollView

**Comment by hirbod** [comment]
Here, I've fixed your Snack
https://snack.expo.dev/@hirbod/flashlist-scroll-props?platform=android

**Comment by szydlovsky** [comment]
Thank you @hirbod for solving the issue, happily closing 😄

**Comment by efstathiosntonas** [comment]
@hirbod can you share an example of your exported Flashlist? 

What kind of touchables optimization is providing exactly?

**Comment by hirbod** [comment]
@efstathiosntonas, if you use touchable components from RNGH (like TouchableOpacity, RectButton, etc.), they will automatically detect whether you're trying to tap or scroll. Other components will flash when touched, but this combination does not. That's why I always pass ScrollView from RNGH to FlashList. Here is a quick example of many apps doing it wrong (one of the easiest indicators for me that someone is using React Native). Notice how the 3-dot icon goes into the pressed state, even though I am scrolling? This would not happen with RNGH and their pressables.

https://github.com/software-mansion/react-native-reanimated/assets/504909/90e218e2-f551-415e-bd55-da2ad8f25032
