### ISSUE TITLE
Android App crash on scrollTo With PanGesture

### ISSUE THREAD

**Issue by DonBrowny** [software-mansion/react-native-reanimated#6418]
### Description

I am trying to trying to create a Drag-Sort component with react-native-reanimated and react-native-gesture-handler.
I came across this old snack - https://snack.expo.dev/@stewartarmbrecht/apple-music-drag-and-sort-working?platform=android and try to use it with the latest version of react-native and the app crashed when the scrollTo is triggered.

https://github.com/user-attachments/assets/7de221bd-4261-4642-a289-3db9fc6c0613

### Steps to reproduce

yarn start --reset-cache
and open the app in android-emulator

### Snack or a link to a repository

https://github.com/DonBrowny/AnimationTest

### Reanimated version

3.15.0

### React Native version

0.75.1

### Platforms

Android

### JavaScript runtime

None

### Workflow

None

### Architecture

Fabric (New Architecture)

### Build type

None

### Device

Android emulator

### Acknowledgements

Yes

**Comment by MatiPl01** [comment]
I encountered the same issue. Thanks for reporting. I will forward the issue to the person who has been working on this recently.

**Comment by DonBrowny** [comment]
@bartlomiejbloniarz To narrow down the suspects for you, this issue occurs even on react-native-74.1 so this not specific to React Native update and i have also tried replacing the deprecated API with the alternatives/new way of handling gesture and faced the same issue. Let me know if you need any help in debugging this.

**Comment by bartlomiejbloniarz** [comment]
Hi @DonBrowny. This problems occurs, because when the user is moving an item, it triggers an update. This update synchronously triggers the logic responsible for scrolling the list (so it triggers another update). This means that there is a recursive call to the `ShadowTree::commit` function in RN. Currently such recursive calls lead to a deadlock (on Android). The issue seems to have been noticed by the RN team and had been addressed in [this PR](https://github.com/facebook/react-native/pull/44725), but the fix is currently behind a feature flag. I tested it, and it seems to resolve our issue. I'm not sure when this behavior will be made default.

**Comment by DonBrowny** [comment]
@bartlomiejbloniarz Thanks for digging into this. Can you please let me know how to enable the FF and test this?

**Comment by bartlomiejbloniarz** [comment]
I just changed the [invocation of the FF getter](https://github.com/rubennorte/react-native/blob/d08ba0f94b247b9103a8ba77d11568665a7d2ab8/packages/react-native/ReactAndroid/src/main/jni/react/fabric/Binding.cpp#L491) to a `true` value. For this I also had to [build RN from source](https://reactnative.dev/contributing/how-to-build-from-source).

**Comment by DonBrowny** [comment]
Got it, Thanks. I will close this issue since it's a issue in the react-native framework and not on this library.

**Comment by dppo** [comment]
@DonBrowny I encountered the same problem, is there any solution?
