### ISSUE TITLE
Multiple WithRuntimeDecorator segfaults in production build

### ISSUE THREAD

**Issue by BenIrving** [software-mansion/react-native-reanimated#6579]
### Description

We are rolling out new architecture to our production users in one of our apps, and have noticed a number of segfaults resulting from reanimated stack traces.

I thought it was perhaps relating to these missing `WithRuntimeDecorator` [[1](https://github.com/facebook/react-native/pull/45049) [2](https://github.com/facebook/react-native/pull/45042)] methods as I can see some that were previously missing have been recently added, however some of the decorators already exist for methods that appear to be causing crashes, namely `createStringFromUtf8` and `setPropertyValue`

There does not appear to be a common trend on which screen or user interaction within our app is causing these issues, and they are not reliably reproducible. 

I've copied some of the stack traces from our Sentry reporting below, unfortunately they're not all complete with lots of `unknown` items but I've copied the most relevant items that exist off the top of the stack.

```
facebook::jsi::WithRuntimeDecorator<T>::createStringFromUtf8
reanimated::ShareableObject::toJSValue
reanimated::ShareableObject::toJSValue
reanimated::WorkletRuntime::executeSync
```

```
facebook::jsi::WithRuntimeDecorator<T>::setPropertyValue
reanimated::ShareableObject::toJSValue
reanimated::ShareableObject::toJSValue
reanimated::WorkletRuntime::executeSync
```

```
facebook::jsi::RuntimeDecorator<T>::setNativeState
reanimated::ShareableObject::toJSValue
```

```
facebook::jsi::WithRuntimeDecorator<T>::call
facebook::jsi::Function::call<T>
reanimated::ShareableWorklet::toJSValue
```

### Steps to reproduce

N/A

### Snack or a link to a repository

-

### Reanimated version

3.15.3

### React Native version

0.74.5

### Platforms

Android

### JavaScript runtime

Hermes

### Workflow

React Native

### Architecture

Fabric (New Architecture)

### Build type

Release app & production bundle

### Device

Real device

### Acknowledgements

Yes

**Comment by tomekzaw** [comment]
Hi @BenIrving, thanks for opening this issue!

The crash you're observing happens when two (or more) threads use JS runtime at the same time.

Even though the stack trace points to `facebook::jsi::WithRuntimeDecorator<T>::createStringFromUtf8` which is correctly synchronized and indeed called by Reanimated, the true offender might be another method which is missing synchronization called from React Native internals.

You're running on React Native 0.74.5 which doesn't contain fixes from https://github.com/facebook/react-native/pull/45042 and https://github.com/facebook/react-native/pull/45049. One thing you might try at this point is to incorporate these changes into your codebase, build React Native from source and check if the issue still persists. Obviously, this requires some efforts so maybe it's better to wait for 0.76-stable which comes with those two fixes.

**Comment by BenIrving** [comment]
@tomekzaw Thanks for the reply! I assumed this would be the fix. 

We shipped this last week and have since observed none of these crashes in prod, so I assume it is resolved.
