### ISSUE TITLE
Cond if/else nodes re-evaluated when dependencies change

### ISSUE THREAD

**Issue by noldidrita** [software-mansion/react-native-reanimated#734]
I'm using a condition based on the gesture state to control the application a transformation or not. It works fine, however my issues is that the condition is re-evaluated every single time that one of the dependencies in the if/else clauses change, although the condition itself doesn't change. Let me show the code:
```
     cond(
       eq(gestureState, State.ACTIVE),
         sub(
           multiply(scrollOffset, divide(scale, baseScale)),
            scrollOffset,
          ),
        0,
      )
```

`scrollOffset` is an animated event mapped from the ScrollView

This Animation is applied to a handful of elements (~2000-3000 elements in a SVG chart). It works perfectly fine, however the ScrollView pan animation is terrible. The reason for this is that all the nodes are re-evaluated every single time that scrollOffset changes, although during the scroll, `gestureState` is not active, so the animation should default to the else node, which just sets the translation to 0. 

I would assume that the `cond` node would only evaluate the IF clause if the condition evaluates to true, otherwise it would just return the ELSE clause, which is just 0. Maybe this is unavoidable due to the internals of the Animated implementation, so I would ask, is there a way to achieve this on the native side?

**Comment by jakub-gonet** [comment]
Hi @noldidrita,

as you rightly pointed out this is caused by a current implementation that updates nodes when it's dependencies change. It can be surely implemented, but we would have to do some graph traversal to find usages of a given node because you can use some Value in cond which is used elsewhere (and should evaluate unconditionally).

Unfortunately, I don't have any solution on top of my mind right now for that problem.

**Comment by jakub-gonet** [comment]
Hi!
This issue was inactive for a while, so I'm closing it.
If you still face this problem don't hesitate to ask.
