### ISSUE TITLE
Reanimated V2, worklet API

### ISSUE THREAD

**Issue by jfrolich** [software-mansion/react-native-reanimated#823]
The worklet API is JavaScript code that contains redundant code (the `"worklet"` string). This means that some compile to JS languages can't produce the code because the compiler rightfully strips it away. An example is BuckleScript / ReasonML.

Would it be possible to revise this API decision, or have an alternative API? I would suggest having distinct naming for the function so the babel plugin knows it's a worklet. Like pretending the name with `worklet__` or something similar.

**Comment by romanonthego** [comment]
I too find API... strange. A bit uncomfortable event.
Could it be done like `use...` pattern for hooks? like `worklet...`?
Or may be like 
```js
const animation = () => {
  //....
}

animation.worklet = true
```

**Comment by terrysahaidak** [comment]
Hi @romanonthego. The only thing required in order to mark it as worklet is to use "worklet". This is just mark for babel to do its thing. The problem with .worklet - it can be defined at runtime or like something which can lead to tought times for babel to detect it. 

Could you explain why .worklet is way better than "worklet"?

**Comment by jfrolich** [comment]
> Hi @romanonthego. The only thing required in order to mark it as worklet is to use "worklet". This is just mark for babel to do its thing. The problem with .worklet - it can be defined at runtime or like something which can lead to tought times for babel to detect it.
> 
> Could you explain why .worklet is way better than "worklet"?

The `"worklet"` string will be removed by every optimizing compiler or smart enough compile to JS languages (specifically it's impossible to do this in ReasonML/BuckleScript). That is the problem. It can be resolved by indicating that something is a worklet by pretending the function name, or something that cannot be stripped away by the compiler, like `worklet()` in the body or something like:

```js
let aWorkLet = worklet(() => {
  ...
})
```

**Comment by terrysahaidak** [comment]
Do you use babel with ReasonML/BuckleScript projects?

**Comment by jfrolich** [comment]
> Do you use babel with ReasonML/BuckleScript projects?

Yes

**Comment by terrysahaidak** [comment]
Well, worklet wrapper could work then, yeah.
Just bit sure it's the best solution for now, but we'll take a look.

**Comment by jfrolich** [comment]
Thanks. I know of a few companies that write apps with Reason and React-Native (including my own company). So having a way to do this in Reason would be amazing.

**Comment by Ragnar-H** [comment]
To add to the API discussion here for compile-to-JS frameworks.

I see the babel plugin [auto-magically marks the hooks](https://github.com/software-mansion/react-native-reanimated/blob/c04e2a0c3f0151c14ef648a410fe4572076e18e1/plugin.js#L12-L18) provided by reanimated as `worklets`.

This is great! This becomes a problem for compile-to-JS since the hooks are identified by their function name. The function name isn't always preserved when compiled, and we can even break this with vanilla JS.

```
import Animated, { useAnimatedStyle } from 'react-native-reanimated'

...

// works
useAnimatedStyle(() => {
  return { width: magic }
})

// not identified as worklet
Animated.useAnimatedStyle(() => {
  return { width: moreMagic }
})
```

Specifically this is a problem for BuckleScript / ReasonML because ES6 imports come in the flavour of 

```
import * as Reanimated from 'react-native-reanimated'

// again not identified as worklet
Reanimated.useAnimatedStyle(...)
```

---

Some solutions I can think of

1. Require compile-to-JS languages to adhere to the `worklet` API
1. Flesh out the babel plugin to look for where imports are from
1. Provide a non-babel-plugin escape hatch (I'm still grokking what the plugin does to the input)

**Comment by terrysahaidak** [comment]
This PR will fix this:
https://github.com/software-mansion/react-native-reanimated/pull/1310

**Comment by jfrolich** [comment]
Great to have this alternative syntax! I added a comment.

**Comment by terrysahaidak** [comment]
https://github.com/software-mansion/react-native-reanimated/pull/1210 This PR should fix this type of imports as well. 

cc @jakub-gonet
