### ISSUE TITLE
Is Reanimated limited to the same animatable style properties as Animated?

### ISSUE THREAD

**Issue by mrousavy** [software-mansion/react-native-reanimated#893]
## Description

I couldn't find anything for this in the documentation, but I was wondering if animating properties such as `height` or `top` are supported by the reanimated API to run natively, or if they are limited to JS-animations like in the default Animated API?

**Comment by jakub-gonet** [comment]
AFAIK you can animate those, but performance will be decreased - changing height, width, margins, padding etc involves recalculating layout - you don't want to do it every frame.

**Comment by terrysahaidak** [comment]
In my reanimated-gallery project, I use height/width as well as top and left (instead of translate just to be in sync with dimensions, because they are both updated on native thread) for image lightbox transition. Works great. But still these require recalculation on each frame which causes them to be async. So if you going to use both layout properties and transforms, you'll see they are not in sync.
