### ISSUE TITLE
Feature request: bitwise operations (AND, OR, etc.)

### ISSUE THREAD

**Issue by lebedev** [software-mansion/react-native-reanimated#98]
Subject.

**Comment by ckknight** [comment]
If this is done, I'd prefer if they were named something like `bitAnd`, `bitOr`, `bitXor`, etc. This'd increase some clarity and make it obvious that these are not the logical (boolean) operators.

**Comment by angly-cat** [comment]
Hey. Sorry for not answering sooner.

In my app I heavily modified Viewer for my needs. One of which is tracking if a picture is touching either of screen edges. Currently for that I have 4 reanimated values. But I think it would've been more convenient to have just 1 reanimated value with bit masks.

So, basically, I want bitwise operations in order to be able to use less "variables" with bit masks for convenience.

**Comment by chrfalch** [comment]
@osdnk: What about reverse color interpolation? 

Say you have a node containing the current color and the color your want to animate it to is an RGB value as an integer. Then you'd need to perform the opposite of what the `color` function does.

**Comment by osdnk** [comment]
@wojtus7 can you show here how to obtain it w/out bitwise operators?

**Comment by wcandillon** [comment]
I concur with @chrfalch about the reverse color interpolation. It would be useful to have a function like red(node) that extract the red value of a color node.

I can totally see how people would use it to encode things more complex than colors within animation values ;-)

**Comment by wcandillon** [comment]
A use case would be to make color interpolation proc'able.
